import {
  AsteriskIcon,
  BinaryIcon,
  BookOpenTextIcon,
  BracketsCurlyIcon,
  ClockIcon,
  CodeIcon,
  DatabaseIcon,
  FileCodeIcon,
  FileCssIcon,
  FileCsvIcon,
  FileImageIcon,
  FileJsxIcon,
  FilesIcon,
  FileSqlIcon,
  FileSvgIcon,
  FileTxtIcon,
  FingerprintIcon,
  FlaskIcon,
  FlowArrowIcon,
  FrameCornersIcon,
  GitBranchIcon,
  GlobeHemisphereEastIcon,
  GlobeIcon,
  IdentificationCardIcon,
  ImageIcon,
  KeyIcon,
  LayoutIcon,
  LinkIcon,
  LockIcon,
  MarkdownLogoIcon,
  NetworkIcon,
  PaletteIcon,
  PasswordIcon,
  PlusMinusIcon,
  QrCodeIcon,
  ScalesIcon,
  ScanIcon,
  ShieldCheckeredIcon,
  ShieldCheckIcon,
  ShippingContainerIcon,
  StarIcon,
  SwatchesIcon,
  TerminalWindowIcon,
  TextTIcon,
} from "@phosphor-icons/react/ssr";

export const iconMap = {
  asterisk: AsteriskIcon,
  binary: BinaryIcon,
  "book-open-text": BookOpenTextIcon,
  "brackets-curly": BracketsCurlyIcon,
  clock: ClockIcon,
  code: CodeIcon,
  database: DatabaseIcon,
  "file-code": FileCodeIcon,
  "file-css": FileCssIcon,
  "file-csv": FileCsvIcon,
  "file-image": FileImageIcon,
  "file-jsx": FileJsxIcon,
  "file-sql": FileSqlIcon,
  "file-svg": FileSvgIcon,
  "file-txt": FileTxtIcon,
  files: FilesIcon,
  fingerprint: FingerprintIcon,
  flask: FlaskIcon,
  "flow-arrow": FlowArrowIcon,
  "frame-corners": FrameCornersIcon,
  "git-branch": GitBranchIcon,
  globe: GlobeIcon,
  "globe-hemisphere-east": GlobeHemisphereEastIcon,
  "identification-card": IdentificationCardIcon,
  image: ImageIcon,
  key: KeyIcon,
  layout: LayoutIcon,
  link: LinkIcon,
  lock: LockIcon,
  "markdown-logo": MarkdownLogoIcon,
  network: NetworkIcon,
  palette: PaletteIcon,
  password: PasswordIcon,
  "plus-minus": PlusMinusIcon,
  "qr-code": QrCodeIcon,
  scales: ScalesIcon,
  scan: ScanIcon,
  "shield-check": ShieldCheckIcon,
  "shield-checkered": ShieldCheckeredIcon,
  "shipping-container": ShippingContainerIcon,
  star: StarIcon,
  swatches: SwatchesIcon,
  "terminal-window": TerminalWindowIcon,
  "text-t": TextTIcon,
} as const;

export type IconName = keyof typeof iconMap;
