import { Resource } from "@/types";

import { CATEGORIES } from "./categories";
import { TAGS } from "./tags";

export const animationLinks: Resource[] = [
  {
    title: "Anime.js",
    author: "Julian Garnier",
    category: CATEGORIES.animation,
    description: "A fast, multipurpose and lightweight JavaScript animation library",
    favicon: "https://animejs.com/assets/images/favicon.png",
    gitHubLink: "https://github.com/juliangarnier/anime",
    ogImage: "https://animejs.com/media/pages/home/066c76f87b-1787698629/generated-og-image.en.png",
    subtitle: "JavaScript Animation Engine",
    tags: [TAGS.animation],
    url: "https://animejs.com/",
  },
  {
    title: "Animista",
    category: CATEGORIES.animation,
    description:
      "Animista is a CSS animation library and a place where you can play with a collection of ready-made CSS animations and download only those you will use.",
    favicon: "https://animista.net/images/favicons/apple-touch-icon-180x180.png",
    ogImage: "https://animista.net/animista-media-img.gif",
    subtitle: "On-Demand CSS Animations Library",
    tags: [TAGS.animation],
    url: "https://animista.net/",
  },
  {
    title: "Atropos",
    author: "nolimits4web",
    category: CATEGORIES.animation,
    description:
      "Atropos is a lightweight, free and open-source JavaScript library to create stunning touch-friendly 3D parallax hover effects.",
    favicon: "https://atroposjs.com/favicon.png",
    gitHubLink: "https://github.com/nolimits4web/atropos/",
    ogImage: "https://atroposjs.com/images/share-banner.png",
    subtitle: "Stunning touch-friendly 3D parallax hover effects",
    tags: [TAGS.animation],
    url: "https://atroposjs.com/",
  },
  {
    title: "AutoAnimate",
    author: "FormKit",
    category: CATEGORIES.animation,
    description:
      "A zero-config, drop-in animation utility that automatically adds smooth transitions to your web app. Use it with React, Solid, Vue, Svelte, or any other JavaScript application.",
    favicon: "https://auto-animate.formkit.com/assets/favicon-C1f1LLf8.svg",
    gitHubLink: "https://github.com/formkit/auto-animate",
    ogImage: "https://cdn.formk.it/web-assets/auto-animate-og.png",
    subtitle: "Add motion to your apps with a single line of code",
    tags: [TAGS.animation],
    url: "https://auto-animate.formkit.com/",
  },
  {
    title: "Blendy",
    category: CATEGORIES.animation,
    description:
      "Blendy, a framework-agnostic tool that smoothly transitions one element into another with just a few lines of code.",
    favicon: "https://blendy.tahazsh.com/favicon.svg",
    ogImage: "https://blendy.tahazsh.com/banner.png",
    subtitle: "Smoothly transition elements",
    tags: [TAGS.animation],
    url: "https://blendy.tahazsh.com/",
  },
  {
    title: "Border Beam",
    author: "Jakub Antalik",
    category: CATEGORIES.animation,
    className: "bg-foreground border-paper",
    description:
      "A lightweight React component that renders an animated glowing border beam effect. Supports multiple sizes, color variants, and themes.",
    favicon: "https://beam.jakubantalik.com/favicon.svg",
    ogImage: "https://beam.jakubantalik.com/og-v2.jpg",
    subtitle: "Animated border beam component for React",
    tags: [TAGS.animation],
    url: "https://beam.jakubantalik.com/",
  },
  {
    title: "Brik AI",
    category: CATEGORIES.animation,
    description:
      "Build your tailor-made stack of AI-powered design tools for animations, 2D & 3D visuals, text effects, and images. Remix, share, export, and scale.",
    favicon: "https://brik.space/favicon.svg",
    ogImage: "https://brik.space/images/og/og-default.png",
    subtitle: "Turn Creative Vision into Living Design Tools",
    tags: [TAGS.animation],
    url: "https://brik.space/",
  },
  {
    title: "CSS Loaders",
    author: "Temani Afif",
    category: CATEGORIES.animation,
    description:
      "The biggest collection of CSS-only loaders. More than 600 loading animations made by Temani Afif using a single element.",
    favicon: "https://css-loaders.com/fav.png",
    ogImage: "https://css-loaders.com/css-loader-banner.jpg",
    subtitle: "A collection of more than 600 loading animations",
    tags: [TAGS.animation],
    url: "https://css-loaders.com/",
  },
  {
    title: "CSS loaders and Spinners",
    author: "Vineeth TR",
    category: CATEGORIES.animation,
    className: "bg-foreground border-paper",
    description:
      "CSS Loader is a collection of different types of loaders, spinners and their source code. Pure CSS spinners with no image dependencies. Easily customizable CSS animations for loading states.",
    favicon: "https://cssloaders.github.io/images/apple-touch-icon.png",
    gitHubLink: "https://github.com/vineethtrv/css-loader",
    ogImage: "https://vineethtrv.github.io/assets/images/Loader-screen.png",
    tags: [TAGS.animation],
    url: "https://cssloaders.github.io/",
  },
  {
    title: "DASCA",
    author: "DASCA",
    category: CATEGORIES.animation,
    description:
      "Desktop visual effects software for video, images and 3D. Pixel sorting, dithering, blob tracking and more with real‑time previews and a smooth workflow.",
    favicon: "https://dasca.studio/favicon.png",
    ogImage: "https://dasca.studio/og-image.png",
    subtitle: "Real-Time Visual Effects for Image/Video/3D",
    tags: [TAGS.animation],
    url: "https://dasca.studio/",
  },
  {
    title: "Driver.js",
    author: "Kamran Ahmed",
    category: CATEGORIES.animation,
    description:
      "Driver.js is a lightweight, no-dependency JavaScript library for building product tours, feature highlights, hints and contextual help. It is just ~5kb and MIT licensed.",
    favicon: "https://driverjs.com/apple-touch-icon.png",
    gitHubLink: "https://github.com/nilbuild/driver.js",
    ogImage: "https://driverjs.com/og-img.png",
    subtitle: "Product Tours & Highlights in Vanilla JS",
    tags: [TAGS.animation],
    url: "https://driverjs.com/",
  },
  {
    title: "EaseMaster",
    author: "Satish Kumar",
    category: CATEGORIES.animation,
    description:
      "Design motion that feels real. The ultimate easing visualization tool for generating Cubic Bezier curves and Spring physics for CSS, Tailwind, Framer Motion, and GSAP.",
    favicon: "https://easemaster.satisui.xyz/icon0.svg",
    ogImage: "https://easemaster.satisui.xyz/og-image.png",
    subtitle: "CSS & Spring Easing Generator",
    tags: [TAGS.animation],
    url: "https://easemaster.satisui.xyz/",
  },
  {
    title: "Easing Graphs",
    author: "Lochie Axon",
    category: CATEGORIES.animation,
    description: "A curated collection of easing graphs",
    favicon: "https://www.easing.dev/logo.svg",
    ogImage: "https://easing.dev/opengraph-image.png",
    tags: [TAGS.animation],
    url: "https://www.easing.dev/",
  },
  {
    title: "Easing Wizard",
    author: "Matthias Martin",
    category: CATEGORIES.animation,
    description:
      "Generate and customize CSS easing functions with ease and magical precision using Easing Wizard 🧙",
    favicon: "https://easingwizard.com/favicon.svg",
    gitHubLink: "https://github.com/roydigerhund/easingwizard",
    ogImage: "https://easingwizard.com/share-image.png",
    subtitle: "CSS Easing Editor and Generator",
    tags: [TAGS.animation],
    url: "https://easingwizard.com/",
  },
  {
    title: "Epic Easing",
    category: CATEGORIES.animation,
    description:
      "Quickly and easily generate easing curves for ease, spring, and bounce animations. Utilize animation presets or create your own custom animation curve, spring, or bounce. Instantly export to CSS, SCSS, Objective-C, and Swift.",
    favicon: "https://epiceasing.com/apple-touch-icon.png",
    ogImage: "https://epiceasing.com/epiceasing_preview.png",
    tags: [TAGS.animation],
    url: "https://epiceasing.com/",
  },
  {
    title: "Flicker",
    author: "Laura Escobar",
    category: CATEGORIES.animation,
    description:
      "A loading spinner library inspired by flip-dot displays. Browse the collection, build your own, export to SVG, React, or Flutter.",
    favicon: "https://flicker.laurie.fyi/icon.svg",
    ogImage: "https://flicker.laurie.fyi/og-image.png",
    subtitle: "Spinner Library",
    tags: [TAGS.animation, TAGS.flutter, TAGS.react, TAGS.svg],
    url: "https://flicker.laurie.fyi/",
  },
  {
    title: "FliiipBook",
    author: "FliiipBook",
    category: CATEGORIES.animation,
    description:
      "Draw frame-by-frame animations and create GIFs directly in your browser. Simple, fun, and powerful animation tool with onion skinning, timeline controls, and instant GIF export.",
    favicon: "https://www.fliiipbook.com/favicon.ico",
    ogImage: "https://www.fliiipbook.com/og-image.png",
    tags: [TAGS.animation, TAGS.tool],
    url: "https://www.fliiipbook.com/",
  },
  {
    title: "FlipOff.",
    author: "magnum6actual",
    category: CATEGORIES.animation,
    description:
      "Free split-flap display emulator for any TV. The classic flip-board look, without the $3,500 hardware.",
    favicon: "/github.svg",
    ogImage:
      "https://opengraph.githubassets.com/baa7433f1bdde269f0a58eee23818c91bad29033f2e79a2acca349c79f803233/magnum6actual/flipoff",
    tags: [TAGS.animation],
    url: "https://github.com/magnum6actual/flipoff",
  },
  {
    title: "Grainrad",
    category: CATEGORIES.animation,
    description: "Grainrad - Free WebGPU-powered ASCII, dithering, and retro effects at 60fps",
    favicon: "https://grainrad.com/apple-touch-icon.png",
    ogImage: "https://grainrad.com/preview_thu.png",
    tags: [TAGS.animation],
    url: "https://grainrad.com/",
  },
  {
    title: "GSAP",
    category: CATEGORIES.animation,
    description:
      "Supported by Webflow. Animate Anything - A wildly robust JavaScript animation library built for professionals.",
    favicon: "https://gsap.com/apple-touch-icon.png",
    ogImage: "https://gsap.com/GSAP-share-image.png",
    tags: [TAGS.animation],
    url: "https://gsap.com/",
  },
  {
    title: "Image generation",
    author: "Jakub Antalik",
    category: CATEGORIES.animation,
    description: "Image generation loader and reveal component.",
    favicon: "https://image.jakubantalik.com/images/favicon.png",
    ogImage: "https://image.jakubantalik.com/images/og-image.jpg",
    tags: [TAGS.animation],
    url: "https://image.jakubantalik.com/",
  },
  {
    title: "Jitter",
    category: CATEGORIES.animation,
    description:
      "Jitter is a collaborative motion design tool that lets you create professional animations in minutes, no matter your experience with motion.",
    favicon: "https://jitter.video/icons/icon-48x48.png",
    ogImage: "https://jitter.video/assets/homepage-2026-DXrOP74Y.png",
    subtitle: "A fast and simple motion design tool on the web",
    tags: [TAGS.animation],
    url: "https://jitter.video/",
  },
  {
    title: "Kinetics",
    author: "Csaba Kissi",
    category: CATEGORIES.animation,
    description:
      "A library of spring-driven micro-interactions for web apps. Copy the CSS or React, tune the physics, ship the motion.",
    favicon: "https://kinetics.colorion.co/favicon.svg",
    ogImage: "https://kinetics.colorion.co/og-image.png",
    subtitle: "Spring-physics motion for web interfaces",
    tags: [TAGS.animation, TAGS.css, TAGS["ui-component"]],
    url: "https://kinetics.colorion.co/",
  },
  {
    title: "LottieFiles",
    category: CATEGORIES.animation,
    description:
      "Effortlessly bring the smallest, free, ready-to-use motion graphics for the web, app, social, and designs. Create, edit, test, collaborate, and ship Lottie animations in no time!",
    favicon: "https://lottiefiles.com/icons/favicon.svg",
    ogImage: "https://stp-v4-cdn.lottiefiles.com/ogimage_Homepage_b5840ac00c.png",
    tags: [TAGS.animation],
    url: "https://lottiefiles.com/",
  },
  {
    title: "Lottieflow",
    category: CATEGORIES.animation,
    description:
      "Download Lottie icon animations to implement on your Webflow website. Change hex color, customize easing, and download json files to use Lottie with Webflow Interactions. Made by Finsweet.",
    favicon:
      "https://cdn.prod.website-files.com/5d76680dc57fa0f42dcfe0c5/5d769663344fac12df06fae1_fav-awesome.png",
    ogImage:
      "https://cdn.prod.website-files.com/5d76680dc57fa0f42dcfe0c5/5dc214043af52b276dd35223_lottieflow-og-image.jpg",
    subtitle: "Lottie icon animations for Webflow",
    tags: [TAGS.animation],
    url: "https://finsweet.com/lottieflow",
  },
  {
    title: "Lottielab",
    category: CATEGORIES.animation,
    description:
      "Create and ship animations to your products faster. Bring your websites and apps to life with the simplest editor for Lottie animations.",
    favicon: "https://www.lottielab.com/apple-touch-icon.png",
    subtitle: "Create & edit Lottie animations",
    tags: [TAGS.animation],
    url: "https://www.lottielab.com/",
  },
  {
    title: "Matter.js",
    author: "liabru",
    category: CATEGORIES.animation,
    description: "Matter.js is 2D rigid body JavaScript physics engine for the web",
    favicon: "https://brm.io/img/icon/apple-touch-icon.png",
    ogImage: "https://brm.io/matter-js/img/matter-js.svg",
    tags: [TAGS.animation],
    url: "https://brm.io/matter-js/",
  },
  {
    title: "Motion",
    category: CATEGORIES.animation,
    description:
      "Motion (prev Framer Motion) is a fast, production-grade animation library for React, JavaScript and Vue. Build smooth UI animations at a tiny footprint.",
    favicon: "https://motion.dev/favicon.svg",
    ogImage: "https://images.motion.dev/og/fresh/v1/site/home-3jhn8b0abpu66.png",
    subtitle: "JavaScript & React animation library",
    tags: [TAGS.animation],
    url: "https://motion.dev/",
  },
  {
    title: "Rive",
    author: "Rive",
    authorLink: "https://github.com/rive-app",
    category: CATEGORIES.animation,
    description:
      "Behind Spotify Wrapped, Duolingo, and products reaching 2 billion users. Design, animate, and code in one place. Ship everywhere.",
    favicon: "https://framerusercontent.com/images/jMyKrhKKXqpc15qYqC3A0pZELw.png",
    ogImage: "https://framerusercontent.com/images/yEWMbP7UtsS81SlkoxTasfabvc.png",
    subtitle: "The interactive experience engine",
    tags: [TAGS.animation],
    url: "https://rive.app/",
  },
  {
    title: "Shaders",
    author: "Shader Effects Inc.",
    category: CATEGORIES.animation,
    description:
      "Component library for creative WebGPU effects in modern frontend frameworks. Compose interactive visuals for Vue, React, Svelte, Solid & JS.",
    favicon: "https://shaders.com/icon.svg",
    ogImage: "https://shaders.com/og.jpg",
    subtitle: "The design platform for web shaders",
    tags: [TAGS.animation],
    url: "https://shaders.com/",
  },
  {
    title: "Smooothy",
    author: "Federico Valla",
    category: CATEGORIES.animation,
    description: "Smooth configurable extendable slider made for animation.",
    favicon: "https://smooothy.vercel.app/favicon_svg.svg",
    gitHubLink: "https://github.com/vallafederico/smooothy",
    ogImage: "https://smooothy.vercel.app/og_img1.jpg",
    tags: [TAGS.animation],
    url: "https://smooothy.vercel.app/",
  },
  {
    title: "Spline",
    category: CATEGORIES.animation,
    description:
      "Spline is a free 3D design software with real-time collaboration to create web interactive experiences in the browser. Easy 3d modeling, animation, textures, and more.",
    favicon:
      "https://spline.design/_next/image?url=%2F_next%2Fstatic%2Fimmutable%2Fmedia%2Fspline_logo.18-bh7nan-wgm.png&w=128&q=75",
    ogImage:
      "https://spline.design/_next/static/immutable/media/spline_image_banner.2at491x3fx670.png",
    subtitle: "3D Design tool in the browser with real-time collaboration",
    tags: [TAGS.animation],
    url: "https://spline.design/",
  },
  {
    title: "SSGOI",
    author: "MeurSyphus",
    category: CATEGORIES.animation,
    description:
      "Router-agnostic page transitions for React, Svelte, Vue, Solid, Angular, and Qwik. Built on the Web Animations API with spring physics and state preservation.",
    favicon: "https://ssgoi.dev/ssgoi-logo.png",
    ogImage: "https://ssgoi.dev/og.png",
    subtitle: "Native page transitions on the web",
    tags: [TAGS.animation],
    url: "https://ssgoi.dev/",
  },
  {
    title: "SVGator",
    category: CATEGORIES.animation,
    description:
      "Create impressive SVG animations and more. Add them easily to your website or app. Get started for free!",
    favicon: "https://www.svgator.com/favicon.svg",
    ogImage: "https://cdn.svgator.com/assets/og-images/main-page-og.jpg",
    subtitle: "Free Animation Maker Online",
    tags: [TAGS.animation, TAGS.svg],
    url: "https://www.svgator.com/",
  },
  {
    title: "SVG Spinners",
    category: CATEGORIES.animation,
    description:
      "Collection of 100+ Open Source SVG-based icons you can use to show content is being loaded. Absolutely free with no attribution required.",
    favicon: "https://magecdn.com/assets/icons/favicon.png",
    ogImage: "https://i.magecdn.com/d2b508/ee0b63_og_image_3?f=png",
    subtitle: "Open Source SVG Loading Icons",
    tags: [TAGS.animation, TAGS.svg, TAGS["ui-component"]],
    url: "https://magecdn.com/tools/svg-loaders",
  },
  {
    title: "SVG Studio",
    category: CATEGORIES.animation,
    description:
      "SVG Studio — a free, browser-based SVG animation editor. No sign-up, no telemetry, no subscription.",
    favicon: "https://www.svgstudio.org/images/favicon.svg",
    ogImage: "https://www.svgstudio.org/images/social-2.png",
    subtitle: "Animate Everything",
    tags: [TAGS.animation, TAGS.svg],
    url: "https://www.svgstudio.org/",
  },
  {
    title: "Swishy",
    author: "Swishy",
    category: CATEGORIES.animation,
    description:
      "Swishy is the leading AI motion designer and AI animator platform. Create professional motion graphics, animated typefaces, and stunning video animations without After Effects. Export to MP4, MOV, and GIF instantly.",
    favicon: "https://www.swishy.ai/icon.svg",
    ogImage: "https://www.swishy.ai/og-image.png",
    subtitle: "AI Motion Designer & Animator | Create Stunning Animations",
    tags: [TAGS.animation],
    url: "https://www.swishy.ai/",
  },
  {
    title: "Tailwind CSS Animations Plugin",
    author: "Miguel Ángel Durán (midudev)",
    category: CATEGORIES.animation,
    description:
      "Add 79+ ready-to-use CSS animations to Tailwind CSS with utility classes. Fade, slide, zoom, scroll-driven motion, and dialog effects. Zero config, open source by midudev.",
    favicon: "https://tailwind-animations.com/favicon.svg",
    ogImage: "https://tailwind-animations.com/og.jpg",
    subtitle: "79+ Utility Classes",
    tags: [TAGS.animation],
    url: "https://tailwindcss-animations.vercel.app",
  },
  {
    title: "Torph",
    author: "Lochie Axon",
    category: CATEGORIES.animation,
    description: "Dependency-free animated text component.",
    favicon: "https://torph.lochie.me/icon.svg",
    gitHubLink: "https://github.com/lochie/torph",
    ogImage: "https://torph.lochie.me/opengraph-image.png",
    subtitle: "Dependency-Free Text Morphing",
    tags: [TAGS.animation, TAGS.typography],
    url: "https://torph.lochie.me/",
  },
  {
    title: "Transitions.dev",
    author: "Jakub Antalik",
    category: CATEGORIES.animation,
    description:
      "Collection of the most essential transitions for web apps that you can just copy and paste into any project.",
    favicon: "https://transitions.dev/assets/favicon-light-mode.png",
    ogImage: "https://transitions.dev/assets/og-main.jpg",
    subtitle: "Essential transitions for web apps",
    tags: [TAGS.animation],
    url: "https://transitions.dev/",
  },
  {
    title: "Unicorn Studio",
    category: CATEGORIES.animation,
    description:
      "Create interactive motion and real-time graphics for the web. Stack layers on a real-time canvas, shape them with effects and motion, expose controls, and ship.",
    favicon: "https://www.unicorn.studio/favicon.png",
    ogImage: "https://www.unicorn.studio/images/ogg2.png",
    subtitle: "Interactive Motion & Real-Time Graphics",
    tags: [TAGS.animation, TAGS.noCode],
    url: "https://www.unicorn.studio/",
  },
  {
    title: "Video for Web",
    author: "Lochie Axon",
    category: CATEGORIES.animation,
    description:
      "Seamless online playback by encoding videos into ideal formats, ensuring smooth streaming, fast loading times, and minimal bandwidth usage across devices.",
    favicon: "https://compress.lochie.me/logo.svg",
    ogImage: "https://compress.lochie.me/opengraph-image.png",
    subtitle: "Optimized Video Encoding for Seamless Playback",
    tags: [TAGS.video],
    url: "https://compress.lochie.me/",
  },
  {
    title: "WebHaptics",
    author: "Lochie Axon",
    category: CATEGORIES.animation,
    description: "Haptic feedback for the mobile web.",
    favicon:
      "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>%F0%9F%AB%A8</text></svg>",
    gitHubLink: "https://github.com/lochie/web-haptics",
    ogImage: "https://haptics.lochie.me/og.png",
    tags: [TAGS.animation],
    url: "https://haptics.lochie.me/",
  },
];
