import { Resource } from "@/types";

import { CATEGORIES } from "./categories";
import { TAGS } from "./tags";

export const colorLinks: Resource<typeof CATEGORIES.colors>[] = [
  {
    title: "Actionable Color Palettes",
    author: "Csaba Kissi",
    category: CATEGORIES.colors,
    description: "Hand curated color palettes with previews",
    tags: [TAGS.color],
    url: "https://colorpalettes.colorion.co/",
  },
  {
    title: "AniMaps",
    author: "Sarthak Navalekar",
    category: CATEGORIES.colors,
    description:
      "Build animated route maps in React, then export them as video or share them. A travelling marker traces your journey across the map.",
    favicon: "https://feralui.dev/apple-touch-icon.png",
    ogImage: "https://feralui.dev/og-hero.png",
    url: "https://feralui.dev/animaps",
  },
  {
    title: "Blinds",
    author: "Sarthak Navalekar",
    category: CATEGORIES.colors,
    description:
      "An expanding gallery of slats on real springs for React. Hover to open a panel with momentum, watch neighbours squeeze aside, pin with a click, or let autoplay drive.",
    favicon: "https://feralui.dev/apple-touch-icon.png",
    ogImage: "https://feralui.dev/og-hero.png",
    url: "https://feralui.dev/blinds",
  },
  {
    title: "Chromatic Profiles",
    author: "Pixel Symphony",
    category: CATEGORIES.colors,
    description:
      "Colorists in the Colorist Archive: browse chromatic profiles, artwork palettes, and generative color studies across artists, periods, and collections.",
    favicon: "https://meditationsincolor.com/apple-touch-icon.png",
    ogImage: "https://meditationsincolor.com/assets/mic-logo-1024.png",
    subtitle: "Meditations in Color",
    tags: [TAGS.color],
    url: "https://meditationsincolor.com/colorists",
  },
  {
    title: "Colir",
    category: CATEGORIES.colors,
    className: "bg-foreground border-paper",
    description:
      "Create unique, professional gradients with curve-based control. Real-time WebGL rendering, 12 blend modes, and advanced visual effects.",
    favicon: "https://colir.space/Logos/logo.svg",
    ogImage: "https://colir.space/Templates/OG_colir.png",
    subtitle: "Gradients",
    tags: [TAGS.color],
    url: "https://colir.space/",
  },
  {
    title: "Colorffy",
    category: CATEGORIES.colors,
    description:
      "Create beautiful color schemes, dynamic gradients, and custom themes with Colorffy—the ultimate CSS color palette generator and designer toolkit suite.",
    favicon: "https://colorffy.com/icon-pwa.svg",
    ogImage: "https://colorffy.com/seo/seo-home.png",
    subtitle: "Create Beautiful CSS Color Palettes & UI Themes",
    tags: [TAGS.color],
    url: "https://colorffy.com/",
  },
  {
    title: "ColorFlow",
    author: "ColorFlow",
    category: CATEGORIES.colors,
    description:
      "Create stunning mesh gradients with ColorFlow. Professional gradient editor with real-time preview, customizable control points, and export options. Perfect for designers and developers.",
    favicon: "https://colorflow.ls.graphics/apple-touch-icon.png",
    ogImage: "https://colorflow.ls.graphics/og-image.jpg",
    subtitle: "Advanced Mesh Gradient Generator & Editor",
    tags: [TAGS.color],
    url: "https://colorflow.ls.graphics/",
  },
  {
    title: "Color Generator",
    category: CATEGORIES.colors,
    description: "Generate beautiful color palettes for your design system.",
    favicon: "https://kigen.design/kigen-logo-icon.svg",
    ogImage: "https://kigen.design/color-og.jpg",
    tags: [TAGS.color],
    url: "https://kigen.design/color",
  },
  {
    title: "ColorHub",
    author: "Dan Cranney",
    category: CATEGORIES.colors,
    description: "Find the perfect color palette for your next project",
    favicon: "https://www.colorhub.app/favicon.png",
    ogImage:
      "https://raw.githubusercontent.com/danielcranney/repo-storage/main/colorhub-v2-meta-image.jpg",
    tags: [TAGS.color],
    url: "https://www.colorhub.app/",
  },
  {
    title: "Color Hunt",
    category: CATEGORIES.colors,
    description:
      "Discover the newest hand-picked color palettes of Color Hunt. Get color inspiration for your design and art projects.",
    favicon: "https://colorhunt.co/img/colorhunt-favicon.svg",
    ogImage: "https://colorhunt.co/img/color-hunt-og.png",
    subtitle: "Color Palettes for Designers and Artists",
    tags: [TAGS.color],
    url: "https://colorhunt.co/",
  },
  {
    title: "colorion",
    author: "Csaba Kissi",
    category: CATEGORIES.colors,
    description: "Discover, save, and copy modern color palettes for your next project.",
    favicon: "https://colorion.co/favicon.svg",
    ogImage: "https://colorion.co/og-image.png",
    subtitle: "Curated Color Palettes",
    tags: [TAGS.color],
    url: "https://colorion.co/",
  },
  {
    title: "Colorize",
    category: CATEGORIES.colors,
    description:
      "Generate color palettes instantly from any website effortlessly. Enter a URL to explore color schemes and combinations directly from the site's design. No sign-up required. Try it now!",
    favicon: "https://colorize.design/favicon.svg",
    ogImage: "https://colorize.design/og-image.jpg",
    subtitle: "Extract Color Palettes from Any Website - Free Color Palette Generator",
    tags: [TAGS.color],
    url: "https://colorize.design/",
  },
  {
    title: "Color Lab",
    author: "naymur rahman",
    category: CATEGORIES.colors,
    description:
      "Color Lab is your all-in-one color and UI toolkit. Create stunning palettes, convert between HEX, RGB, HSL, and design custom themes with the built-in Shadcn UI Theme Generator – ideal for designers and frontend developers.",
    favicon: "https://tools.ui-layouts.com/favicon.ico",
    ogImage: "https://tools.ui-layouts.com/color-lab-og.jpg",
    subtitle: "Generate Color Palettes, Convert Codes & Build Shadcn Themes",
    tags: [TAGS.color],
    url: "https://tools.ui-layouts.com/color-lab",
  },
  {
    title: "Colormind",
    category: CATEGORIES.colors,
    className:
      "bg-foreground border-paper overflow-hidden [&>img]:translate-x-[16%] [&>img]:-translate-y-[9%] [&>img]:scale-125",
    description:
      "Generate color combinations in one click. Colormind creates cohesive color schemes using a deep neural net.",
    favicon: "https://colormind.io/img/logo_nav.svg",
    ogImage: "https://colormind.io/img/logo.png",
    subtitle: "The AI powered color palette generator",
    tags: [TAGS.color],
    url: "https://colormind.io/",
  },
  {
    title: "Color Moods",
    category: CATEGORIES.colors,
    description: "Generate pairs of colors based on the amount of stimulation you select.",
    favicon: "https://colormoods.co/assets/images/favicon/apple-touch-icon.png",
    ogImage: "https://colormoods.co/assets/images/og-image.jpg",
    tags: [TAGS.color],
    url: "https://colormoods.co/",
  },
  {
    title: "Color Name Finder",
    author: "Jasper Bernaers",
    category: CATEGORIES.colors,
    description:
      "Free color name finder — identify any HTML color by name, HEX, RGB or HSL. Browse all 140+ CSS named colours, search by hue, and copy values instantly. No signup.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/colours/og-image.png",
    subtitle: "HTML Colour Names, HEX, RGB, HSL",
    tags: [TAGS.color],
    url: "https://jasperbernaers.com/colours/",
  },
  {
    title: "Color Palette Generator",
    author: "Csaba Kissi",
    category: CATEGORIES.colors,
    description: "Generate new color palette generator with every press of the spacebar",
    favicon: "https://palettegenerator.colorion.co/thumbnail.png",
    ogImage: "https://palettegenerator.colorion.co/shared.png",
    tags: [TAGS.color],
    url: "https://palettegenerator.colorion.co/",
  },
  {
    title: "Color Palette Pro",
    category: CATEGORIES.colors,
    description:
      "Generate customizable color palettes in advanced color spaces that can be easily shared, downloaded, or exported.",
    favicon: "https://colorpalette.pro/favicon.svg",
    ogImage: "https://colorpalette.pro/colorpalettepro.png",
    tags: [TAGS.color],
    url: "https://colorpalette.pro/",
  },
  {
    title: "Colour Contrast Checker",
    author: "Alex Clapperton",
    category: CATEGORIES.colors,
    description: "Check the contrast between different colour combinations against WCAG standards.",
    favicon: "https://colourcontrast.cc/favicons/apple-touch-icon.png",
    gitHubLink: "https://github.com/Pushedskydiver/Colour-Contrast-Checker",
    url: "https://colourcontrast.cc/",
  },
  {
    title: "Contrast Report",
    author: "Adam Chaboryk",
    category: CATEGORIES.colors,
    description: "Straightforward colour contrast checker with Picture-in-picture (PiP) mode.",
    favicon:
      "https://raw.githubusercontent.com/adamchaboryk/contrast.report/main/public/icons/icon-384x384.webp",
    ogImage: "https://contrast.report/og-contrast-report.png",
    subtitle: "WCAG Colour Contrast Checker",
    url: "https://contrast.report/",
  },
  {
    title: "Coolors",
    author: "Fabrizio Bianchi",
    authorLink: "https://fabrizio.io/",
    category: CATEGORIES.colors,
    description: "Generate or browse beautiful color combinations for your designs.",
    favicon: "https://coolors.co/assets/img/favicon.png",
    ogImage: "https://coolors.co/assets/img/og_image.png",
    subtitle: "The super fast color palettes generator!",
    tags: [TAGS.color],
    url: "https://coolors.co/",
  },
  {
    title: "CSS Gradient",
    category: CATEGORIES.colors,
    description:
      "As a free CSS gradient generator tool, this website lets you create a colorful gradient background for your website, blog, or social media profile.",
    favicon: "https://cssgradient.io/icon.svg",
    gitHubLink: "https://github.com/balshaer/gradients-css",
    ogImage:
      "https://cssgradient.imgix.net/2bJFIYjQAMqSz44evG5Pel/f973f26f3b70726a8e1aed05da781625/css-gradient.png",
    subtitle: "Generator, Maker, and Background",
    tags: [TAGS.color],
    url: "https://cssgradient.io/",
  },
  {
    title: "Font Freezer",
    author: "Anton Gridz",
    authorLink: "https://antongridz.com/",
    category: CATEGORIES.colors,
    description:
      "Freeze OpenType features and variable axes into static font files. No coding required.",
    favicon: "https://fontfreezer.com/static/favicon.svg",
    ogImage: "https://fontfreezer.com/static/img/og-image.png",
    url: "https://fontfreezer.com/",
  },
  {
    title: "Free Gradient Generator",
    author: "Sarthak Navalekar",
    category: CATEGORIES.colors,
    description:
      "Free online gradient generator. Blend soft mesh, grainy, and animated gradients from traditional Japanese colours, then export as SVG, PNG, or MP4 video. No signup.",
    favicon: "https://feralui.dev/apple-touch-icon.png",
    ogImage: "https://feralui.dev/og-hero.png",
    subtitle: "Mesh, grainy and animated gradients",
    tags: [TAGS.color, TAGS.gradient],
    url: "https://feralui.dev/gradients",
  },
  {
    title: "Fur",
    author: "Sarthak Navalekar",
    category: CATEGORIES.colors,
    description:
      "A pettable coat of fur rendered strand by strand on canvas, that parts and reacts to your cursor and touch.",
    favicon: "https://feralui.dev/apple-touch-icon.png",
    ogImage: "https://feralui.dev/og-hero.png",
    url: "https://feralui.dev/fur",
  },
  {
    title: "Gradient Colors Collection",
    author: "GradientsCSS",
    category: CATEGORIES.colors,
    description:
      "Discover and explore beautiful gradient colors for your projects. GradientsCSS offers a curated collection of gradient palettes for web design and creative work.",
    favicon: "https://gradientscss.vercel.app/favicon/favicon.svg",
    ogImage: "https://gradientscss.vercel.app/favicon/banner.jpg",
    tags: [TAGS.color],
    url: "https://gradientscss.vercel.app/",
  },
  {
    title: "GradLab",
    author: "Superbobo",
    category: CATEGORIES.colors,
    description:
      "GradLab is a free online gradient generator — create animated mesh gradients and download as PNG, MP4 video, or standalone HTML. No sign-up, no watermark. Also known as GradientLab.",
    ogImage: "https://www.gradlab.app/og-image.png",
    subtitle: "Free Gradient Generator | Download PNG, MP4 & HTML",
    url: "https://www.gradlab.app/",
  },
  {
    title: "Graduum",
    author: "Niklaus Gerber",
    category: CATEGORIES.colors,
    description:
      "A collection of one hundred free high-quality mesh gradients suitable for desktop and mobile use.",
    favicon: "https://graduum.niklausgerber.com/assets/images/apple-touch-icon.png?v=a66bfeb6",
    ogImage: "https://graduum.niklausgerber.com/assets/images/share.jpg?v=a66bfeb6",
    subtitle: "Free Mesh Gradients by Niklaus Gerber",
    tags: [TAGS.color],
    url: "https://graduum.niklausgerber.com/",
  },
  {
    title: "Happy Hues",
    author: "Mackenzie Child",
    category: CATEGORIES.colors,
    description:
      "See color palette inspiration on a real example website. As you click on different palettes every color on this site updates to give you context of how that color could be used for your design or illustration projects.",
    favicon:
      "https://cdn.prod.website-files.com/5dd40aa8049df8748c72d0ee/5dd9b92056a2d6ed5e537c61_happy-hues-apple-icon.png",
    ogImage:
      "https://cdn.prod.website-files.com/5dd40aa8049df8748c72d0ee/5ddd471cbe5e6601554a2a4d_happy-hues.jpeg",
    subtitle: "Curated colors in context",
    tags: [TAGS.color],
    url: "https://www.happyhues.co/",
  },
  {
    title: "Harmonizer",
    author: "Evil Martians",
    category: CATEGORIES.colors,
    description: "Color palette generator for UI",
    favicon: "https://harmonizer.evilmartians.com/favicon.svg",
    ogImage: "https://harmonizer.evilmartians.com/social-image.png",
    tags: [TAGS.color],
    url: "https://harmonizer.evilmartians.com/",
  },
  {
    title: "Hologram",
    author: "Sarthak Navalekar",
    category: CATEGORIES.colors,
    description:
      "A foil holographic trading card for React that catches and scatters light as you tilt it, like a real Pokemon-style foil.",
    favicon: "https://feralui.dev/apple-touch-icon.png",
    ogImage: "https://feralui.dev/og-hero.png",
    url: "https://feralui.dev/hologram",
  },
  {
    title: "Hypercolor",
    category: CATEGORIES.colors,
    description:
      "A curated collection of beautiful Tailwind CSS gradients using the full range of Tailwind CSS colors. Easily copy and paste the class names, CSS or even save the gradients as an image.",
    favicon: "https://hypercolor.dev/favicon.png",
    tags: [TAGS.color],
    url: "https://hypercolor.dev/",
  },
  {
    title: "ImageColorPicker.com",
    category: CATEGORIES.colors,
    description:
      "Upload an image, paste from clipboard, or enter a URL to instantly pick colors. Get HEX, RGB, HSL codes free — no signup required.",
    favicon: "https://imagecolorpicker.com/favicon.svg",
    ogImage: "https://imagecolorpicker.com/imagecolorpicker-preview_b.webp",
    subtitle: "Pick Colors from Any Image – Free HEX, RGB & Color Codes",
    tags: [TAGS.color],
    url: "https://imagecolorpicker.com/",
  },
  {
    title: "Ingradients",
    author: "Gilbert Pellegrom",
    category: CATEGORIES.colors,
    description: "Hand-picked mesh gradients for your next design project.",
    favicon:
      "https://framerusercontent.com/modules/reOxh1U6VCuZnfou6x2m/eJmnQAJafZ0DjECK4JSI/assets/oYzfVi4pX5vTuybl3rTEXooXk.png",
    ogImage:
      "https://framerusercontent.com/modules/reOxh1U6VCuZnfou6x2m/eJmnQAJafZ0DjECK4JSI/assets/S3wd0yoFBBYAKv1E4nAuhoWxC8.jpg",
    tags: [TAGS.color, TAGS.gradient],
    url: "https://ingradients.net/",
  },
  {
    title: "Khroma",
    author: "George Hastings",
    category: CATEGORIES.colors,
    description:
      "Khroma is the fastest way to discover, search, and save color combos and palettes you'll love. Discover a personalized AI-powered color tool for designers to find the perfect color scheme.",
    favicon: "https://www.khroma.co/assets/icons/fav.png",
    ogImage: "https://www.khroma.co/assets/images/social.png",
    subtitle: "AI Color Tool for Designers | Discover and Save Color Palettes",
    tags: [TAGS.color],
    url: "https://www.khroma.co/",
  },
  {
    title: "Mesh Gradient",
    category: CATEGORIES.colors,
    description: "MESH is a simple way to create beautiful, unique gradients using shaders.",
    favicon: "https://meshgradient.com/logo-sm.svg",
    tags: [TAGS.color],
    url: "https://meshgradient.com/",
  },
  {
    title: "MotionView",
    author: "Sarthak Navalekar",
    category: CATEGORIES.colors,
    description:
      "Free motion template studio. Drop in a few images, pick a motion like Carousel or Orbit, tune the dials, and export a seamless MP4 loop. No signup.",
    favicon: "https://feralui.dev/apple-touch-icon.png",
    ogImage: "https://feralui.dev/og-hero.png",
    url: "https://feralui.dev/motionview",
  },
  {
    title: "Movie Poster Archive",
    author: "Pixel Symphony",
    category: CATEGORIES.colors,
    description:
      "A searchable chromatic archive of movie poster design. Directors, their film posters, and the color systems inside them.",
    favicon: "https://meditationsincolor.com/apple-touch-icon.png",
    subtitle: "Meditations in Color",
    tags: [TAGS.color],
    url: "https://meditationsincolor.com/movies",
  },
  {
    title: "mymind",
    author: "mymind",
    authorLink: "https://mymind.com/",
    category: CATEGORIES.colors,
    description: "A collection of unique color combinations for your design projects.",
    favicon: "https://static.accelerator.net/134/0.107.0/images/apple-touch-icon.png",
    ogImage: "https://static.accelerator.net/134/0.107.0/colors/images/mymind-colors-twitter.jpg",
    subtitle: "Mindfully curated color palettes",
    tags: [TAGS.color],
    url: "https://access.mymind.com/colors",
  },
  {
    title: "oklch.fyi",
    category: CATEGORIES.colors,
    description:
      "Build palettes with consistent lightness and predictable shades, convert between formats, and explore gamut — all in OKLCH.",
    favicon: "https://oklch.fyi/favicon.ico",
    ogImage: "https://zaevelstnancdrwi.public.blob.vercel-storage.com/oklch-og.png",
    subtitle: "Pick, convert and generate OKLCH colors",
    tags: [TAGS.color],
    url: "https://oklch.fyi/",
  },
  {
    title: "OKLCH Color Picker & Converter",
    author: "Evil Martians",
    category: CATEGORIES.colors,
    description: "OKLCH is a new way to encode colors (like hex, RGBA, or HSL)",
    favicon: "https://oklch.com/oklch-BhPJAgVY.svg",
    ogImage: "https://oklch.com/og-oklch.png",
    tags: [TAGS.color],
    url: "https://oklch.com/",
  },
  {
    title: "Orrery",
    author: "Noor Mtir",
    category: CATEGORIES.colors,
    description:
      "An immersive, cinematic Solar System simulator with procedural gradient shader planets, responsive camera orbits, and poetic first-person planetary monologues.",
    favicon: "https://cosmos.nourmtir22.workers.dev/favicon.svg",
    ogImage: "https://cosmos.nourmtir22.workers.dev/og-image.png",
    subtitle: "Cinematic Solar System Experience",
    url: "https://cosmos.nourmtir22.workers.dev/",
  },
  {
    title: "Palette Maker",
    category: CATEGORIES.colors,
    description:
      "Free color tool for creatives and color lovers. Create color palettes and preview them on UI/UX, Illustrations, Web, Apps, Branding and other designs.",
    tags: [TAGS.color],
    url: "https://palettemaker.com/",
  },
  {
    title: "Paletton",
    category: CATEGORIES.colors,
    description:
      "In love with colors, since 2002. A designer tool for creating color combinations that work together well. Formerly known as Color Scheme Designer. Use the color wheel to create great color palettes.",
    favicon: "https://paletton.com/img/favicon-128.png",
    ogImage: "https://paletton.com/img/paletton-preview-20140414.png",
    subtitle: "The Color Scheme Designer",
    tags: [TAGS.color],
    url: "https://paletton.com/",
  },
  {
    title: "Paperlab",
    author: "Noor Mtir",
    category: CATEGORIES.colors,
    description:
      "Physical, realistic paper as a React component. Real 3D geometry that peels, unrolls, folds and hangs — preset-driven, serializable, agent-first.",
    url: "https://paperlab.nawwara.studio/editor/",
  },
  {
    title: "Photo Gradient",
    category: CATEGORIES.colors,
    description: "Generate beautiful gradients from colors or from a photo",
    ogImage: "https://photogradient.com/social-image.png",
    subtitle: "Image to Mesh Gradient",
    tags: [TAGS.gradient],
    url: "https://photogradient.com/",
  },
  {
    title: "Picture Palette",
    category: CATEGORIES.colors,
    description: "Aesthetically pleasing color palettes based on aesthetically pleasing pictures.",
    tags: [TAGS.color],
    url: "https://picture-palette.web.app/",
  },
  {
    title: "Picular",
    category: CATEGORIES.colors,
    description:
      "Picular is a rocket fast primary color generator using Google’s image search. If you ever needed the perfect yellow hex code from a banana, this is the tool for you.",
    favicon: "https://picular.co/images/favicon-base.png",
    tags: [TAGS.color],
    url: "https://picular.co/",
  },
  {
    title: "Poline",
    category: CATEGORIES.colors,
    description:
      "Poline is lightweight, dependency free and fast JavaScript function written in TypeScript. It draws lines between anchors over polar HSL coordinates to generate pleasing color palettes.",
    favicon: "https://meodai.github.io/poline/poline-wheel.png",
    ogImage: "https://meodai.github.io/poline/socialfb.png",
    subtitle: "Esoteric Color Palette Generation Library",
    url: "https://meodai.github.io/poline/",
  },
  {
    title: "PullCord",
    author: "Sarthak Navalekar",
    category: CATEGORIES.colors,
    description:
      "A ceiling pull-cord React component with a real Verlet-integration rope that hangs and swings. Give it a tug to toggle light and dark.",
    favicon: "https://feralui.dev/apple-touch-icon.png",
    ogImage: "https://feralui.dev/og-hero.png",
    url: "https://feralui.dev/pullcord",
  },
  {
    title: "Radix Colors",
    author: "Radix",
    category: CATEGORIES.colors,
    description:
      "An open-source color system for designing beautiful, accessible websites and apps.",
    favicon: "https://www.radix-ui.com/favicon-black.svg",
    ogImage: "https://radix-ui.com/colors/opengraph-image.png",
    tags: [TAGS.color],
    url: "https://www.radix-ui.com/colors",
  },
  {
    title: "RandomA11y",
    category: CATEGORIES.colors,
    description:
      "Discover millions of accessible color combinations with RandomA11y, the real-time color playground.",
    ogImage: "https://randoma11y-feed.adam-f8f.workers.dev/og-image.png",
    subtitle: "Endless collection of accessible color combos",
    tags: [TAGS.color],
    url: "https://randoma11y.com/",
  },
  {
    title: "Realtime Colors",
    category: CATEGORIES.colors,
    description: "Visualize your colors and fonts on a real website.",
    tags: [TAGS.color],
    url: "https://www.realtimecolors.com/",
  },
  {
    title: "Scale",
    author: "Hayk An",
    category: CATEGORIES.colors,
    description: "Color scale generator by Hayk An",
    favicon: "https://hihayk.github.io/scale/favicon.ico",
    ogImage: "https://raw.githubusercontent.com/hihayk/scale/master/docs/screenshot-1.png",
    subtitle: "Color scale generator",
    tags: [TAGS.color],
    url: "https://hihayk.github.io/scale",
  },
  {
    title: "Shadecolr",
    author: "Radix",
    category: CATEGORIES.colors,
    description:
      "Generate Tailwind CSS color palettes for SaaS dashboards, product UI, and client projects. Preview them in a real interface and export usable shades fast.",
    favicon: "https://www.shadecolr.com/image/favicon/favicon.svg",
    ogImage: "https://www.shadecolr.com/image/shadecolr-cover.png",
    subtitle: "Generate color palettes for Tailwind CSS",
    tags: [TAGS.color],
    url: "https://www.shadecolr.com/",
  },
  {
    title: "Shader Gradient",
    category: CATEGORIES.colors,
    description: "Create beautiful moving gradients on Framer, Figma and React",
    tags: [TAGS.color],
    url: "https://shadergradient.co/",
  },
  {
    title: "Super Color Palette",
    category: CATEGORIES.colors,
    description:
      "Generate super awesome color palettes by shifting hue, saturation, lightness, and more. 100% free without ads.",
    favicon: "https://supercolorpalette.com/favicon.svg",
    ogImage: "https://i.imgur.com/XeZmcBP.png",
    subtitle: "100% Free Color Palette Generator",
    tags: [TAGS.color],
    url: "https://supercolorpalette.com/",
  },
  {
    title: "The good colors",
    author: "Fran Pérez",
    category: CATEGORIES.colors,
    description:
      "Generate perceptually uniform color palettes with OKLCH, ensuring consistent lightness and chroma. Supports wide gamut displays, checks contrast ratios using APAC, and is optimized for color blindness.",
    favicon:
      "data:image/svg+xml;utf8,%3Csvg%20width%3D%2216%22%20height%3D%2216%22%20viewBox%3D%220%200%2016%2016%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%3Crect%0A%20%20%20%20%20%20%20%20%20%20x%3D%221%22%0A%20%20%20%20%20%20%20%20%20%20y%3D%221%22%0A%20%20%20%20%20%20%20%20%20%20width%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20height%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20rx%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20fill%3D%22%23ffb0cc%22%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%3Crect%0A%20%20%20%20%20%20%20%20%20%20x%3D%226%22%0A%20%20%20%20%20%20%20%20%20%20y%3D%221%22%0A%20%20%20%20%20%20%20%20%20%20width%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20height%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20rx%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20fill%3D%22%23ffb4b3%22%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%3Crect%0A%20%20%20%20%20%20%20%20%20%20x%3D%2211%22%0A%20%20%20%20%20%20%20%20%20%20y%3D%221%22%0A%20%20%20%20%20%20%20%20%20%20width%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20height%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20rx%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20fill%3D%22%23ffba80%22%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%3Crect%0A%20%20%20%20%20%20%20%20%20%20x%3D%221%22%0A%20%20%20%20%20%20%20%20%20%20y%3D%226%22%0A%20%20%20%20%20%20%20%20%20%20width%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20height%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20rx%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20fill%3D%22%23eace58%22%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%3Crect%0A%20%20%20%20%20%20%20%20%20%20x%3D%226%22%0A%20%20%20%20%20%20%20%20%20%20y%3D%226%22%0A%20%20%20%20%20%20%20%20%20%20width%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20height%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20rx%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20fill%3D%22%23ade27f%22%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%3Crect%0A%20%20%20%20%20%20%20%20%20%20x%3D%2211%22%0A%20%20%20%20%20%20%20%20%20%20y%3D%226%22%0A%20%20%20%20%20%20%20%20%20%20width%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20height%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20rx%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20fill%3D%22%2356edc5%22%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%3Crect%0A%20%20%20%20%20%20%20%20%20%20x%3D%221%22%0A%20%20%20%20%20%20%20%20%20%20y%3D%2211%22%0A%20%20%20%20%20%20%20%20%20%20width%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20height%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20rx%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20fill%3D%22%2334e7ff%22%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%3Crect%0A%20%20%20%20%20%20%20%20%20%20x%3D%226%22%0A%20%20%20%20%20%20%20%20%20%20y%3D%2211%22%0A%20%20%20%20%20%20%20%20%20%20width%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20height%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20rx%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20fill%3D%22%23a7d2ff%22%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%3Crect%0A%20%20%20%20%20%20%20%20%20%20x%3D%2211%22%0A%20%20%20%20%20%20%20%20%20%20y%3D%2211%22%0A%20%20%20%20%20%20%20%20%20%20width%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20height%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20rx%3D%224%22%0A%20%20%20%20%20%20%20%20%20%20fill%3D%22%23d5c1ff%22%0A%20%20%20%20%20%20%20%20%2F%3E%0A%20%20%20%20%20%20%0A%20%20%20%20%3C%2Fsvg%3E",
    ogImage: "https://thegoodcolors.com/og-poster.png",
    tags: [TAGS.color],
    url: "https://thegoodcolors.com/",
  },
  {
    title: "The Palette Studio",
    author: "Pixel Symphony",
    category: CATEGORIES.colors,
    favicon: "https://meditationsincolor.com/apple-touch-icon.png",
    subtitle: "Meditations in Color",
    tags: [TAGS.color],
    url: "https://meditationsincolor.com/palette-studio",
  },
  {
    title: "Two Color Combinations",
    author: "Csaba Kissi",
    category: CATEGORIES.colors,
    description: "Hand-picked two color combinations with copy-ready HEX values.",
    favicon: "https://2colors.colorion.co/favicon.svg",
    ogImage: "https://2colors.colorion.co/og-image.png",
    tags: [TAGS.color],
    url: "https://2colors.colorion.co/",
  },
  {
    title: "UI Colors",
    category: CATEGORIES.colors,
    description:
      "Create and customize beautiful Tailwind CSS color palettes. Generate, edit, and export colors for your design with our intuitive color generator tool.",
    subtitle: "Tailwind CSS Colors - All colors + Custom color generator",
    tags: [TAGS.color],
    url: "https://uicolors.app/",
  },
  {
    title: "WebGradients",
    category: CATEGORIES.colors,
    description:
      "Browse 180 free CSS gradients for backgrounds, UI, websites, and design systems. Copy CSS code, explore color palettes, and find gradient inspiration fast.",
    tags: [TAGS.color],
    url: "https://webgradients.com/",
  },
  {
    title: "Wheel",
    author: "Hayk An",
    category: CATEGORIES.colors,
    description: "Color wheel generator",
    favicon: "https://hihayk.github.io/wheel/favicon.ico",
    ogImage: "https://raw.githubusercontent.com/hihayk/wheel/master/docs/shot.png",
    tags: [TAGS.color],
    url: "https://hihayk.github.io/wheel",
  },
];
