import { Resource } from "@/types";

import { CATEGORIES } from "./categories";
import { TAGS } from "./tags";

export const dataLinks: Resource<typeof CATEGORIES.data>[] = [
  {
    title: "actuallyEXPLAIN",
    category: CATEGORIES.data,
    description:
      "A visualizer that helps you understand complex PostgreSQL queries in a diagram and dictionarized form. Paste your code and check.",
    favicon: "https://actuallyexplain.vercel.app/ae-logo.svg",
    gitHubLink: "https://github.com/freenandes/actuallyexplain",
    ogImage: "https://actuallyexplain.vercel.app/preview.png",
    subtitle: "Visual SQL Logic Mapper",
    url: "https://actuallyexplain.vercel.app/",
  },
  {
    title: "Apify",
    author: "Apify",
    category: CATEGORIES.data,
    description:
      "Thousands of tools to automate your business. Get real-time web data, track competitors, generate leads, and integrate your apps and AI agents.",
    favicon: "https://apify.com/icon0.svg",
    ogImage: "https://apify.com/og-image?title=Thousands+of+tools%0Afor+your+AI",
    subtitle: "The largest marketplace of trusted tools for AI",
    tags: [TAGS.data],
    url: "https://apify.com/",
  },
  {
    title: "APILayer",
    category: CATEGORIES.data,
    description:
      "APILayer is a unified API marketplace with 40+ production-ready APIs for finance, geolocation, weather, data, and AI. Trusted by 2.2M+ developers.",
    favicon: "https://apilayer.com/wp-content/themes/hello-theme-child/assets/favicon.ico",
    gitHubLink: "https://github.com/public-apis/public-apis",
    ogImage: "https://apilayer.com/wp-content/uploads/2026/03/logo.png",
    subtitle: "40+ Production-Ready APIs, One Account, One Key",
    tags: [TAGS.data],
    url: "https://apilayer.com/",
  },
  {
    title: "Automated Web Performance Insights",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "Track web speed & website quality over time. Monitor website performance automatically. Get Lighthouse-powered speed insights & quality metrics in real-time. Track Core Web Vitals, SEO scores & more.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    ogImage: "https://microlink.io/images/og/insights.png",
    url: "https://microlink.io/insights",
  },
  {
    title: "Awesome Public Datasets",
    author: "AwesomeData",
    category: CATEGORIES.data,
    description: "A topic-centric list of HQ open datasets.",
    favicon: "/github.svg",
    ogImage:
      "https://opengraph.githubassets.com/2a61ea1664906fccb0fa2862cc615c2f83984f50a103821992f695485c350967/awesomedata/awesome-public-datasets",
    tags: [TAGS.data],
    url: "https://github.com/awesomedata/awesome-public-datasets",
  },
  {
    title: "Azure Naming Convention Generator",
    author: "Jasper Bernaers",
    category: CATEGORIES.data,
    description:
      "Free Azure naming convention generator following the Microsoft Cloud Adoption Framework. 200+ resource types with official CAF abbreviations, real per-resource length and character rules, 47 regions, org and project segments, batch validation, and export to Terraform, Bicep, ARM, PowerShell, Azure CLI, Markdown, CSV and Azure Policy. 100% client-side.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/azurenamingconvention/og-image.png",
    subtitle: "CAF Abbreviations, Rules & Policy",
    url: "https://jasperbernaers.com/azurenamingconvention/",
  },
  {
    title: "Behind the Email",
    category: CATEGORIES.data,
    description:
      "Instantly find career history, education, and public profile signals from any email address. Professional OSINT for lead research and verification.",
    favicon: "https://behindtheemail.com/icon.svg",
    ogImage: "https://behindtheemail.com/opengraph-image",
    subtitle: "Public Profile & Career Search",
    tags: [TAGS.data],
    url: "https://behindtheemail.com/",
  },
  {
    title: "browserless",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description: "The headless Chrome/Chromium performance driver for Node.js",
    favicon: "https://browserless.js.org/static/logo.png",
    gitHubLink: "https://github.com/microlinkhq/browserless",
    ogImage: "https://browserless.js.org/static/banner.jpg",
    url: "https://browserless.js.org/",
  },
  {
    title: "ByteByteGo",
    category: CATEGORIES.data,
    description: "Everything you need to take your system design skill to the next level",
    favicon: "https://bytebytego.com/apple-touch-icon.png",
    ogImage: "https://bytebytego.com/social2.png",
    subtitle: "Technical Interview Prep",
    url: "https://bytebytego.com/",
  },
  {
    title: "Embed API for Any URL",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "Embed API for any URL — get a ready-to-paste iframe and oEmbed payload in one HTTPS call. 300+ providers including YouTube, Spotify, Twitter, TikTok, Figma. Free tier, optional React / Vue / Vanilla JS SDK.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    ogImage: "https://microlink.io/images/og/embed.png",
    subtitle: "oEmbed for 300+ Providers",
    url: "https://microlink.io/embed",
  },
  {
    title: "Env File Editor",
    author: "Jasper Bernaers",
    category: CATEGORIES.data,
    description:
      "Free online .env file editor: syntax highlighting, 30 lint rules, a secret audit covering 40+ token formats (AWS, GitHub, Stripe, OpenAI), environment diff and export to 16 formats including Docker Compose, Kubernetes, GitHub Actions and env.d.ts. 100% client-side — your secrets never leave the browser.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/env-editor/og-image.png",
    subtitle: "Free Online .env Editor, Linter & Secret Auditor",
    url: "https://jasperbernaers.com/env-editor/",
  },
  {
    title: "File Conversion API",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "Convert PDFs, Word documents, spreadsheets and slide decks into HTML, Markdown or clean text with one API call. No local toolchain. 25 free requests/day.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    ogImage: "https://microlink.io/images/og/file-conversion.png",
    subtitle: "Files to Markdown & Text",
    url: "https://microlink.io/file-conversion",
  },
  {
    title: "Free Fake Data Generator",
    author: "Jasper Bernaers",
    category: CATEGORIES.data,
    description:
      "Free online fake data generator. Build a schema from 123 field types, pick a locale, and generate up to 50,000 rows of realistic test data with valid Luhn cards, mod-97 IBANs and check-digit barcodes. Export CSV, Excel CSV, TSV, JSON, NDJSON, SQL, YAML, XML, Markdown or HTML. Seeded and reproducible, 100% in your browser.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/fake-data/og-image.png",
    subtitle: "123 Field Types, CSV, JSON, SQL, NDJSON & XML | Mockaroo Alternative",
    url: "https://jasperbernaers.com/fake-data/",
  },
  {
    title: "Free Online Tools for Developers",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "A curated collection of free developer tools by Microlink. Screenshot generators, metadata debuggers, and more. No login required.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    ogImage: "https://microlink.io/images/og/tools.png",
    url: "https://microlink.io/tools",
  },
  {
    title: "Free Public APIs",
    category: CATEGORIES.data,
    description:
      "A collection of Free Public APIs for Students and Developers. Tested every single day.",
    favicon: "https://www.freepublicapis.com/favicon.ico",
    tags: [TAGS.data],
    url: "https://www.freepublicapis.com/",
  },
  {
    title: "Google Search API (SERP) for AI Agents",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "Scrape Google Search results in ~1s. A reliable Google SERP API delivering normalized JSON for RAG pipelines, LLM tools, and developer workflows.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    ogImage: "https://microlink.io/images/og/search.png",
    url: "https://microlink.io/search",
  },
  {
    title: "Hoppscotch",
    category: CATEGORIES.data,
    description: "Helps you create requests faster, saving precious time on development.",
    favicon: "https://hoppscotch.io/icon.png",
    ogImage: "https://hoppscotch.io/banner.png",
    subtitle: "Open source API development ecosystem",
    tags: [TAGS.tool],
    url: "https://hoppscotch.io/",
  },
  {
    title: "HTML to PDF API",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "Convert HTML or any URL to PDF with a single REST API call. Features custom margins, headless control, and edge caching. 25 free requests/day.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    ogImage: "https://microlink.io/images/og/pdf.png",
    subtitle: "Convert URL to PDF Document",
    url: "https://microlink.io/pdf",
  },
  {
    title: "JSON For You",
    category: CATEGORIES.data,
    description:
      "Online JSON view, format, minify, validate and compare. It also provides graph view to preview JSON data, semantic comparing two JSON diffs, convert JSON to CSV or CSV to JSON and support jq online.",
    favicon: "https://json4u.com/icon.svg",
    gitHubLink: "https://github.com/loggerhead/json4u",
    ogImage: "https://json4u.com/example/graph.webp",
    subtitle: "The best online JSON tool",
    url: "https://json4u.com/",
  },
  {
    title: "JSON Hero",
    author: "Trigger.dev",
    category: CATEGORIES.data,
    description:
      "JSON Hero makes reading and understand JSON files easy by giving you a clean and beautiful UI packed with extra features.",
    favicon: "https://jsonhero.io/favicon.ico",
    gitHubLink: "https://github.com/triggerdotdev/jsonhero-web",
    ogImage: "https://jsonhero.io/build/_assets/opengraph-P6EWTI3J.png",
    subtitle: "A beautiful JSON viewer for the web",
    tags: [TAGS.tool],
    url: "https://jsonhero.io/",
  },
  {
    title: "Jsonify",
    category: CATEGORIES.data,
    description:
      "Transform XLSX/CSV translation files into structured JSON. Simplify multilingual website and app localization. Convert excel/csv language data to JSON objects effortlessly.",
    favicon: "https://www.jsonify.net/images/seo-logo.svg",
    ogImage: "https://jsonify.net/_next/static/media/og-image.834f1293.webp",
    subtitle: "Free JSON generator",
    tags: [TAGS.tool],
    url: "https://www.jsonify.net/",
  },
  {
    title: "Link Preview API",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "Link preview API that turns any URL into a custom preview card. Normalized metadata (Open Graph, Twitter Cards, JSON-LD, oEmbed) in one JSON call. Free tier, proxy rotation for URLs behind Cloudflare and CAPTCHAs. Built for developers.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    ogImage: "https://microlink.io/images/og/link-preview.png",
    subtitle: "URL Unfurling & Open Graph Metadata",
    tags: [TAGS.data],
    url: "https://microlink.io/link-preview",
  },
  {
    title: "Lorem Ipsum Alternative",
    author: "Jasper Bernaers",
    category: CATEGORIES.data,
    description:
      "Free developer placeholder text generator — a Lorem Ipsum alternative with 24 themes (git commits, terminal logs, API responses, legal copy, UI microcopy). Export to Markdown, HTML, JSX, JSON, CSV, YAML, XML or SQL, with seeded, reproducible output. No signup.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/lore-gen/og-image.png",
    subtitle: "Free Developer Placeholder Text Generator",
    url: "https://jasperbernaers.com/lore-gen/",
  },
  {
    title: "MCP Servers",
    category: CATEGORIES.data,
    description:
      "Official and community Model Context Protocol server implementations for AI tool integrations.",
    favicon:
      "https://modelcontextprotocol.io/mintlify-assets/_mintlify/favicons/mcp/ebiVJzri-bsiCfVZ/_generated/favicon/android-chrome-192x192.png",
    gitHubLink: "https://github.com/modelcontextprotocol/servers",
    ogImage:
      "https://raw.githubusercontent.com/modelcontextprotocol/docs/2eb6171ddbfeefde349dc3b8d5e2b87414c26250/images/og-image.png",
    tags: [TAGS.data],
    url: "https://modelcontextprotocol.io/",
  },
  {
    title: "Media Extraction API",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "Extract direct video and audio file URLs from any web page, with dimensions, duration and type. Real browser detection, proxy support, edge caching. 25 free requests/day.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    ogImage: "https://microlink.io/images/og/media.png",
    subtitle: "Video & Audio File URLs",
    url: "https://microlink.io/media",
  },
  {
    title: "Microlink",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "A single API for turning any URL into data. Built for apps, agents, and AI. Powered by real browsers. Try it, no signup.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    gitHubLink: "https://github.com/microlinkhq",
    ogImage: "https://microlink.io/images/og/home.png",
    subtitle: "The web, transformed",
    tags: [TAGS.data],
    url: "https://microlink.io/",
  },
  {
    title: "Product Hunt",
    category: CATEGORIES.data,
    description:
      "Product Hunt is a curation of the best new products, every day. Discover the latest mobile apps, websites, and technology products that everyone's talking about.",
    favicon: "https://ph-static.imgix.net/ph-favicon-brand-500.ico",
    ogImage: "https://ph-static.imgix.net/ph-logo-1.png",
    subtitle: "The best new products in tech.",
    tags: [TAGS.data],
    url: "https://www.producthunt.com/",
  },
  {
    title: "PublicAPIs.dev",
    author: "Marcel Cruz",
    category: CATEGORIES.data,
    description:
      "A collection of public APIs for developers, categorized and crowdsourced. Animals, books, cryptocurrencies, development, music, weather and much more.",
    favicon: "https://publicapis.dev/favicon-pa/safari-pinned-tab.svg",
    gitHubLink: "https://github.com/marcelscruz/public-apis",
    ogImage: "https://publicapis.dev/og",
    subtitle: "A Collaborative List Of 1400+ Public APIs For Developers",
    tags: [TAGS.data],
    url: "https://publicapis.dev/",
  },
  {
    title: "Rendered HTML API",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "Get the fully rendered HTML of any URL after JavaScript executes. Real browser rendering, CSS selector scoping, proxy support and edge caching. 25 free requests/day.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    ogImage: "https://microlink.io/images/og/html.png",
    subtitle: "HTML After JavaScript",
    url: "https://microlink.io/html",
  },
  {
    title: "unavatar.io",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "Universal avatars API: resolve user avatars by username, email, or domain from GitHub, Gravatar, X, Google, Instagram, and 74+ providers. The same endpoint also returns logos, favicons, app store icons, and cover art — with dashboard analytics for usage, provider mix, and billing.",
    favicon: "https://unavatar.io/favicon.svg",
    gitHubLink: "https://github.com/microlinkhq/unavatar",
    ogImage: "https://unavatar.io/api/og",
    subtitle:
      "The universal avatars API for username, email, and domain — plus logos, icons & artwork",
    url: "https://unavatar.io/",
  },
  {
    title: "URL to Markdown API",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "Convert any web page to clean markdown. Built for AI agents, RAG pipelines, and LLM ingestion reducing token usage by 80%. No login required.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    ogImage: "https://microlink.io/images/og/markdown.png",
    subtitle: "Free, no login required",
    url: "https://microlink.io/markdown",
  },
  {
    title: "URL to Text API",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "Extract clean, readable plain text from any URL. Boilerplate removed, JavaScript rendered, documents supported. Built for LLM pipelines. 25 free requests/day.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    ogImage: "https://microlink.io/images/og/text.png",
    subtitle: "Clean, LLM-Ready Page Content",
    url: "https://microlink.io/text",
  },
  {
    title: "Website Logo API",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "Get the logo behind any URL — page markup, DNS BIMI records and favicons, plus brand palettes with WCAG-aware color pairs. 25 free requests/day.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    ogImage: "https://microlink.io/images/og/logo.png",
    subtitle: "Logos, Favicons & Brand Colors",
    url: "https://microlink.io/logo",
  },
  {
    title: "Website Metadata API",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "Website metadata API - 25 req/day free - that turns any URL to metadata: Open Graph, JSON-LD, Twitter Cards, link preview & URL preview in one JSON call.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    ogImage: "https://microlink.io/images/og/metadata.png",
    subtitle: "URL to Metadata & Link Preview",
    url: "https://microlink.io/metadata",
  },
  {
    title: "Website Screenshot API",
    author: "Microlink HQ",
    category: CATEGORIES.data,
    description:
      "Capture pixel-perfect website screenshots with one API call. Free to start. Sub-second responses, full headless browser control, device emulation & ad-blocking.",
    favicon: "https://cdn.microlink.io/logo/favicon.svg",
    ogImage: "https://microlink.io/images/og/screenshot.png",
    subtitle: "Convert URL to Image",
    url: "https://microlink.io/screenshot",
  },
];
