import { Resource } from "@/types";

import { CATEGORIES } from "./categories";
import { TAGS } from "./tags";

export const documentationLinks: Resource<typeof CATEGORIES.docs>[] = [
  {
    title: "Accept: text/markdown",
    author: "Ben Word",
    category: CATEGORIES.docs,
    description:
      "Serve Markdown to AI agents and LLMs via the Accept: text/markdown header. Browsers get HTML, agents get clean Markdown.",
    favicon: "https://acceptmarkdown.com/favicon.svg",
    ogImage: "https://acceptmarkdown.com/open-graph/home.png",
    subtitle: "Serve Markdown to AI Agents with Accept Headers",
    tags: [TAGS.markdown, TAGS.tool],
    url: "https://acceptmarkdown.com/",
  },
  {
    title: "Alexandrie",
    author: "Alexandrie Team",
    category: CATEGORIES.docs,
    description:
      "Alexandrie is a fast, self-hostable Markdown workspace for notes, knowledge bases, collaboration, and public documentation.",
    favicon: "https://alexandrie-hub.fr/Logo/Alexandrie-logo-light-crop.png",
    gitHubLink: "https://github.com/Smaug6739/Alexandrie",
    ogImage: "https://alexandrie-hub.fr/screenshots/mock/0.png",
    url: "https://alexandrie-hub.fr/",
  },
  {
    title: "ANSItype",
    author: "Ben Word",
    category: CATEGORIES.docs,
    description: "Generate ANSI/ASCII text with TheDraw fonts",
    favicon: "https://ansitype.com/favicon.png",
    ogImage: "https://ansitype.com/og-image.png",
    subtitle: "FIGlet Alternative with TDF Fonts",
    url: "https://ansitype.com/",
  },
  {
    title: "Anypost",
    author: "Anypost",
    category: CATEGORIES.docs,
    description:
      "Send transactional and broadcast email from one modern API — 8 SDKs, Markdown sends, tags, tracking, and webhooks. As low as 8¢ per 1,000.",
    favicon: "https://anypost.com/favicon.svg",
    gitHubLink: "https://github.com/anypost",
    ogImage: "https://anypost.com/brand/og.png",
    subtitle: "Transactional and broadcast email service",
    tags: [TAGS.email, TAGS.markdown],
    url: "https://anypost.com/",
  },
  {
    title: "Anytype",
    category: CATEGORIES.docs,
    description:
      "Create notes, tasks, databases, and chats that only you can access. Your data stays on your device — fully owned, secure, and private. Free to start.",
    favicon: "https://anytype.io/apple-touch-icon.png",
    ogImage: "https://anytype.io/ogimage.jpg",
    subtitle: "A safe haven for digital collaboration",
    url: "https://anytype.io/",
  },
  {
    title: "DevDocs API Documentation",
    author: "freeCodeCamp",
    category: CATEGORIES.docs,
    description:
      "Fast, offline, and free documentation browser for developers. Search 100+ docs in one web app: HTML, CSS, JavaScript, PHP, Ruby, Python, Go, C, C++…",
    favicon: "https://devdocs.io/images/apple-icon-160.png",
    gitHubLink: "https://github.com/freeCodeCamp/devdocs",
    tags: [TAGS["open-source"]],
    url: "https://devdocs.io/",
  },
  {
    title: "Devhints",
    author: "Rico Sta. Cruz",
    category: CATEGORIES.docs,
    description: "A ridiculous collection of web development cheatsheets",
    favicon: "https://devhints.io/assets/favicon.png",
    gitHubLink: "https://github.com/rstacruz/cheatsheets",
    ogImage: "https://assets.devhints.io/previews/index.jpg",
    subtitle: "TL;DR for developer documentation",
    tags: [TAGS.development, TAGS.education],
    url: "https://devhints.io/",
  },
  {
    title: "docmd",
    category: CATEGORIES.docs,
    description:
      "Open-source documentation compiler. One Markdown source, one command — generates website, search, AI context, agent protocols, and knowledge formats together.",
    favicon:
      "https://raw.githubusercontent.com/docmd-io/docmd/main/packages/ui/assets/images/docmd-logo.png",
    gitHubLink: "https://github.com/docmd-io/docmd",
    ogImage: "https://docmd.io/assets/images/preview.webp",
    subtitle: "Documentation for Humans and Machines",
    url: "https://docmd.io/",
  },
  {
    title: "docsify",
    category: CATEGORIES.docs,
    description: "A magical documentation generator.",
    favicon: "https://docsify.js.org/_media/icon.svg",
    url: "https://docsify.js.org/#/",
  },
  {
    title: "emailmd",
    author: "Anypost",
    category: CATEGORIES.docs,
    description:
      "Turn markdown into responsive, email-safe HTML that renders perfectly across every client.",
    favicon: "https://www.emailmd.dev/favicon.ico",
    gitHubLink: "https://github.com/anypost/emailmd",
    subtitle: "Responsive Emails, Written in Markdown",
    tags: [TAGS.email, TAGS.markdown],
    url: "https://www.emailmd.dev/",
  },
  {
    title: "Free Email Signature Generator",
    author: "Jasper Bernaers",
    category: CATEGORIES.docs,
    description:
      "Free email signature generator. Create a professional HTML email signature with your logo, social links and contact details, then copy the code into Outlook, Gmail or Apple Mail. Live preview, no signup, no watermark, 100% free and private.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/email-signature/og-image.png",
    subtitle: "HTML Signatures for Outlook, Gmail & Apple Mail",
    tags: [TAGS.email],
    url: "https://jasperbernaers.com/email-signature/",
  },
  {
    title: "Free Invoice Generator Online",
    author: "Jasper Bernaers",
    category: CATEGORIES.docs,
    description:
      "Free online invoice generator — create professional invoices in seconds. Add line items, tax, discounts, your logo. Export print-ready PDF instantly. No sign-up, no watermark, no ads. 100% browser-based and private. Best free alternative to Wave, Zoho Invoice, and FreshBooks.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/invoice-generator/og-image.png",
    subtitle: "Create & Download PDF Invoices | No Sign-Up, No Watermark",
    tags: [TAGS.invoice],
    url: "https://jasperbernaers.com/invoice-generator/",
  },
  {
    title: "Free PDF Tools Online",
    author: "Jasper Bernaers",
    category: CATEGORIES.docs,
    description:
      "Free online PDF tools — merge PDF files into one, split PDF by pages, compress PDF size by 80%, convert PDF to JPG images, convert JPG to PDF, rotate and organize pages. 100% browser-based with no file upload to any server. No watermarks, no daily limits, no registration. Best free alternative to SmallPDF, iLovePDF, PDF24, Sejda and Adobe Acrobat online. Works on Windows, Mac, Linux, iPhone and Android.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/pdf/og-image.png",
    subtitle: "Merge, Split, Compress, Convert PDF to JPG | No Upload, No Watermark, No Sign‑Up",
    tags: [TAGS.pdf, TAGS.tool],
    url: "https://jasperbernaers.com/pdf/",
  },
  {
    title: "Free PDF Translator",
    author: "Jasper Bernaers",
    category: CATEGORIES.docs,
    description:
      "Free browser-based PDF translator. Extract text from any PDF and translate it to 100+ languages instantly. No upload, no server, 100% private. Powered by MyMemory.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/pdf-translator/og-image.png",
    subtitle: "Translate PDFs to Any Language",
    tags: [TAGS.pdf],
    url: "https://jasperbernaers.com/pdf-translator/",
  },
  {
    title: "Fumadocs",
    category: CATEGORIES.docs,
    description: "The React.js documentation framework.",
    favicon: "https://www.fumadocs.dev/icon.png",
    ogImage: "https://www.fumadocs.dev/banner.png",
    tags: [TAGS.react],
    url: "https://www.fumadocs.dev/",
  },
  {
    title: "GitDocify",
    category: CATEGORIES.docs,
    description:
      "Turn any GitHub repository into structured, source-grounded documentation with GitDocify.",
    favicon: "https://gitdocify.com/brand/logo-mark-primary.png",
    ogImage: "https://gitdocify.com/brand/social-preview.png",
    subtitle: "Instant, Professional Code Documentation",
    tags: [TAGS.development],
    url: "https://gitdocify.com/",
  },
  {
    title: "iLovePDF",
    category: CATEGORIES.docs,
    description:
      "iLovePDF is an online service to work with PDF files completely free and easy to use. Merge PDF, split PDF, compress PDF, office to PDF, PDF to JPG and more!",
    favicon: "https://www.ilovepdf.com/img/app-icon.png",
    ogImage: "https://www.ilovepdf.com/img/ilovepdf/social/en-US/ilovepdf.png",
    subtitle: "Online PDF tools for PDF lovers",
    tags: [TAGS.pdf, TAGS.tool],
    url: "https://www.ilovepdf.com/",
  },
  {
    title: "Invoice Builder",
    author: "piratuks",
    category: CATEGORIES.docs,
    description:
      "Invoice and quotation builder desktop app with PDF export, designed for small businesses and freelancers. Create, manage, and export invoices and quotes easily using a local database in an Electron-based app.",
    favicon: "/github.svg",
    ogImage:
      "https://opengraph.githubassets.com/f50c07ae3a04dedde35800ded790b1ed85d154e313f6e136a5cc3c7e256c5d65/piratuks/invoice-builder",
    tags: [TAGS.invoice],
    url: "https://github.com/piratuks/invoice-builder",
  },
  {
    title: "Invoicely",
    category: CATEGORIES.docs,
    description:
      "Invoicely is a simple and easy to use invoice generator where you can create beautiful and professional invoices in minutes. ~ Proudly OSS - Backed by Cloudflare OSS",
    favicon: "https://invoicely.gg/official/invoicely-logo.png",
    ogImage: "https://invoicely.gg/official/og-banner.png",
    subtitle: "Create Beautiful & Professional Invoices",
    tags: [TAGS.invoice, TAGS.selfHosted],
    url: "https://invoicely.gg/",
  },
  {
    title: "Markdown Editor Online",
    author: "Jasper Bernaers",
    category: CATEGORIES.docs,
    description:
      "Free online Markdown editor with instant live preview — GitHub-style preview, document outline, resizable panes, README & blog templates, visual table generator, Mermaid diagrams, math, share links, export to HTML/MD/PDF. Auto-saves in your browser. No sign-up, no upload.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/markdown-live-editor/og-image.png",
    subtitle: "Live Preview, GitHub Style, Templates & HTML/PDF Export",
    tags: [TAGS.markdown],
    url: "https://jasperbernaers.com/markdown-live-editor/",
  },
  {
    title: "Material for MkDocs",
    author: "Martin Donath",
    category: CATEGORIES.docs,
    description:
      "Write your documentation in Markdown and create a professional static site in minutes – searchable, customizable, in 60+ languages, for all devices",
    favicon: "https://squidfunk.github.io/mkdocs-material/assets/favicon.png",
    gitHubLink: "https://github.com/squidfunk/mkdocs-material",
    ogImage: "https://squidfunk.github.io/mkdocs-material/assets/images/social/index.png",
    tags: [TAGS.markdown, TAGS.tool],
    url: "https://squidfunk.github.io/mkdocs-material/",
  },
  {
    title: "Matter.",
    author: "Hayk An",
    category: CATEGORIES.docs,
    description: "A task manager that highlights what matters most to you",
    favicon: "https://hihayk.github.io/matter/favicon.ico",
    ogImage: "https://raw.githubusercontent.com/hihayk/matter/master/docs/shot.png",
    url: "https://hihayk.github.io/matter/",
  },
  {
    title: "Mintlify",
    category: CATEGORIES.docs,
    description: "Self-updating documentation for startups, enterprises, and agents.",
    favicon: "https://raw.githubusercontent.com/mintlify/starter/main/favicon.svg",
    ogImage: "https://www.mintlify.com/_next/static/media/og.28576e75.png",
    subtitle: "The Knowledge Platform Built for Agents",
    tags: [TAGS.tool],
    url: "https://www.mintlify.com/",
  },
  {
    title: "Online Notepad",
    author: "Jasper Bernaers",
    category: CATEGORIES.docs,
    description:
      "A free online notepad that opens instantly — just start typing. Autosaves in your browser, no login, no install, works offline. Line numbers, tabs, syntax highlighting and a local AI writing assist (summarize, fix grammar, rewrite tone) that runs 100% on your device, so it doubles as a Notepad++ alternative on any device.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/notepad/og-image.png",
    subtitle: "Free, Autosave, No Sign-Up | Notepad++ Alternative",
    tags: [TAGS.editor, TAGS.tool],
    url: "https://jasperbernaers.com/notepad/",
  },
  {
    title: "OverAPI.com",
    category: CATEGORIES.docs,
    description: "OverAPI.com is a site collecting all the cheatsheets,all!",
    favicon: "https://overapi.com/static/images/overapi-logo.png",
    ogImage:
      "https://lh3.googleusercontent.com/YsthzC-Dw5og9snWVX5mfD9cvURgRmxwMAgcvnrtxdAn-v2nIx8-DxzIZMT0xrTQdoURcQWBING4t6tW5VM4s5nl7w=s1280-w1280-h800",
    subtitle: "Collecting all the cheat sheets",
    tags: [TAGS.cheatsheet, TAGS.development],
    url: "https://overapi.com/",
  },
  {
    title: "Paperless-ngx",
    author: "The Paperless-ngx team",
    category: CATEGORIES.docs,
    description: "Documentation for the Paperless-ngx document management system software.",
    favicon:
      "https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/dev/docs/assets/logo_leaf.svg",
    ogImage:
      "https://opengraph.githubassets.com/e41f9417cd92968ecb63476d01b5e01def7f1a1b63698286415859dd4cd2770f/paperless-ngx/paperless-ngx",
    url: "https://docs.paperless-ngx.com/",
  },
  {
    title: "PDFCraft",
    author: "PDFCraft Team",
    category: CATEGORIES.docs,
    description:
      "Free, Private & Browser-Based. Merge, edit, and edit PDF files online without uploading to servers.",
    favicon: "https://pdfcraft.devtoolcafe.com/favicon.svg",
    gitHubLink: "https://github.com/PDFCraftTool/pdfcraft",
    ogImage: "https://pdfcraft.devtoolcafe.com/images/og-image.png",
    subtitle: "Professional PDF Tools",
    tags: [TAGS.pdf],
    url: "https://pdfcraft.devtoolcafe.com/en/",
  },
  {
    title: "PDF Form Filler",
    author: "Jasper Bernaers",
    category: CATEGORIES.docs,
    description:
      "Fill in any PDF in your browser — add text, checkmarks, dates and hand-drawn signatures. No upload, 100% private, instant PDF export. Free, no signup.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/pdf-form-filler/og-image.png",
    subtitle: "Fill, Sign & Export PDFs Free",
    tags: [TAGS.pdf],
    url: "https://jasperbernaers.com/pdf-form-filler/",
  },
  {
    title: "Quarkdown",
    author: "Giorgio Garofalo",
    category: CATEGORIES.docs,
    description:
      "Quarkdown is a modern, open-source, Markdown-based typesetting system for creating papers, presentations, knowledge bases and static websites.",
    favicon: "https://quarkdown.com/favicon.svg",
    gitHubLink: "https://github.com/iamgio/quarkdown",
    ogImage: "https://quarkdown.com/og-image.jpg",
    subtitle: "Markdown with superpowers",
    tags: [TAGS.development],
    url: "https://quarkdown.com/",
  },
  {
    title: "readme.so",
    category: CATEGORIES.docs,
    description:
      "Use readme.so's markdown editor and templates to easily create a ReadMe for your projects",
    favicon: "https://readme.so/readme.svg",
    ogImage: "https://readme.so/screenshot.png",
    url: "https://readme.so/",
  },
  {
    title: "Signature PDF",
    category: CATEGORIES.docs,
    description:
      "Signature PDF is free online software for signing (individually or collaboratively), organizing, or compressing PDF files.",
    favicon: "https://pdf.24eme.fr/favicon.svg",
    gitHubLink: "https://github.com/24eme/signaturepdf",
    ogImage: "https://pdf.24eme.fr/logo.svg",
    subtitle: "Sign and manipulate PDFs freely",
    tags: [TAGS.pdf],
    url: "https://pdf.24eme.fr/",
  },
  {
    title: "Slidev",
    author: "Anthony Fu",
    category: CATEGORIES.docs,
    description: "Presentation slides for developers",
    favicon: "https://sli.dev/logo.svg",
    ogImage: "https://sli.dev/og-image.png",
    tags: [TAGS.presentation],
    url: "https://sli.dev/",
  },
  {
    title: "Stirling",
    category: CATEGORIES.docs,
    description:
      "GitHub's #1 PDF application with 30M+ downloads. The next generation of the PDF Editor - private, open-source, and built to scale.",
    favicon:
      "https://raw.githubusercontent.com/Stirling-Tools/Stirling-PDF/main/frontend/editor/src/core/assets/brand/branding-logo/logo-mark.svg",
    gitHubLink: "https://github.com/Stirling-Tools/Stirling-PDF",
    ogImage:
      "https://raw.githubusercontent.com/Stirling-Tools/Stirling-PDF/main/frontend/editor/src/core/assets/brand/modern-logo/Firstpage.png",
    subtitle: "PDF Processor",
    tags: [TAGS.pdf, TAGS.tool],
    url: "https://www.stirling.com/",
  },
  {
    title: "Text Cleaner",
    author: "Jasper Bernaers",
    category: CATEGORIES.docs,
    description:
      "Free online text cleaner. Remove extra spaces, line breaks, smart quotes and Word/PDF formatting, strip HTML, remove accents, find & replace, sort, dedup and more — live, in your browser.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/text-cleaner/og-image.png",
    subtitle: "Remove Extra Spaces, Line Breaks & Formatting Online",
    url: "https://jasperbernaers.com/text-cleaner/",
  },
];
