import { Tool } from "@/types";

import { CATEGORIES } from "./categories";
import { TAGS } from "./tags";

export const frontendLinks: Tool[] = [
  {
    title: "404 Animation Library",
    author: "Csaba Kissi",
    category: CATEGORIES.frontend,
    description:
      "A library of ready-to-copy 404 page animations built with pure CSS. Click any animation to grab its code — no JavaScript, no dependencies, MIT licensed.",
    favicon: "https://404.colorion.co/favicon.svg",
    ogImage: "https://404.colorion.co/og-image.png",
    subtitle: "Free CSS 404 page animations to copy",
    tags: [TAGS.animation, TAGS.css, TAGS["ui-component"]],
    url: "https://404.colorion.co/",
  },
  {
    title: "Animejs",
    category: CATEGORIES.frontend,
    description: "A fast, multipurpose and lightweight JavaScript animation library",
    tags: [TAGS.animation],
    url: "https://animejs.com/",
  },
  {
    title: "Animista",
    category: CATEGORIES.frontend,
    description:
      "Animista is a CSS animation library and a place where you can play with a collection of ready-made CSS animations and download only those you will use.",
    tags: [TAGS.animation],
    url: "https://animista.net/",
  },
  {
    title: "Animmaster Lib",
    category: CATEGORIES.frontend,
    description:
      "Animmaster Lib — a modern frontend library of 300 PRO-level animated UI components with live video previews. Scroll animations, WebGL shaders, hero sections, sliders, menus and more — copy, paste, ship.",
    tags: [TAGS.animation],
    url: "https://animmasterlib.dev/",
  },
  {
    title: "Apache ECharts",
    category: CATEGORIES.frontend,
    description: "A powerful, interactive charting and visualization library for browser",
    tags: [TAGS["data-viz"]],
    url: "https://echarts.apache.org/en/index.html",
  },
  {
    title: "Atropos",
    category: CATEGORIES.frontend,
    description:
      "Atropos is a lightweight, free and open-source JavaScript library to create stunning touch-friendly 3D parallax hover effects.",
    tags: [TAGS.animation],
    url: "https://atroposjs.com/",
  },
  {
    title: "AutoAnimate",
    category: CATEGORIES.frontend,
    description:
      "A zero-config, drop-in animation utility that automatically adds smooth transitions to your web app. Use it with React, Solid, Vue, Svelte, or any other JavaScript application.",
    subtitle: "Add motion to your apps with a single line of code",
    tags: [TAGS.animation],
    url: "https://auto-animate.formkit.com/",
  },
  {
    title: "Background Snippets Generator",
    author: "naymur rahman",
    category: CATEGORIES.frontend,
    description:
      "Generate beautiful CSS background patterns, gradients, textures, and snippets for your website. Perfect for modern web design and UI backgrounds.",
    ogImage: "https://tools.ui-layouts.com/bgsnippets.jpg",
    url: "https://tools.ui-layouts.com/background-snippets",
  },
  {
    title: "Blendy",
    category: CATEGORIES.frontend,
    description:
      "Blendy, a framework-agnostic tool that smoothly transitions one element into another with just a few lines of code.",
    favicon: "https://blendy.tahazsh.com/favicon.svg",
    ogImage: "https://blendy.tahazsh.com/banner.png",
    subtitle: "Smoothly transition elements",
    tags: [TAGS.animation],
    url: "https://blendy.tahazsh.com/",
  },
  {
    title: "Border Beam",
    author: "Jakub Antalik",
    category: CATEGORIES.frontend,
    className: "bg-foreground border-paper",
    description:
      "A lightweight React component that renders an animated glowing border beam effect. Supports multiple sizes, color variants, and themes.",
    favicon: "https://beam.jakubantalik.com/favicon.svg",
    ogImage: "https://beam.jakubantalik.com/og-v2.jpg",
    subtitle: "Animated border beam component for React",
    tags: [TAGS.animation],
    url: "https://beam.jakubantalik.com/",
  },
  {
    title: "Brik",
    category: CATEGORIES.frontend,
    description:
      "Build your tailor-made stack of AI-powered design tools for animations, 2D & 3D visuals, text effects, and images. Remix, share, export, and scale.",
    tags: [TAGS.animation],
    url: "https://brik.space/",
  },
  {
    title: "CodePen",
    category: CATEGORIES.frontend,
    description: "Build, share, and learn JavaScript, CSS, and HTML with our online code editor.",
    subtitle: "Online Code Editor and Front End Web Developer Community",
    url: "https://codepen.io/",
  },
  {
    title: "CSS-Tricks",
    category: CATEGORIES.frontend,
    description: "A Website About Making Websites",
    url: "https://css-tricks.com/",
  },
  {
    title: "CSS Diner",
    author: "Luke Pacholski",
    category: CATEGORIES.frontend,
    description: "A fun game to help you learn and practice CSS selectors.",
    favicon: "https://flukeout.github.io/favicon.png",
    ogImage: "https://flukeout.github.io/images/fb-share.jpg",
    subtitle: "Where we feast on CSS Selectors!",
    tags: [TAGS.css],
    url: "https://flukeout.github.io/",
  },
  {
    title: "CSS Loaders",
    author: "Temani Afif",
    category: CATEGORIES.frontend,
    description:
      "The biggest collection of CSS-only loaders. More than 600 loading animations made by Temani Afif using a single element.",
    subtitle: "A collection of more than 600 loading animations",
    tags: [TAGS.animation],
    url: "https://css-loaders.com/",
  },
  {
    title: "CSS Loaders",
    category: CATEGORIES.frontend,
    className: "bg-foreground border-paper",
    description:
      "CSS Loader is a collection of different types of loaders, spinners and their source code. There are no image dependencies in this. It's is done using pure CSS. Hence it is easily customization too.",
    tags: [TAGS.animation],
    url: "https://cssloaders.github.io/",
  },
  {
    title: "CSS Polka Dot Generator",
    author: "Brian Louis Ramirez",
    category: CATEGORIES.frontend,
    description:
      "Generate polka dot patterns using CSS custom variables for background images. No JS required.",
    favicon: "https://screenspan.net/favicon.svg",
    ogImage: "https://screenspan.net/img/polka-hero.jpg",
    tags: [TAGS.patterns],
    url: "https://screenspan.net/polka/",
  },
  {
    title: "DASCA",
    category: CATEGORIES.frontend,
    description:
      "Desktop visual effects software for video, images and 3D. Pixel sorting, dithering, blob tracking and more with real‑time previews and a smooth workflow.",
    subtitle: "Real-Time Visual Effects for Image/Video/3D",
    tags: [TAGS.animation],
    url: "https://dasca.studio/",
  },
  {
    title: "driver.js",
    category: CATEGORIES.frontend,
    description:
      "A light-weight, no-dependency, vanilla JavaScript library to drive user's focus across the page.",
    tags: [TAGS.animation],
    url: "https://driverjs.com/",
  },
  {
    title: "EaseMaster",
    author: "Satish Kumar",
    category: CATEGORIES.frontend,
    description:
      "Design motion that feels real. The ultimate easing visualization tool for generating Cubic Bezier curves and Spring physics for CSS, Tailwind, Framer Motion, and GSAP.",
    favicon: "https://easemaster.satisui.xyz/icon0.svg",
    ogImage: "https://easemaster.satisui.xyz/og-image.png",
    subtitle: "CSS & Spring Easing Generator",
    tags: [TAGS.animation],
    url: "https://easemaster.satisui.xyz/",
  },
  {
    title: "Easing Graphs",
    category: CATEGORIES.frontend,
    className: "bg-foreground border-paper",
    description: "A curated collection of easing graphs",
    favicon: "https://www.easing.dev/logo.svg",
    ogImage: "https://easing.dev/opengraph-image.png?f63f59cbea8235ed",
    tags: [TAGS.animation],
    url: "https://www.easing.dev/",
  },
  {
    title: "Easing Wizard",
    category: CATEGORIES.frontend,
    description:
      "Generate and customize CSS easing functions with ease and magical precision using Easing Wizard 🧙",
    subtitle: "CSS Easing Editor and Generator",
    tags: [TAGS.animation],
    url: "https://easingwizard.com/",
  },
  {
    title: "Epic Easing",
    category: CATEGORIES.frontend,
    description:
      "Quickly and easily generate easing curves for ease, spring, and bounce animations. Utilize animation presets or create your own custom animation curve, spring, or bounce. Instantly export to CSS, SCSS, Objective-C, and Swift.",
    ogImage: "https://epiceasing.com/epiceasing_preview.png",
    url: "https://epiceasing.com/",
  },
  {
    title: "Flexbox Labs",
    category: CATEGORIES.frontend,
    description: "A visual tool for experimenting with flexbox and CSS grid layouts.",
    favicon: "https://raw.githubusercontent.com/prazzon/Flexbox-Labs/master/public/img/logo.svg",
    ogImage:
      "https://raw.githubusercontent.com/prazzon/Flexbox-Labs/master/.github/images/Screenshot1.png",
    tags: [TAGS.tool],
    url: "https://flexboxlabs.netlify.app/",
  },
  {
    title: "Flicker",
    category: CATEGORIES.frontend,
    description:
      "A loading spinner library inspired by flip-dot displays. Browse the collection, build your own, export to SVG, React, or Flutter.",
    subtitle: "Spinner Library",
    tags: [TAGS.animation],
    url: "https://flicker.laurie.fyi/",
  },
  {
    title: "FlipOff.",
    author: "magnum6actual",
    category: CATEGORIES.frontend,
    description:
      "Free split-flap display emulator for any TV. The classic flip-board look, without the $3,500 hardware.",
    favicon: "/github.svg",
    tags: [TAGS.animation],
    url: "https://github.com/magnum6actual/flipoff",
  },
  {
    title: "Framer University",
    category: CATEGORIES.frontend,
    description:
      "Discover the best free Framer resources for your next project, including Framer components, code overrides, animations, and effects. Elevate your Framer website with a curated selection of top-quality Framer assets.",
    subtitle: "Best Free Framer Resources",
    url: "https://framer.university/resources",
  },
  {
    title: "Frontend Practice",
    category: CATEGORIES.frontend,
    description:
      "Take your frontend skills to the next level by recreating real websites from real companies.",
    favicon: "https://www.frontendpractice.com/images/favicon.ico",
    ogImage: "https://www.frontendpractice.com/FP-meta.png",
    subtitle: "Become a better frontend developer.",
    tags: [TAGS.development, TAGS.education, TAGS.ui],
    url: "https://www.frontendpractice.com/",
  },
  {
    title: "Gingham Maker",
    category: CATEGORIES.frontend,
    description: "A CSS generator for custom gingham patterns",
    url: "https://gingham.laney.tech/",
  },
  {
    title: "Grainrad",
    category: CATEGORIES.frontend,
    description: "Grainrad - Free WebGPU-powered ASCII, dithering, and retro effects at 60fps",
    tags: [TAGS.animation],
    url: "https://grainrad.com/",
  },
  {
    title: "GSAP",
    category: CATEGORIES.frontend,
    description:
      "Supported by Webflow. Animate Anything - A wildly robust JavaScript animation library built for professionals.",
    tags: [TAGS.animation],
    url: "https://gsap.com/",
  },
  {
    title: "Hero Patterns",
    author: "Steve Schoger",
    category: CATEGORIES.frontend,
    description: "Free repeatable SVG background patterns for your web projects",
    tags: [TAGS.image, TAGS.ui],
    url: "https://heropatterns.com/",
  },
  {
    title: "hookcn",
    author: "strlrd-29",
    category: CATEGORIES.frontend,
    description: "A collection of reusable react hooks that you can copy and paste into your apps.",
    favicon:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' class='lucide lucide-anchor size-5' aria-hidden='true'%3E%3Cpath d='M12 22V8'%3E%3C/path%3E%3Cpath d='M5 12H2a10 10 0 0 0 20 0h-3'%3E%3C/path%3E%3Ccircle cx='12' cy='5' r='3'%3E%3C/circle%3E%3C/svg%3E",
    ogImage: "https://hookcn.ouassim.tech/og.png",
    tags: [TAGS.react],
    url: "https://hookcn.ouassim.tech/",
  },
  {
    title: "htmldocs",
    author: "htmldocs team",
    category: CATEGORIES.frontend,
    description:
      "Create and generate professional documents and PDFs using React components. htmldocs offers a simple, powerful API for automated document generation and management.",
    favicon: "https://raw.githubusercontent.com/htmldocs-js/htmldocs/canary/apps/docs/favicon.svg",
    ogImage: "https://htmldocs.com/og-image.png",
    subtitle: "Build and generate documents with React",
    tags: [TAGS.react],
    url: "https://htmldocs.com/",
  },
  {
    title: "Image generation",
    author: "Jakub Antalik",
    category: CATEGORIES.frontend,
    description: "Image generation loader and reveal component.",
    favicon: "https://image.jakubantalik.com/images/favicon.png",
    ogImage: "https://image.jakubantalik.com/images/og-image.jpg",
    tags: [TAGS.animation],
    url: "https://image.jakubantalik.com/",
  },
  {
    title: "Impeccable",
    category: CATEGORIES.frontend,
    description:
      "1 skill, 23 commands, and curated anti-patterns for impeccable frontend design. Works with Cursor, Claude Code, GitHub Copilot, Gemini CLI, and Codex CLI.",
    subtitle: "The missing upgrade to Anthropic's impeccable skill",
    url: "https://impeccable.style/",
  },
  {
    title: "Jitter",
    category: CATEGORIES.frontend,
    description:
      "Jitter is a collaborative motion design tool that lets you create professional animations in minutes, no matter your experience with motion.",
    subtitle: "A fast and simple motion design tool on the web",
    tags: [TAGS.animation],
    url: "https://jitter.video/",
  },
  {
    title: "Kinetics",
    author: "Csaba Kissi",
    category: CATEGORIES.frontend,
    description:
      "A library of spring-driven micro-interactions for web apps. Copy the CSS or React, tune the physics, ship the motion.",
    favicon: "https://kinetics.colorion.co/favicon.svg",
    ogImage: "https://kinetics.colorion.co/og-image.png",
    subtitle: "Spring-physics motion for web interfaces",
    tags: [TAGS.animation, TAGS.css, TAGS["ui-component"]],
    url: "https://kinetics.colorion.co/",
  },
  {
    title: "LottieFiles",
    category: CATEGORIES.frontend,
    description:
      "Effortlessly bring the smallest, free, ready-to-use motion graphics for the web, app, social, and designs. Create, edit, test, collaborate, and ship Lottie animations in no time!",
    tags: [TAGS.animation],
    url: "https://lottiefiles.com/",
  },
  {
    title: "Lottielab",
    category: CATEGORIES.frontend,
    description:
      "Create and ship animations to your products faster. Bring your websites and apps to life with the simplest editor for Lottie animations.",
    subtitle: "Create & edit Lottie animations",
    tags: [TAGS.animation],
    url: "https://www.lottielab.com/",
  },
  {
    title: "mapcn",
    category: CATEGORIES.frontend,
    description:
      "A collection of beautifully designed, accessible, and customizable map components. Built on MapLibre GL. Styled with Tailwind CSS. Works with shadcn/ui.",
    tags: [TAGS.map],
    url: "https://www.mapcn.dev/",
  },
  {
    title: "Matter.js",
    author: "liabru",
    category: CATEGORIES.frontend,
    description: "Matter.js is 2D rigid body JavaScript physics engine for the web",
    url: "https://brm.io/matter-js/",
  },
  {
    title: "Mesh-Gradient Generator",
    author: "naymur rahman",
    category: CATEGORIES.frontend,
    description:
      "Create beautiful mesh gradients and fluid color transitions for your web designs. Perfect for modern UI and backgrounds.",
    ogImage: "https://tools.ui-layouts.com/meshgradients.jpg",
    url: "https://tools.ui-layouts.com/mesh-gradients",
  },
  {
    title: "MiroMiro",
    category: CATEGORIES.frontend,
    description:
      "The design-to-code tool that turns any website into clean HTML, Tailwind, and design tokens in one click. Paste real code straight into Cursor, Claude,...",
    subtitle: "Website to Code: Copy Real HTML & Tailwind",
    url: "https://miromiro.app/",
  },
  {
    title: "Motion",
    category: CATEGORIES.frontend,
    description:
      "Motion (prev Framer Motion) is a fast, production-grade animation library for React, JavaScript and Vue. Build smooth UI animations at a tiny footprint.",
    subtitle: "JavaScript & React animation library",
    tags: [TAGS.animation],
    url: "https://motion.dev/",
  },
  {
    title: "Odyc.js",
    category: CATEGORIES.frontend,
    description:
      "Odyc.js is a simple JavaScript library to create interactive narrative games, even without coding experience.",
    ogImage: "https://odyc.dev/og.png",
    url: "https://odyc.dev/",
  },
  {
    title: "Open Props",
    category: CATEGORIES.frontend,
    description:
      "Open source CSS custom properties to help accelerate adaptive and consistent design. Available from a CDN or NPM, as CSS or Javascript.",
    subtitle: "sub-atomic styles",
    tags: [TAGS["ui-component"]],
    url: "https://open-props.style/",
  },
  {
    title: "OpenTUI",
    category: CATEGORIES.frontend,
    description:
      "OpenTUI is a TypeScript library on a native Zig core for building terminal user interfaces (TUIs)",
    subtitle: "Terminal UIs",
    url: "https://opentui.com/",
  },
  {
    title: "Patterns",
    author: "Ali Imam",
    category: CATEGORIES.frontend,
    favicon: "https://www.aliimam.in/apple-touch-icon.png",
    ogImage: "https://www.aliimam.in/opengraph-image.jpg",
    tags: [TAGS.patterns],
    url: "https://old.aliimam.in/patterns",
  },
  {
    title: "PDFSlick",
    author: "Vancho Stojkov",
    category: CATEGORIES.frontend,
    description: "View and Interact with PDFs in React, SolidJS, Svelte and JavaScript apps.",
    tags: [TAGS.development, TAGS.react],
    url: "https://pdfslick.dev/",
  },
  {
    title: "PDFx",
    category: CATEGORIES.frontend,
    description:
      "Copy-paste React PDF components like shadcn/ui. Run `npx pdfx-cli add table` and own the code. 24 components, theme system, CLI, invoice & report blocks. MIT licensed.",
    subtitle: "shadcn/ui for React PDFs | Copy-Paste PDF Components",
    tags: [TAGS.development, TAGS.pdf],
    url: "https://pdfx.akashpise.dev/",
  },
  {
    title: "pen.dev",
    category: CATEGORIES.frontend,
    description:
      "pen.dev fundamentally increases your engineering speed by bringing designing directly into your preferred IDE.",
    favicon: "https://www.pen.dev/favicon.svg",
    ogImage: "https://pen.dev/og-image-v4.png",
    subtitle: "Design on canvas. Land in code.",
    url: "https://www.pen.dev/",
  },
  {
    title: "Pretext",
    category: CATEGORIES.frontend,
    description:
      "Pretext is a pure TypeScript text layout library by ex-React core member Cheng Lou. It bypasses browser layout reflow and measures text 300-600x faster than DOM methods.",
    subtitle: "JavaScript Text Measurement Without DOM Reflow",
    url: "https://pretextjs.net/",
  },
  {
    title: "React Doctor",
    category: CATEGORIES.frontend,
    description:
      "Let coding agents diagnose and fix React codebases with deterministic static analysis.",
    url: "https://www.react.doctor/",
  },
  {
    title: "React Grab",
    category: CATEGORIES.frontend,
    description: "Copy any UI element for your coding agent.",
    favicon: "https://react-grab.com/logo.svg",
    ogImage: "https://react-grab.com/api/og",
    tags: [TAGS["ai-agent"]],
    url: "https://www.react-grab.com/",
  },
  {
    title: "React Haiku",
    category: CATEGORIES.frontend,
    description: "A minimal React Hooks library that saves you time and lines of code.",
    tags: [TAGS.react],
    url: "https://www.reacthaiku.dev/",
  },
  {
    title: "React Three Fiber",
    category: CATEGORIES.frontend,
    description: "React-three-fiber is a React renderer for three.js.",
    tags: [TAGS.react],
    url: "https://r3f.docs.pmnd.rs/getting-started/introduction",
  },
  {
    title: "React Zero-UI",
    category: CATEGORIES.frontend,
    description:
      "React Zero-UI is a CSS-powered React state manager for UI state with zero React re-renders, no providers, and generated Tailwind variants.",
    favicon:
      "https://raw.githubusercontent.com/react-zero-ui/core/main/examples/demo/public/assets/zero-ui-favicon-transparent.png",
    ogImage: "https://zero-ui.dev/assets/zero-ui-logo.png",
    subtitle: "React UI State Management Without Re-renders",
    tags: [TAGS.react],
    url: "https://zero-ui.dev/",
  },
  {
    title: "Refero Styles",
    category: CATEGORIES.frontend,
    description:
      "Search a curated DESIGN.md library for AI agents: colors, typography, spacing, and component patterns from top websites. Part of Refero.",
    url: "https://styles.refero.design/",
  },
  {
    title: "Rive",
    category: CATEGORIES.frontend,
    description:
      "Behind Spotify Wrapped, Duolingo, and products reaching 2 billion users. Design, animate, and code in one place. Ship everywhere.",
    subtitle: "The interactive experience engine",
    tags: [TAGS.animation],
    url: "https://rive.app/",
  },
  {
    title: "Screen Sizes",
    category: CATEGORIES.frontend,
    description: "A complete guide for Apple Displays, Icon Sizes, and more!",
    favicon: "https://screensizes.app/favicon.svg",
    ogImage: "https://www.screensizes.app/ogimage.png",
    url: "https://screensizes.app/",
  },
  {
    title: "Scroll Mask",
    author: "Tim Wilson",
    category: CATEGORIES.frontend,
    className: "bg-foreground border-paper",
    description:
      "A tiny Tailwind @utility for scroll-driven gradient masks at the edges of overflow containers.",
    favicon: "https://twilson.net/favicon.ico",
    ogImage: "https://twilson.net/scroll-mask/opengraph-image.jpg",
    subtitle: "Scroll Mask Tailwind CSS Utilities",
    tags: [TAGS["ui-component"]],
    url: "https://twilson.net/scroll-mask",
  },
  {
    title: "shadcnmaps",
    category: CATEGORIES.frontend,
    description:
      "170+ interactive SVG map components for React. Countries, continents, and US states. No dependencies — install via shadcn CLI with pure Tailwind CSS styling.",
    tags: [TAGS.map],
    url: "https://www.shadcnmaps.com/",
  },
  {
    title: "ShadCN Themer",
    author: "Mike Tromba",
    category: CATEGORIES.frontend,
    description:
      "Discover and create beautiful themes for shadcn/ui. Browse thousands of community-made themes, customize colors with OKLCH picker, select Google Fonts, adjust border radius, and export themes instantly for your Next.js projects.",
    favicon: "https://shadcnthemer.com/favicon.ico",
    ogImage: "https://shadcnthemer.com/og-image.png",
    subtitle: "ShadCN Themes - Create Beautiful Themes for shadcn/ui",
    tags: [TAGS["ui-component"]],
    url: "https://shadcnthemer.com/",
  },
  {
    title: "Shaders",
    category: CATEGORIES.frontend,
    description:
      "Component library for creative WebGPU effects in modern frontend frameworks. Compose interactive visuals for Vue, React, Svelte, Solid & JS.",
    tags: [TAGS.animation],
    url: "https://shaders.com/",
  },
  {
    title: "Shadows Generator",
    author: "naymur rahman",
    category: CATEGORIES.frontend,
    description:
      "Generate beautiful CSS and Tailwind CSS v3/v4 box-shadows and text-shadows. Perfect for modern UI, glassmorphism, and soft design systems.",
    ogImage: "https://tools.ui-layouts.com/shadows.jpg",
    url: "https://tools.ui-layouts.com/shadows",
  },
  {
    title: "Smooothy",
    category: CATEGORIES.frontend,
    description: "Smooth configurable extendable slider made for animation.",
    tags: [TAGS.animation],
    url: "https://smooothy.vercel.app/",
  },
  {
    title: "soundcn",
    author: "soundcn",
    category: CATEGORIES.frontend,
    description:
      "700+ curated UI sound effects for modern web apps. Browse, preview, and install sounds with a single command. Free and open source.",
    favicon: "https://www.soundcn.xyz/icon.svg?icon.025y~su-z2aj3.svg",
    ogImage: "https://www.soundcn.xyz/og-dark.png",
    subtitle: "Free Sound Effects for Modern Web Apps",
    tags: [TAGS["ui-component"]],
    url: "https://www.soundcn.xyz/",
  },
  {
    title: "Soundz",
    author: "Kaycee Ingram",
    category: CATEGORIES.frontend,
    description: "A Lightweight, Customizable Sound Effects Wrapper for React.",
    favicon: "https://soundzjs.vercel.app/s-icon.svg",
    ogImage: "https://soundzjs.vercel.app/soundz.svg",
    tags: [TAGS["ui-component"]],
    url: "https://soundzjs.vercel.app/",
  },
  {
    title: "Spline",
    category: CATEGORIES.frontend,
    description:
      "Spline is a free 3D design software with real-time collaboration to create web interactive experiences in the browser. Easy 3d modeling, animation, textures, and more.",
    subtitle: "3D Design tool in the browser with real-time collaboration",
    tags: [TAGS.animation],
    url: "https://spline.design/",
  },
  {
    title: "SSGOI",
    author: "MeurSyphus",
    category: CATEGORIES.frontend,
    description:
      "Router-agnostic page transitions for React, Svelte, Vue, Solid, Angular, and Qwik. Built on the Web Animations API with spring physics and state preservation.",
    favicon: "https://ssgoi.dev/ssgoi-logo.png",
    ogImage: "https://ssgoi.dev/og.png",
    subtitle: "Native page transitions on the web",
    tags: [TAGS.animation],
    url: "https://ssgoi.dev/",
  },
  {
    title: "StyleSeed",
    author: "bitjaru",
    category: CATEGORIES.frontend,
    description:
      "Open-source AI design-method engine for Claude Code, Codex, and Cursor — directed concepts, semantic palettes, verified working interactions, privacy-minimized local learning with explicit limits, and revision-safe updates.",
    favicon: "https://styleseed-demo.vercel.app/favicon.ico",
    ogImage: "https://styleseed-demo.vercel.app/og/styleseed-og.png",
    subtitle: "Design engine for vibe coding",
    tags: [TAGS.ai, TAGS.development, TAGS.ui],
    url: "https://styleseed-demo.vercel.app/",
  },
  {
    title: "SVGator",
    category: CATEGORIES.frontend,
    description:
      "Create impressive SVG animations and more. Add them easily to your website or app. Get started for free!",
    subtitle: "Free Animation Maker Online",
    tags: [TAGS.animation],
    url: "https://www.svgator.com/",
  },
  {
    title: "SVG Spinners",
    category: CATEGORIES.frontend,
    description:
      "Collection of 100+ Open Source SVG-based icons you can use to show content is being loaded. Absolutely free with no attribution required.",
    favicon: "https://magecdn.com/assets/icons/favicon.png",
    ogImage: "https://i.magecdn.com/d2b508/ee0b63_og_image_3?f=png",
    subtitle: "Open Source SVG Loading Icons",
    tags: [TAGS.animation, TAGS.svg, TAGS["ui-component"]],
    url: "https://magecdn.com/tools/svg-loaders",
  },
  {
    title: "SVG Studio",
    category: CATEGORIES.frontend,
    description:
      "SVG Studio — a free, browser-based SVG animation editor. No sign-up, no telemetry, no subscription.",
    subtitle: "Animate Everything",
    tags: [TAGS.animation],
    url: "https://www.svgstudio.org/",
  },
  {
    title: "Swishy",
    category: CATEGORIES.frontend,
    description:
      "Swishy is the leading AI motion designer and AI animator platform. Create professional motion graphics, animated typefaces, and stunning video animations without After Effects. Export to MP4, MOV, and GIF instantly.",
    tags: [TAGS.animation],
    url: "https://www.swishy.ai/",
  },
  {
    title: "Tailwind CSS Animations Plugin",
    author: "Miguel Ángel Durán (midudev)",
    category: CATEGORIES.frontend,
    description:
      "Add 79+ ready-to-use CSS animations to Tailwind CSS with utility classes. Fade, slide, zoom, scroll-driven motion, and dialog effects. Zero config, open source by midudev.",
    favicon: "https://tailwind-animations.com/favicon.svg",
    ogImage: "https://tailwind-animations.com/og.jpg",
    subtitle: "79+ Utility Classes",
    tags: [TAGS.animation],
    url: "https://tailwindcss-animations.vercel.app",
  },
  {
    title: "ThemeCN",
    category: CATEGORIES.frontend,
    description:
      "Customize theme for shadcn/ui with tweakcn's interactive editor. Supports Tailwind CSS v4, Shadcn UI, and custom styles. Modify properties, preview changes, and get the code in real time.",
    tags: [TAGS["ui-component"]],
    url: "https://tweakcn.com/",
  },
  {
    title: "Tinte",
    author: "Railly Hugo",
    category: CATEGORIES.frontend,
    description:
      "Agent-native design system infrastructure for shadcn/ui. 13 semantic OKLCH tokens compile to presets, VS Code themes, terminal configs, and 19+ formats. Install with one command via shadcn CLI v4. 500+ presets, AI generation, agent skill included.",
    favicon: "https://www.tinte.dev/icons/favicon-192x192.png",
    subtitle: "Agent-Native Design System Infrastructure",
    tags: [TAGS["ui-component"]],
    url: "https://www.tinte.dev/",
  },
  {
    title: "tldraw SDK",
    category: CATEGORIES.frontend,
    description:
      "The tldraw SDK provides tools, services, and APIs to build beautiful whiteboards and infinite canvas applications with real-time collaboration and a powerful React-based canvas.",
    subtitle: "Infinite Canvas SDK for React",
    url: "https://tldraw.dev/",
  },
  {
    title: "Torph",
    category: CATEGORIES.frontend,
    description: "Dependency-free animated text component.",
    subtitle: "Dependency-Free Text Morphing",
    tags: [TAGS.animation, TAGS.typography],
    url: "https://torph.lochie.me/",
  },
  {
    title: "Transitions.dev",
    author: "Jakub Antalik",
    category: CATEGORIES.frontend,
    description:
      "Collection of the most essential transitions for web apps that you can just copy and paste into any project.",
    favicon: "https://transitions.dev/assets/favicon-light-mode.png",
    ogImage: "https://transitions.dev/assets/og-main.jpg",
    subtitle: "Essential transitions for web apps",
    tags: [TAGS.animation],
    url: "https://transitions.dev/",
  },
  {
    title: "Tutorials",
    author: "Codrops",
    category: CATEGORIES.frontend,
    description:
      "In this section, you will find a variety of in-depth articles written by skilled front-end developers that cover a range of web development and web design techniques.",
    favicon: "https://tympanus.net/codrops/wp-content/themes/codropstheme03/favicons/favicon.svg",
    tags: [TAGS.tutorial],
    url: "https://tympanus.net/codrops/category/tutorials/",
  },
  {
    title: "UI Ball",
    category: CATEGORIES.frontend,
    description: "Useful things for web developers.",
    subtitle: "Useful things for devs",
    url: "https://uiball.com/",
  },
  {
    title: "UI SFX",
    author: "Yuki Capital",
    category: CATEGORIES.frontend,
    description:
      "Preview 936 open-source UI sound effects for web, mobile, SaaS, and games. Compare 12 sonic styles, one-shots, and seamless loops.",
    favicon: "https://uisfx.com/favicon.svg",
    ogImage: "https://uisfx.com/og-ui-sound-effects-v4.jpg",
    subtitle: "UI Sound Design: 936 Interface Sound Effects",
    tags: [TAGS.audio],
    url: "https://uisfx.com/",
  },
  {
    title: "Ultracite",
    category: CATEGORIES.frontend,
    description:
      "Ultracite is a zero-config preset for ESLint, Biome, and Oxlint that helps teams and AI write consistent, type-safe code.",
    subtitle: "Zero-Config Linting for Biome, ESLint, and Oxlint",
    url: "https://www.ultracite.ai/",
  },
  {
    title: "Utility Hub",
    category: CATEGORIES.frontend,
    description: "30 useful web apps, one place. Everything you need, one link.",
    subtitle: "30 tools in one place",
    url: "https://utility-hub-navy-six.vercel.app/",
  },
  {
    title: "UV Canvas",
    category: CATEGORIES.frontend,
    description: "An open source React.js component library for beautifully shaded canvas.",
    favicon: "https://uvcanvas.com/favicon-32x32.png",
    tags: [TAGS.react],
    url: "https://uvcanvas.com/",
  },
  {
    title: "VisGL Google Maps",
    category: CATEGORIES.frontend,
    description: "React components and hooks for the Google Maps JavaScript API",
    favicon: "https://visgl.github.io/react-google-maps/images/visgl-logo-dark.png",
    tags: [TAGS.map],
    url: "https://visgl.github.io/react-google-maps/",
  },
  {
    title: "Web Interface Guidelines",
    category: CATEGORIES.frontend,
    description: "A non-exhaustive list of details that make a good web interface.",
    favicon: "https://interfaces.rauno.me/favicon.svg",
    ogImage: "https://interfaces.rauno.me/og.png",
    tags: [TAGS.education],
    url: "https://interfaces.rauno.me",
  },
];
