import { Tool } from "@/types";

import { CATEGORIES } from "./categories";
import { TAGS } from "./tags";

export const iconLinks: Tool[] = [
  {
    title: "Absurd Design",
    category: CATEGORIES.icons,
    description:
      "Download free illustrations – beautiful hand-drawn artwork for any creative project. Enhance websites, books, and more with high-quality visuals.",
    favicon: "https://absurd.design/img/favicon/apple-touch-icon-152x152.png",
    ogImage: "https://absurd.design/img/social.jpg",
    subtitle: "Free Hand-Drawn Illustrations for Download – Unleash Your Imagination",
    tags: [TAGS.illustration],
    url: "https://absurd.design/intro",
  },
  {
    title: "AnimateIcons",
    author: "Avijit Dey",
    category: CATEGORIES.icons,
    description:
      "Free, open-source animated SVG icons for React. Drop-in components built on motion/react with hover and imperative triggers, configurable size, color, and duration - installable via the shadcn CLI.",
    favicon: "https://animateicons.in/logo.svg",
    ogImage: "https://animateicons.in/og.png",
    subtitle: "Free Animated React Icon Library",
    tags: [TAGS.icons],
    url: "https://animateicons.in/",
  },
  {
    title: "Atlas Icons",
    category: CATEGORIES.icons,
    description:
      "Free open-source icon library by GetIllustrations. 7,980 hand-crafted icons across 41 packs in three stroke weights. Webfont, React, Vue, Flutter, React Native, Figma plugin. MIT licensed.",
    favicon: "https://iconsatlas.com/assets/img/favicon.svg",
    ogImage:
      "https://www.figma.com/community/thumbnail?resource_id=1182746451598399442&resource_type=plugin",
    subtitle: "7,980 free open-source icons in 41 packs · MIT licensed",
    tags: [TAGS.icons],
    url: "https://iconsatlas.com/",
  },
  {
    title: "Avatune",
    category: CATEGORIES.icons,
    description:
      "A typed, SSR-first avatar primitive for the web — seven frameworks, eleven themes, zero dependencies. Compose by hand or let the predictor draft from a photo.",
    subtitle: "Avatars that feel like people",
    url: "https://www.avatune.dev/",
  },
  {
    title: "Basicons",
    category: CATEGORIES.icons,
    description:
      "A set of free, open-source icons for your next project. Customise and download individual svg icons or the entire collection.",
    favicon: "https://www.basicons.com/favicon.ico",
    ogImage: "https://www.basicons.com/opengraph-image.png",
    subtitle: "Basic icons for product design & development",
    tags: [TAGS.icons],
    url: "https://www.basicons.com/",
  },
  {
    title: "Boxicons",
    author: "Boxicons",
    category: CATEGORIES.icons,
    description:
      "Access 50,000+ Pro icon variations and 3,500+ free icons. High-quality SVG icons for React, Vue, Figma & more. Download in SVG, PNG, JSX formats. Perfect for web & mobile apps.",
    favicon: "https://cdn.boxicons.com/logo.svg",
    ogImage: "https://boxicons.com/opengraph-image.png",
    subtitle: "High Quality Web Icons",
    tags: [TAGS.icons],
    url: "https://boxicons.com/",
  },
  {
    title: "Boxy SVG Editor",
    category: CATEGORIES.icons,
    description: "Create and edit Scalable Vector Graphics (SVG) files online",
    favicon: "https://boxy-svg.com/icons/favicon.svg",
    tags: [TAGS.svg],
    url: "https://boxy-svg.com/",
  },
  {
    title: "Buttery.so",
    author: "Rachel How",
    category: CATEGORIES.icons,
    className: "bg-foreground border-paper",
    description: "Buttery smooth, minimal icons for interfaces.",
    favicon: "https://www.buttery.so/logo-loaf.svg",
    ogImage: "https://www.buttery.so/opengraph-image.png",
    tags: [TAGS.icons],
    url: "https://www.buttery.so/icons",
  },
  {
    title: "Cascade",
    category: CATEGORIES.icons,
    description:
      "An open-source icon set where every icon represents a CSS property–value pair. Copy as SVG or React component. Built for design tools, inspectors, and documentation.",
    subtitle: "Icons for CSS Properties",
    tags: [TAGS.icons],
    url: "https://designsurface.dev/cascade",
  },
  {
    title: "central icon system",
    category: CATEGORIES.icons,
    description: "Designed to be universal. Built for every context—across any medium.",
    favicon: "https://centralicons.com/logo.png",
    ogImage: "https://centralicons.com/meta.png",
    tags: [TAGS.icons],
    url: "https://centralicons.com/",
  },
  {
    title: "Contour",
    author: "illustrations.run",
    category: CATEGORIES.icons,
    description:
      "Generate custom topographic SVG maps with adjustable contour lines. Free tool for creating scalable vector graphics perfect for design projects, presentations and artwork.",
    ogImage: "https://illustrations.run/contour/images/og-image.png",
    subtitle: "Topography SVG Generator. Contour Lines ready to copy/paste.",
    tags: [TAGS.svg],
    url: "https://illustrations.run/contour/",
  },
  {
    title: "coolicons PRO",
    category: CATEGORIES.icons,
    className: "bg-foreground border-paper",
    description:
      "coolicons is a carefully designed collection of 1,320+ icons with a focus on simplicity and consistency. Perfectly suited for web, application and mobile design.",
    favicon: "https://coolicons.cool/images/favicons/favicon.svg",
    ogImage: "https://coolicons.cool/images/ogi.webp",
    subtitle: "1,320+ Carefully Designed Icons | Duotone, Duocolor, Line Icons",
    tags: [TAGS.icons],
    url: "https://coolicons.cool/",
  },
  {
    title: "Flowbite",
    category: CATEGORIES.icons,
    description:
      "Get started with a collection of 751 free and open-source SVG icons compatible with Flowbite and Tailwind CSS based on solid and outline styles with React (JSX) and Figma support.",
    favicon: "https://flowbite.com/images/logo.svg",
    ogImage: "https://flowbite.com/images/og-image.png",
    subtitle: "Free and open-source SVG Icons",
    tags: [TAGS.icons],
    url: "https://flowbite.com/icons/",
  },
  {
    title: "FREE - 200+ Unique Illustrations",
    author: "GraphicSauce",
    category: CATEGORIES.icons,
    description:
      "This illustration combines cultural characters from various continents and packaged in a modern style, suitable for your startup that wants to stand up among others. Key Features: 100% Vector Library100 pre-made scenes (200+ scenes on our website)Drag and drop scene builder with organized layer...",
    favicon: "https://static.figma.com/app/icon/1/favicon.svg",
    ogImage:
      "https://s3-alpha.figma.com/hub/file/5135664550/9154eac7-d255-41a6-91d3-aa55bbf67c3c-cover.png",
    subtitle: "Figma",
    tags: [TAGS.illustration],
    url: "https://www.figma.com/community/file/1331150412576485660/free-200-unique-illustrations",
  },
  {
    title: "Free Flat Vector Illustration Collection",
    category: CATEGORIES.icons,
    description:
      "A diverse range of flat vector illustrations available in SVG and PNG formats. All free with just two clicks. No registration required!",
    favicon:
      "https://i0.wp.com/graphicsauce.co/free-placeholder-logo/wp-content/uploads/2024/08/graphicsauce-icon.png?fit=117,5126&ssl=1",
    ogImage:
      "https://graphicsauce.co/free-flat-vector-Illustrations/wp-content/uploads/2024/08/Free-Flat-Vector-Illustrations.png",
    tags: [TAGS.illustration, TAGS.svg],
    url: "https://graphicsauce.co/free-flat-vector-Illustrations/",
  },
  {
    title: "Free SVG Converter",
    author: "Kristjan Retter",
    category: CATEGORIES.icons,
    description:
      "Free SVG converter with color palette customization. Works with both Jpg to svg and png to svg. Upload the image and adjust colors using our built-in color picker. Convert to editable SVG format instantly. No signup required",
    favicon: "https://svgconverter.online/favicon.ico",
    ogImage: "https://svgconverter.online/thumbnail.png",
    subtitle: "With Color",
    tags: [TAGS.svg],
    url: "https://svgconverter.online",
  },
  {
    title: "Free SVG Illustrations",
    author: "Lukasz Adam",
    category: CATEGORIES.icons,
    description: "Free SVG Illustrations For Websites (CC0 Licensed)",
    tags: [TAGS.illustration, TAGS.svg],
    url: "https://lukaszadam.com/illustrations",
  },
  {
    title: "Glyphs",
    category: CATEGORIES.icons,
    description:
      "A dynamic design system for creating icon sets in Figma and using them on the web.",
    favicon: "https://glyphs.fyi/favicon.ico",
    ogImage:
      "https://raw.githubusercontent.com/gorango/glyphs/main/docs/static/content/community-dark.jpg",
    subtitle: "The Complete Icon Design System",
    tags: [TAGS.icons],
    url: "https://glyphs.fyi/",
  },
  {
    title: "Haikei",
    category: CATEGORIES.icons,
    description:
      "A web-based design tool to generate unique SVG design assets for websites, social media, blog posts, desktop and mobile wallpapers, posters, and more! Our generators let you discover, customize, randomize, and export generative SVG design assets ready to use with your favorite design tools.",
    ogImage: "https://haikei.app/haikei-cover.png",
    subtitle: "Generate unique SVG design assets",
    tags: [TAGS.svg],
    url: "https://haikei.app/",
  },
  {
    title: "Highlights",
    category: CATEGORIES.icons,
    description:
      "Highlights is an open-source hand-drawn illustration library created by Outdraw Design to help everyone tell their story. The library contains over 100 vector shapes ready to use by all creatives in their work: websites, apps, videos, illustrations, and many more.",
    subtitle: "Hand-Drawn Illustration Library",
    tags: [TAGS.illustration, TAGS.svg],
    url: "https://www.highlights.design/",
  },
  {
    title: "Iconbuddy",
    category: CATEGORIES.icons,
    description:
      "Search and download 300,000+ free SVG icons from open source icon libraries. Customize colors and sizes, then export SVG, PNG, JSX, or Base64.",
    favicon: "https://iconbuddy.com/iconbuddy-logo.png",
    ogImage: "https://iconbuddy.com/og-image.png",
    subtitle: "Free SVG Icons - 300,000+ Open Source Icons",
    tags: [TAGS.icons],
    url: "https://iconbuddy.com/",
  },
  {
    title: "Iconer",
    category: CATEGORIES.icons,
    description:
      "App where you can easily customize icons. Choose from a variety of libraries with different licenses. Edit attributes, copy and export effortlessly.",
    ogImage: "https://iconer.app/image.jpg",
    subtitle: "Free Icons for Everything (SVG, PNG, JSX)",
    tags: [TAGS.icons],
    url: "https://iconer.app/",
  },
  {
    title: "Icônes",
    category: CATEGORIES.icons,
    description: "Icon Explorer with Instant searching, powered by Iconify",
    tags: [TAGS.icons],
    url: "https://icones.js.org/",
  },
  {
    title: "Iconify Design",
    category: CATEGORIES.icons,
    description: "All popular icon sets, one framework",
    tags: [TAGS.icons],
    url: "https://iconify.design/",
  },
  {
    title: "Iconly",
    category: CATEGORIES.icons,
    description:
      "Convert SVG strokes to fills and make your icons webfont compatible. Clean up and reduce the size of your SVG files. Free online SVG compressor & minifier. Extract SVG icons from SVG/TTF/EOT icon font files. SVG font to SVG icons converter.",
    favicon: "https://iconly.io/apple-touch-icon.png",
    ogImage: "https://iconly.io/output/png/open-graph.png",
    subtitle: "Icon Font Generator",
    tags: [TAGS.svg],
    url: "https://iconly.io/",
  },
  {
    title: "Icon Maker by Raycast",
    author: "Raycast",
    category: CATEGORIES.icons,
    description: "Create beautiful icons for your next project, app, or Raycast extension.",
    ogImage: "https://www.ray.so/_next/static/media/og-image.00c8lrgmh62oa.png",
    tags: [TAGS.icons],
    url: "https://ray.so/icon",
  },
  {
    title: "Icons8",
    author: "Icons8",
    category: CATEGORIES.icons,
    description:
      "A flexible icon family for interfaces, diagrams, presentations — whatever, really.",
    subtitle: "Download 1,509,000 free icons (SVG, PNG)",
    tags: [TAGS.icons],
    url: "https://icons8.com/icons",
  },
  {
    title: "Icons",
    author: "Ali Imam",
    category: CATEGORIES.icons,
    favicon: "https://www.aliimam.in/apple-touch-icon.png",
    ogImage: "https://www.aliimam.in/opengraph-image.jpg",
    tags: [TAGS.icons, TAGS.logo, TAGS.vector],
    url: "https://old.aliimam.in/icons",
  },
  {
    title: "Icons",
    author: "Chandu Machineni",
    category: CATEGORIES.icons,
    description:
      "Access 2 million+ free SVG icons from 200+ popular libraries. Search, customize colors, sizes & stroke width. Download instantly or copy code. Perfect for designers & developers.",
    favicon: "https://freesvg.vercel.app/favicon.ico",
    ogImage: "https://freesvg.vercel.app/og-image.jpg",
    subtitle: "Free SVG Icon Library - 2M+ Icons | Search, Customize & Download",
    tags: [TAGS.icons],
    url: "https://freesvg.vercel.app/",
  },
  {
    title: "Iconsax",
    category: CATEGORIES.icons,
    description: "Iconsax is a collection of icons for designers and developers",
    tags: [TAGS.icons],
    url: "https://iconsax.io/",
  },
  {
    title: "Icoon",
    category: CATEGORIES.icons,
    description:
      "Explore 3D icons, illustrations, images, and more AI-generated creative assets. Speed up your design process with ready-made, high-quality assets for your website, app, landing page, or print.",
    favicon: "https://framerusercontent.com/images/0kGFrcvOz1dn6LDsbAi3cfzxSk.webp",
    ogImage: "https://framerusercontent.com/images/8R6ihoS2suE4HJyi8h0sYg06lA.jpg",
    subtitle: "3D Icon library",
    tags: [TAGS.illustration, TAGS["3D"]],
    url: "https://www.icoon.co/",
  },
  {
    title: "illlustrations",
    author: "Vijay Verma",
    category: CATEGORIES.icons,
    description:
      "Large set of opensource illustrations. You can use completely free and without attribution.",
    favicon: "https://illlustrations.co/icons/icon-192x192.png?v=1d0394bf9fc267e40ccc6d562175855a",
    ogImage: "https://illlustrations.co/preview.jpg",
    subtitle: "open source illustrations kit",
    tags: [TAGS.illustration],
    url: "https://illlustrations.co/",
  },
  {
    title: "iOS Icon Gallery",
    category: CATEGORIES.icons,
    description: "Showcasing beautiful icon designs from the iOS App Store.",
    tags: [TAGS.icons],
    url: "https://www.iosicongallery.com/",
  },
  {
    title: "Isocons",
    author: "Isocons",
    category: CATEGORIES.icons,
    description: "Carefully crafted isometric icons.",
    favicon: "https://www.isocons.app/brand/favicon-dark.svg",
    ogImage: "https://isocons.app/og.jpg",
    tags: [TAGS.icons],
    url: "https://www.isocons.app/",
  },
  {
    title: "Its Hover",
    category: CATEGORIES.icons,
    description: "Animated icons that move with intent.",
    tags: [TAGS.animation, TAGS.icons],
    url: "https://www.itshover.com/",
  },
  {
    title: "Lineicons",
    category: CATEGORIES.icons,
    description:
      "Get 27988+ free line icons in SVG, PNG, React, Figma, and more. Available in multiple variations, with free CDN & icon editor for seamless customization!",
    favicon: "https://avatars.githubusercontent.com/u/90905687",
    ogImage: "https://cdn.pimjo.com/lineicons-5.jpg",
    subtitle: "Free Line Icons for Designers and Developers",
    tags: [TAGS.icons],
    url: "https://lineicons.com/",
  },
  {
    title: "LsIcon",
    author: "Wis Design",
    category: CATEGORIES.icons,
    description:
      "Discover 700+ customizable SVG icons for React. LSicon offers open-source, high-quality icons designed on a 16px grid with 1px strokes. Perfect for developers and designers.",
    ogImage: "https://www.lsicon.com/static/website.jpg",
    subtitle: "Open-Source SVG Icons for React Developers and Designers",
    tags: [TAGS.icons],
    url: "https://www.lsicon.com/",
  },
  {
    title: "lucide-animated",
    author: "pqoqubbw",
    category: CATEGORIES.icons,
    description:
      "Free open-source library of 350+ beautifully crafted animated React icons. Built with Motion and Lucide. Copy-paste ready, MIT licensed, fully customizable SVG icons with smooth animations.",
    favicon: "https://lucide-animated.com/icon",
    ogImage: "https://lucide-animated.com/og.png",
    subtitle: "Free Animated React Icons Library",
    tags: [TAGS.animation, TAGS.icons],
    url: "https://lucide-animated.com/",
  },
  {
    title: "Lucide Icons",
    category: CATEGORIES.icons,
    description: "Browse all Lucide icons.",
    favicon: "https://lucide.dev/logo.light.svg",
    ogImage: "https://lucide.dev/og.png",
    tags: [TAGS.icons],
    url: "https://lucide.dev/icons/",
  },
  {
    title: "Mega Doodles Pack",
    author: "MariaLetta",
    category: CATEGORIES.icons,
    description:
      "🔥 Big vector pack with hand-drawn doodles for presentations, social media, blog posts and so on",
    favicon: "/github.svg",
    ogImage: "https://raw.githubusercontent.com/MariaLetta/mega-doodles-pack/master/preview/1.png",
    tags: [TAGS.illustration],
    url: "https://github.com/MariaLetta/mega-doodles-pack",
  },
  {
    title: "Meteocons",
    author: "Bas Milius",
    category: CATEGORIES.icons,
    description: "Animated weather icons for the modern web. 500+ icons in SVG and Lottie.",
    favicon: "https://meteocons.com/favicon.svg",
    ogImage: "https://raw.githubusercontent.com/basmilius/meteocons/main/assets/header.png",
    subtitle: "Animated Weather Icons",
    tags: [TAGS.icons],
    url: "https://meteocons.com/",
  },
  {
    title: "Meteor Icons",
    category: CATEGORIES.icons,
    className: "bg-neutral-500 border-paper",
    description: "Open source icon library for MeteorJS.",
    favicon: "https://meteoricons.com/favicon.svg",
    ogImage: "https://meteoricons.com/images/og-image.png",
    tags: [TAGS.icons],
    url: "https://meteoricons.com/",
  },
  {
    title: "Mossaik",
    category: CATEGORIES.icons,
    description: "Stylish SVG Backgrounds for your websites and designs",
    favicon: "https://mossaik.app/favicon.ico",
    ogImage:
      "https://gabriel.perales.me/_next/image?url=%2Fstatic%2Fimages%2Fmossaik.png&w=1200&q=75",
    tags: [TAGS.svg],
    url: "https://mossaik.app/",
  },
  {
    title: "moving icons",
    category: CATEGORIES.icons,
    description: "beautifully crafted, moving icons. for svelte.",
    favicon: "https://www.movingicons.dev/favicon.png",
    ogImage: "https://movingicons.dev/og.png",
    tags: [TAGS.animation, TAGS.icons, TAGS.svelte],
    url: "https://www.movingicons.dev/",
  },
  {
    title: "Overflow Design",
    category: CATEGORIES.icons,
    description:
      "Free Notion icons for dashboards, docs, and templates. Explore a 591-icon starter set in regular, duotone, and accent color styles.",
    favicon: "https://www.overflow.design/favicon.ico",
    ogImage: "https://www.overflow.design/assets/img/od-preview.jpg",
    subtitle: "Free Notion Icons",
    tags: [TAGS.icons],
    url: "https://www.overflow.design/notion-icons/free/",
  },
  {
    title: "Phosphor Icons",
    category: CATEGORIES.icons,
    description:
      "A flexible icon family for interfaces, diagrams, presentations — whatever, really.",
    tags: [TAGS.icons],
    url: "https://phosphoricons.com/",
  },
  {
    title: "Pixelarticons",
    category: CATEGORIES.icons,
    description:
      "4431 hand-crafted pixel art icons on a 24x24 grid. 4 styles: base, sharp, glyph, solid. 880 free, full set via Pro license. npm install pixelarticons.",
    favicon: "https://pixelarticons.com/favicon.svg",
    ogImage: "https://pixelarticons.com/og-default.jpg",
    subtitle: "4431 Pixel Art Icons | Free & Pro",
    tags: [TAGS.icons],
    url: "https://pixelarticons.com/",
  },
  {
    title: "Radix Icons",
    author: "Radix",
    category: CATEGORIES.icons,
    description: "A crisp set of 15×15 icons designed by the WorkOS team.",
    favicon: "https://www.radix-ui.com/favicon-black.svg",
    ogImage: "https://radix-ui.com/icons/opengraph-image.png",
    tags: [TAGS.icons],
    url: "https://www.radix-ui.com/icons",
  },
  {
    title: "Roundicons",
    author: "Ramy Wafaa",
    category: CATEGORIES.icons,
    className: "bg-foreground border-paper",
    description:
      "45,000+ premium vector icons across 29 packs. One-time payment, lifetime download access, 30-day money-back guarantee.",
    favicon: "https://roundicons.com/favicon.svg",
    ogImage: "https://roundicons.com/og.png",
    subtitle: "45,000+ premium vector icons in one bundle",
    tags: [TAGS.icons],
    url: "https://roundicons.com/",
  },
  {
    title: "Scribbles",
    author: "illustrations.run",
    category: CATEGORIES.icons,
    description:
      "Add personality to your design projects with this free collection of unique and playful SVG scribbles. Hand-drawn, these are ready for just copy and paste!",
    ogImage: "https://illustrations.run/images/scribbles-illustrations-og-image.png",
    subtitle: "Free SVG Illustrations - Unique Scribbles for Your Designs",
    tags: [TAGS.illustration, TAGS.svg],
    url: "https://illustrations.run/",
  },
  {
    title: "Scribbles Mix",
    author: "illustrations.run",
    category: CATEGORIES.icons,
    description: "More than 1000+ SVG scribbles. Add personality to your designs.",
    ogImage: "https://illustrations.run/scribbles-mix/images/scribbles-mix-header.png",
    subtitle: "SVG Collection (1000+ files)",
    tags: [TAGS.illustration, TAGS.svg],
    url: "https://illustrations.run/scribbles-mix/",
  },
  {
    title: "Smallbits",
    category: CATEGORIES.frontend,
    description:
      "290+ pixelated icons on a limited 8×8 grid where every point counts. Free for personal and commercial use.",
    subtitle: "290+ pixelated icons on an 8×8 grid",
    tags: [TAGS.icons],
    url: "https://smallbits.design/",
  },
  {
    title: "Supercons",
    category: CATEGORIES.icons,
    description:
      "A friendly open source React iconset by Lachlan Campbell. Download supercons icons on npm.",
    favicon: "https://supercons.vercel.app/apple-touch-icon.png",
    ogImage: "https://cloud-l7ijxkyvg.vercel.app/2021-02-02_21010z8cwfunpdn3jp59d7np4z6q5kdj.png",
    tags: [TAGS.icons],
    url: "https://supercons.vercel.app/",
  },
  {
    title: "SVG Clip-Path Generator",
    author: "naymur rahman",
    category: CATEGORIES.icons,
    description:
      "Create and customize SVG clip-path shapes for your website with ease. Free tool for web designers and developers.",
    ogImage: "https://tools.ui-layouts.com/clippath.jpg",
    tags: [TAGS.svg],
    url: "https://tools.ui-layouts.com/clip-paths",
  },
  {
    title: "Svg Doodle icon",
    category: CATEGORIES.icons,
    className: "bg-foreground border-paper",
    description: "Free Svg Doodle icon Pack",
    favicon: "https://svgicon.net/wp-content/uploads/2023/05/svg-doodle-icon-logo.png",
    tags: [TAGS.illustration, TAGS.svg],
    url: "https://svgicon.net/",
  },
  {
    title: "SVG Doodles",
    category: CATEGORIES.icons,
    description:
      "Browse a curated collection of free, customizable SVG doodles and icons to use in your websites, apps, slides, and prints.",
    subtitle: "Free, editable SVGs to spice up your designs",
    tags: [TAGS.svg],
    url: "https://svgdoodles.com/",
  },
  {
    title: "SVG Hub",
    category: CATEGORIES.icons,
    description: "Custom-color elements ready to paste into your project",
    tags: [TAGS.illustration, TAGS.svg],
    url: "https://svghub.vercel.app/",
  },
  {
    title: "SVGL",
    category: CATEGORIES.icons,
    description: "A beautiful library with SVG logos",
    ogImage: "https://svgl.app/images/screenshot_dark.png",
    tags: [TAGS.svg],
    url: "https://svgl.app/",
  },
  {
    title: "SVG Line Draw",
    author: "naymur rahman",
    category: CATEGORIES.icons,
    description:
      "SVG Line Draw is your creative playground for sketching hand-drawn lines, arrows, highlights, and animations. Perfect for annotations, web design, and interactive storytelling.",
    ogImage: "https://tools.ui-layouts.com/svgpathanimation.jpg",
    subtitle: "Sketch & Animate Hand-Drawn Lines for the Web",
    tags: [TAGS.svg],
    url: "https://tools.ui-layouts.com/svg-line-draw",
  },
  {
    title: "SvgPathEditor",
    author: "Yann Armelin",
    category: CATEGORIES.icons,
    description: "Online editor to create and manipulate SVG paths",
    tags: [TAGS.svg],
    url: "https://yqnn.github.io/svg-path-editor/",
  },
  {
    title: "SVG Path Visualizer",
    author: "Mathieu Dutour",
    category: CATEGORIES.icons,
    description:
      "Enter an SVG path data (the string inside the `d` attribute) to visualize it and discover all its different commands.",
    favicon: "https://svg-path-visualizer.netlify.app/logo512.png",
    ogImage: "https://svg-path-visualizer.netlify.app/og-image.png",
    tags: [TAGS.svg],
    url: "https://svg-path-visualizer.netlify.app/",
  },
  {
    title: "SVG Pattern Builder",
    category: CATEGORIES.icons,
    description:
      "SVG Pattern Builder allows you to create, customize, and download unique animated SVG patterns for your web and design projects. Great for Figma, Framer, Webflow and video projects.",
    ogImage: "https://svg.designcode.io/cover.jpg",
    subtitle: "Create and Customize Patterns Online",
    tags: [TAGS.svg],
    url: "https://svg.designcode.io/",
  },
  {
    title: "SVG Repo",
    category: CATEGORIES.icons,
    description:
      "Free Vectors and Icons in SVG format. ✅ Download free mono or multi color vectors for commercial use. Search in 500.000+ Free SVG Vectors and Icons.",
    subtitle: "Free SVG Vectors and Icons",
    url: "https://www.svgrepo.com/",
  },
  {
    title: "SVG Shapes",
    author: "Monika Michalczyk",
    category: CATEGORIES.icons,
    description: "Free copy-paste SVG Shapes for your next project. Made by Monika Michalczyk.",
    favicon: "https://framerusercontent.com/images/AcOOvejHuHDkEKzCQ1dp2N1qCs.svg",
    ogImage: "https://framerusercontent.com/images/MH0UKXtlzQanSSX5IHDcTM2gkI.jpg",
    tags: [TAGS.svg],
    url: "https://www.shapes.gallery/",
  },
  {
    title: "Svg Wave",
    category: CATEGORIES.icons,
    description:
      "SVG Wave is a minimal svg wave generator with lot of customization. It lets you abiltiy to generate and export pngs and svgs of beautiful waves. SVG wave also lets you layer multiple waves. Create SVGs for your website designs.",
    subtitle: "A free & beautiful gradient SVG wave Generator.",
    tags: [TAGS.svg],
    url: "https://svgwave.in/",
  },
  {
    title: "Symbl",
    author: "Revend Group",
    category: CATEGORIES.icons,
    description:
      "Discover a curated collection of SVG icons, HTML symbols, and design tools at Symbl. Perfect for developers and designers to enhance web projects with ease and creativity.",
    ogImage: "https://symbl.revend.group/img/cover.jpg",
    subtitle: "Your Ultimate Symbol Library",
    tags: [TAGS.svg],
    url: "https://symbl.revend.group/",
  },
  {
    title: "Tabler Icons",
    author: "codecalm",
    category: CATEGORIES.icons,
    description:
      "Tabler Icons: 6184 free and open source SVG icons. Customizable size, color and stroke. Available for React, SolidJS, Vue, Figma and more for free!",
    favicon: "https://tabler.io/favicon.ico",
    ogImage: "https://tabler.io/icons/opengraph-image-1v9qf3.png",
    subtitle: "6150+ free vector icons for web design",
    tags: [TAGS.icons],
    url: "https://tabler.io/icons",
  },
  {
    title: "TechIcons",
    category: CATEGORIES.icons,
    description: "Download, copy and paste tech icons in SVG and PNG format for your projects.",
    subtitle: "SVG and PNG tech icons",
    tags: [TAGS.icons],
    url: "https://techicons.dev/",
  },
  {
    title: "useAnimations",
    author: "Patrik Svoboda",
    category: CATEGORIES.icons,
    description:
      "Library of animated icons created in Lottie Framework for immediate use in your applications or websites.",
    favicon: "https://useanimations.com/images/apple-touch-icon.png",
    ogImage: "https://useanimations.com/images/OGuseAnimationsImage.jpg",
    subtitle: "A micro-animations library",
    tags: [TAGS.animation, TAGS.icons, TAGS.svelte],
    url: "https://useanimations.com/",
  },
  {
    title: "User Initial avatars",
    author: "Lasse Rafn",
    category: CATEGORIES.icons,
    description:
      "Generate image avatars with user initials for free, just specify name. No limits or registration.",
    ogImage: "https://ui-avatars.com/assets/meta.png",
    subtitle: "Generate avatars with initials",
    url: "https://ui-avatars.com/",
  },
  {
    title: "Vecto3d",
    category: CATEGORIES.icons,
    description: "A super simple tool to convert SVG logos to 3D models",
    ogImage: "https://www.vecto3d.xyz/twitter-image-v1.png",
    subtitle: "Convert SVGs to 3D",
    tags: [TAGS.svg, TAGS["3D"]],
    url: "https://vecto3d.app/",
  },
  {
    title: "Vivus Instant",
    category: CATEGORIES.icons,
    description: "Inline SVG Drawing Animation with CSS",
    favicon: "https://maxwellito.github.io/vivus-instant/assets/vivus_instant_logo.svg",
    ogImage: "https://maxwellito.github.io/vivus-instant/assets/vivus_instant_logo_loop.svg",
    tags: [TAGS.animation, TAGS.svg],
    url: "https://maxwellito.github.io/vivus-instant/",
  },
  {
    title: "Warp SVG Online",
    author: "Pavel Laptev",
    category: CATEGORIES.icons,
    description: "Warp and distort SVG online",
    favicon: "https://pavellaptev.github.io/warp-svg/dist/images/favicons/favico-128.png",
    ogImage:
      "https://raw.githubusercontent.com/PavelLaptev/warp-svg/master/dist/images/web-preview.jpg",
    tags: [TAGS.svg],
    url: "https://pavellaptev.github.io/warp-svg/",
  },
];
