import { Tool } from "@/types";

import { CATEGORIES } from "./categories";
import { TAGS } from "./tags";

export const mediaLinks: Tool[] = [
  {
    title: "3dsvg",
    category: CATEGORIES.media,
    description:
      "Turn any SVG into interactive 3D objects. Animate and export as 4K image or video. 100% free, no account or subscription needed.",
    subtitle: "The easiest way to turn SVGs into 3D",
    url: "https://3dsvg.design/",
  },
  {
    title: "Acubens Design",
    category: CATEGORIES.media,
    description: "Streetwear & Apparel Designer",
    favicon: "https://public-files.gumroad.com/26oayrlqvhks3p08s0852u8kujl5",
    ogImage: "https://public-files.gumroad.com/6vvkk7rwhwtatsuoql3f9msyd59s",
    url: "https://acubensdesign.gumroad.com/",
  },
  {
    title: "AI Background Remover",
    category: CATEGORIES.media,
    description:
      "Erase image backgrounds and make a transparent background, using AI. Remove backgrounds from any photo online for free",
    subtitle: "Remove Background From Image",
    url: "https://www.remove.bg/",
  },
  {
    title: "A Little Box of Goodies",
    category: CATEGORIES.media,
    description:
      "A Little Box of Goodies est. for sending a little care things to tuck inside. Photo + Photo Song + Song Video + Video Gift + Gift Voice + Voice Drawing + Drawing Location + Location Coupon + Coupon News + News",
    favicon: "https://alittleboxofgoodies.com/favicon.ico",
    subtitle: "digital care package",
    url: "https://alittleboxofgoodies.com/",
  },
  {
    title: "ASCIInator",
    category: CATEGORIES.media,
    description:
      "Create clean, high-quality ASCII art from your images. Export in PNG, SVG, or TXT. Fast, minimal, and built for beautiful visuals.",
    tags: [TAGS.image],
    url: "https://asciinator.app/",
  },
  {
    title: "Audio Library",
    category: CATEGORIES.media,
    description: "tapis d'épingle by Rrrrrose Azerty · Country & Folk music / Calm music",
    favicon: "https://cdn.audiolibrary.com.co/themes/ytalc/assets/favicon/apple-touch-icon.png",
    ogImage: "https://cdn.audiolibrary.com.co/themes/ytalc/assets/img/og-home.jpeg",
    subtitle: "No Copyright Music",
    tags: [TAGS.audio],
    url: "https://audiolibrary.com.co/",
  },
  {
    title: "Avatars",
    author: "Outpace Studios",
    category: CATEGORIES.media,
    description:
      "Free, zero-dependency React component for generative gradient avatars. Any seed becomes a unique mesh gradient or crisp dither, no stored images or network calls.",
    favicon: "https://outpacestudios.com/favicon.svg",
    ogImage: "https://avatars.outpacestudios.com/meta.jpg",
    subtitle: "Beautiful Generative Gradient Avatars for React",
    tags: [TAGS.image],
    url: "https://avatars.outpacestudios.com/",
  },
  {
    title: "Basic Pattern Repository",
    author: "Thomas Michael Semmler",
    category: CATEGORIES.media,
    description:
      "A collection of hand-coded SVG <pattern>'s, ready to be used in inline SVG or however you like.",
    favicon: "https://patterns.helloyes.dev/assets/favicons/1.svg",
    ogImage: "https://patterns.helloyes.dev/previews/default.png",
    tags: [TAGS.patterns, TAGS.svg],
    url: "https://patterns.helloyes.dev/",
  },
  {
    title: "BDFM",
    category: CATEGORIES.media,
    description: "Bitmap generator",
    favicon: "https://bitmap.designfamilymarket.com/assets/apple-touch-icon.png",
    ogImage: "https://bitmap.designfamilymarket.com/assets/logo.png",
    url: "https://bitmap.designfamilymarket.com/",
  },
  {
    title: "blobSketch",
    category: CATEGORIES.media,
    description:
      "blobSketch is a WebGL-based canvas for creating physics-driven blobs, lines, and repulsion circles. Draw shapes, tweak physics, then export to SVG or high-res JPG.",
    favicon: "https://avatars.githubusercontent.com/u/1743726",
    ogImage: "https://cpreid2.github.io/blobSketch/images/splash.png",
    url: "https://cpreid2.github.io/blobSketch/",
  },
  {
    title: "Blush",
    category: CATEGORIES.media,
    description:
      "Blush makes it easy to add free illustrations to your designs. Play with fully customizable graphics made by artists across the globe.",
    favicon: "https://blush.design/apple-touch-icon.png",
    ogImage: "https://blush.design/og-image.png",
    subtitle: "Illustrations for everyone",
    tags: [TAGS.illustration],
    url: "https://blush.design/",
  },
  {
    title: "Bulk Image Resizer",
    author: "Jasper Bernaers",
    category: CATEGORIES.media,
    description:
      "Free online bulk image resizer — resize multiple JPEG, PNG & WebP images at once by pixels, percentage or preset. Batch resize for web, social media & email. Drag & drop, lock aspect ratio, crop/fit/pad, download as ZIP. No signup, no upload, 100% client-side.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/bulk-image-resizer/og-image.png",
    subtitle: "Resize Multiple Images Online Free",
    tags: [TAGS.image],
    url: "https://jasperbernaers.com/bulk-image-resizer/",
  },
  {
    title: "Carbon",
    category: CATEGORIES.media,
    description:
      "Carbon is the easiest way to create and share beautiful images of your source code.",
    favicon: "https://carbon.now.sh/favicon.ico",
    ogImage: "https://carbon.now.sh/static/brand/banner.png",
    subtitle: "Create and share beautiful images of your source code",
    url: "https://carbon.now.sh/",
  },
  {
    title: "CleanPNG",
    category: CATEGORIES.media,
    description:
      "Discover transparent background images and illustrations. Best quality, free unlimited download.",
    subtitle: "HD png images and illustrations. Free unlimited download. - CleanPNG",
    tags: [TAGS.image],
    url: "https://www.cleanpng.com/",
  },
  {
    title: "Clipdrop",
    category: CATEGORIES.media,
    description: "Remove background, cleanup pictures, upscaling, Stable diffusion and more…",
    favicon: "https://clipdrop.co/favicon.ico",
    ogImage: "https://assets.reactbricks.com/G-dH90DZVcB0SiT/images/original/Lxv-0lCYYQgvMU7.webp",
    subtitle: "Create stunning visuals in seconds with AI.",
    url: "https://clipdrop.co/",
  },
  {
    title: "Convert PNG to ICO file",
    author: "Kristjan Retter",
    category: CATEGORIES.media,
    description:
      "Convert PNG to ICO files instantly in your browser. Create multi-size favicon bundles for websites without uploading files.",
    subtitle: "Custamizable",
    url: "https://png-to-ico.com/",
  },
  {
    title: "Convert to it!",
    category: CATEGORIES.media,
    description:
      "Truly universal online file converter. Private, on-device conversion across mediums.",
    url: "https://p2r3.github.io/convert/",
  },
  {
    title: "ConvertX",
    author: "Emrik Östling",
    category: CATEGORIES.media,
    description: "💾 Self-hosted online file converter. Supports 1000+ formats ⚙️",
    favicon: "https://raw.githubusercontent.com/C4illin/ConvertX/main/public/favicon.svg",
    ogImage:
      "https://repository-images.githubusercontent.com/783343310/5c97fe6b-0ba3-4d51-b04c-704d93920842",
    tags: [TAGS.selfHosted],
    url: "https://github.com/C4illin/ConvertX",
  },
  {
    title: "coolshapes",
    author: "Vijay Verma",
    category: CATEGORIES.media,
    description:
      "100+ Abstract shapes with cool grainy gradient. Ready to use with any design dev project.",
    ogImage: "https://coolshap.es/preview.jpg?v1",
    tags: [TAGS.illustration, TAGS.shapes],
    url: "https://coolshap.es/",
  },
  {
    title: "Craiyon",
    category: CATEGORIES.media,
    description:
      "Remove background from image - unlimited, HD, fast, free & no sign up! Remove Bg & add white background, black background or transparent background.",
    subtitle: "FREE HD Background Remover | Remove Bg Online",
    url: "https://www.craiyon.com/en/background-remover",
  },
  {
    title: "Create beautiful images of your code",
    author: "Raycast",
    category: CATEGORIES.media,
    description:
      "Turn your code into beautiful images. Choose from a range of syntax colors, hide or show the background, and toggle between a dark and light window.",
    ogImage: "https://www.ray.so/_next/static/media/og.0wf8b~rvlko.g.png",
    url: "https://ray.so/",
  },
  {
    title: "DesignFamilyMarket",
    category: CATEGORIES.media,
    description: "High-Quality Graphic Assets",
    favicon: "https://public-files.gumroad.com/hke4c923a9zy7vs2a22bokrqhw9c",
    ogImage: "https://public-files.gumroad.com/06rfjlkmfxuxa2ml4mvnhtogards",
    url: "https://designfamilymarket.gumroad.com/",
  },
  {
    title: "DesignUp",
    category: CATEGORIES.media,
    description: "On Gumroad",
    favicon: "https://public-files.gumroad.com/ot3nmgnwlzwolsh1v5mbltbq1svu",
    ogImage: "https://public-files.gumroad.com/ynrrbypqs8yw1noozlv1cixvyzcd",
    url: "https://designupnet.gumroad.com/",
  },
  {
    title: "digibouquet",
    category: CATEGORIES.media,
    description:
      "Build a beautiful digital flower bouquet and send it to someone you love. Choose from roses, peonies, sunflowers, and more. Free, fun, and made with love.",
    subtitle: "send a digital flower bouquet",
    url: "https://digibouquet.vercel.app/",
  },
  {
    title: "Doodle Ipsum",
    category: CATEGORIES.media,
    description: "Illustration placeholders for developers. Powered by Blush",
    favicon: "https://blush.design/apple-touch-icon.png",
    ogImage: "https://doodleipsum.com/1000x750/flat?bg=e3f5f8&i=23243fc71ac1a810a5873bde01e17f07",
    tags: [TAGS.illustration],
    url: "https://doodleipsum.com/",
  },
  {
    title: "DrawKit",
    category: CATEGORIES.media,
    description:
      "Free and premium vector SVG illustrations for you to use on your next project, no attribution required! Vector illustrations, icons, 3D illustrations, animation, mockups, Figma plugins and more.",
    favicon:
      "https://cdn.prod.website-files.com/682d1c6b3c16bb956eafd69b/682d1c6b3c16bb956eafd82f_DrawKit-Webclip.png",
    ogImage:
      "https://cdn.prod.website-files.com/626f5d0ae6c15c780f2dd5c4/6336572b684b9428785ccd40_DrawKit%20Website%20preview.png",
    subtitle: "Beautiful 2D & 3D Illustrations and Icons",
    tags: [TAGS.illustration],
    url: "https://www.drawkit.com/",
  },
  {
    title: "Effect.app",
    category: CATEGORIES.media,
    className: "bg-foreground border-paper",
    description:
      "Apply visual effects to images and videos online — glitch, blur, distort, halftone & more.",
    favicon: "https://effect.app/icon.svg",
    ogImage: "https://effect.app/effect-og.jpg",
    subtitle: "Online Image & Video Effect Generator – Free",
    tags: [TAGS.svg],
    url: "https://effect.app/",
  },
  {
    title: "fffuel",
    category: CATEGORIES.media,
    description:
      "A fun collection of free SVG generators for gradients, patterns, shapes, textures & cool backgrounds. Plus, some more color tools for web designers.",
    favicon: "https://www.fffuel.co/images/favicon/favicon.svg",
    ogImage: "https://fffuel.co/images/cover.png",
    subtitle: "Free SVG generators, color tools & web design tools",
    tags: [TAGS.color, TAGS.svg, TAGS.tool],
    url: "https://www.fffuel.co/",
  },
  {
    title: "Fisga Studio",
    category: CATEGORIES.media,
    description: "Unusual resources for next level design",
    favicon: "https://public-files.gumroad.com/mog7q685yre30sghfsi6b3n26xx3",
    ogImage: "https://public-files.gumroad.com/4y7k85ewz5lhf8rvhbo7noeooikm",
    url: "https://fisga.gumroad.com/",
  },
  {
    title: "Fluidmotion",
    category: CATEGORIES.media,
    description:
      "A curated collection of beautiful customizable video backgrounds for you to edit and use in your own projects.",
    favicon: "https://fluidmotion.app/apple-touch-icon-192.png",
    ogImage: "https://fluidmotion.app/social-preview.png",
    tags: [TAGS.video],
    url: "https://fluidmotion.app/",
  },
  {
    title: "Free ASCII Art Generator",
    author: "Jasper Bernaers",
    category: CATEGORIES.media,
    description:
      "Free ASCII art generator — the easiest ascii pictures generator and ascii text maker online. Convert any image or photo to ASCII art, or transform text into ASCII art fonts (like Patorjk TAAG). 50+ FIGlet fonts, color mode, multiple character sets. Download as TXT or PNG. No upload, no sign-up, 100% private.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/ASCII-generator/og-image.png",
    subtitle: "Text to ASCII Art Maker & Braille Art | No Upload | Patorjk Alternative",
    tags: [TAGS.ascii, TAGS.tool],
    url: "https://jasperbernaers.com/ASCII-generator/",
  },
  {
    title: "Free ASCII Webcam",
    author: "Jasper Bernaers",
    category: CATEGORIES.media,
    description:
      "Turn your webcam into live ASCII art — real-time camera to text conversion in your browser. Multiple character sets (Blocks, Braille, Detailed, Binary), color mode, adjustable FPS & resolution. Record GIFs, take snapshots. 100% private, no upload, no sign-up.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/ascii-webcam/og-image.png",
    subtitle: "Live Camera to ASCII Art in Real-Time | No Upload",
    tags: [TAGS.ascii, TAGS.tool],
    url: "https://jasperbernaers.com/ascii-webcam/",
  },
  {
    title: "Free Barcode Generator Online",
    author: "Jasper Bernaers",
    category: CATEGORIES.media,
    description:
      "Create barcodes online free — Code 128, EAN-13, EAN-8, UPC-A, UPC-E, ITF-14, GS1-128, Code 39, MSI, Codabar & Pharmacode. Live preview, custom size & colors, download PNG or SVG. No signup, no watermark, 100% in your browser.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/online-free-barcode-generator/og-image.png",
    subtitle: "EAN-13, UPC-A, Code 128 & 15+ Formats (PNG/SVG)",
    tags: [TAGS.barcode],
    url: "https://jasperbernaers.com/online-free-barcode-generator/",
  },
  {
    title: "Free Business Card Designer",
    author: "Jasper Bernaers",
    category: CATEGORIES.media,
    description:
      "Free online business card designer — a fancy visual editor with 22 templates, logo upload, gradients & patterns, shapes and icons, QR codes, snap guides, front & back, and print-ready 300 DPI PDF export with bleed and crop marks. EU, US and square sizes. No signup, no watermark.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/business-card-designer/og-image.png",
    subtitle: "22 Templates, Logo Upload, QR Codes, Print-Ready PDF",
    url: "https://jasperbernaers.com/business-card-designer/",
  },
  {
    title: "Free Clipart & Illustrations",
    author: "Icons8",
    category: CATEGORIES.media,
    description:
      "Download free clipart images and graphics in PNG, SVG, GIF formats. Explore our vector, 3D, and animated illustrations for commercial use.",
    favicon: "https://maxst.icons8.com/vue-static/illustrations/favicon/ouch-96x96.png",
    ogImage: "https://maxst.icons8.com/vue-static/illustrations/seo/opengraph.png",
    subtitle: "Vector SVG and PNG Graphics, Ouch Images for Download",
    tags: [TAGS.illustration],
    url: "https://icons8.com/illustrations",
  },
  {
    title: "Free Favicon Generator",
    author: "Jasper Bernaers",
    category: CATEGORIES.media,
    description:
      "Free favicon generator — upload any image and instantly create favicons in all sizes: 16x16, 32x32, 48x48, 96x96, 180x180 (Apple Touch Icon), 192x192 & 512x512 (Android/PWA). Get ready-to-use HTML code. No upload to server, no sign-up, 100% browser-based.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/free-favicon-generator/og-image.png",
    subtitle: "All Sizes & Platforms from Any Image",
    tags: [TAGS.image],
    url: "https://jasperbernaers.com/free-favicon-generator/",
  },
  {
    title: "Free Online Audio Editor",
    author: "Jasper Bernaers",
    category: CATEGORIES.media,
    description:
      "Free audio editor in your browser: cut, trim, fade, normalize, reverse, speed change, filters, echo, reverb, noise gate, compressor. Record from mic, view spectrogram, loop selections, export WAV or MP3. No upload — 100% private, no sign-up.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/audio-editor/og-image.png",
    subtitle: "Cut, Trim, Effects, Record & Export MP3/WAV",
    tags: [TAGS.audio, TAGS.tool],
    url: "https://jasperbernaers.com/audio-editor/",
  },
  {
    title: "Free Placeholder Logo Collection",
    category: CATEGORIES.media,
    description:
      "Browse and customize our eye catching transparent placeholder logo collection and download it as SVG or PNG.",
    favicon:
      "https://i0.wp.com/graphicsauce.co/free-placeholder-logo/wp-content/uploads/2024/08/graphicsauce-icon.png?fit=117,5126&ssl=1",
    ogImage:
      "https://graphicsauce.co/free-placeholder-logo/wp-content/uploads/2024/08/Free-PlaceHolder-Logo.jpg",
    tags: [TAGS.logo],
    url: "https://graphicsauce.co/free-placeholder-logo/",
  },
  {
    title: "Free QR Code Generator",
    author: "Jasper Bernaers",
    category: CATEGORIES.media,
    description:
      "Generate QR codes for URLs, WiFi, vCard, SMS, email, calendar events, location & crypto. Custom dot styles, logo overlay, SVG export, bulk ZIP download, QR code scanner. 100% free, private, no signup.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/QR/og-image.png",
    subtitle: "URL, WiFi, vCard, Bulk + QR Scanner",
    tags: [TAGS.qr],
    url: "https://jasperbernaers.com/QR/",
  },
  {
    title: "Fresh Folk",
    category: CATEGORIES.media,
    description: "An illustration library of people and objects",
    ogImage: "https://fresh-folk.com/assets/images/card.jpg?v=c3f994c8",
    tags: [TAGS.illustration],
    url: "https://fresh-folk.com/",
  },
  {
    title: "GetIllustrations",
    category: CATEGORIES.media,
    description:
      "170,000+ hand-drawn vector illustrations & icons, SVG, PNG & Adobe Illustrator. Free packs + All-Access from $195/yr. Commercial license, no attribution.",
    favicon: "https://getillustrations.com/images/logo/logo.svg",
    ogImage:
      "https://getillustrations.com/images/Getillustrations-free-and-premium-vector-illustrations.png",
    subtitle: "170K+ Vector Illustrations & Icons: SVG, PNG & AI",
    tags: [TAGS.illustration],
    url: "https://getillustrations.com/",
  },
  {
    title: "Good Stuff No Nonsense",
    category: CATEGORIES.media,
    description:
      "Looking for hand drawn icons of exceptional quality? You're in the right place. This little vector illustrations are ready to use in your designs.",
    favicon:
      "https://goodstuffnononsense.com/wp-content/uploads/2016/03/cropped-gsnn-sygnet-heart-2-300x300.png",
    subtitle: "Hand Drawn Vector Icons",
    tags: [TAGS.illustration],
    url: "https://goodstuffnononsense.com/",
  },
  {
    title: "HEIC to JPG Converter",
    author: "Jasper Bernaers",
    category: CATEGORIES.media,
    description:
      "Convert HEIC to JPG online for free — drop your iPhone photos and they convert instantly, in batch, right in your browser. No upload to any server, no watermark, no signup, no limits. Also HEIC to PNG and WebP, quality control and ZIP download. Works on Windows 10/11, Android, Mac and Linux.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/free-heic-to-jpg-converter/og-image.png",
    subtitle: "Free, Batch, No Upload (Windows, Android, Mac)",
    tags: [TAGS.heic, TAGS.image, TAGS.jpg, TAGS.tool],
    url: "https://jasperbernaers.com/free-heic-to-jpg-converter/",
  },
  {
    title: "iiisometric",
    author: "fffuel",
    category: CATEGORIES.media,
    description:
      "Create isometric design constructions by placing blocks together to form complex 3D-looking shapes. Export your creations as SVG files.",
    favicon: "https://fffuel.co/images/favicon/favicon.svg",
    ogImage: "https://fffuel.co/images/covers/iiisometric.png",
    subtitle: "3D-like isometric design builder",
    tags: [TAGS.svg],
    url: "https://www.fffuel.co/iiisometric/",
  },
  {
    title: "Image to ASCII Converter",
    author: "Jasper Bernaers",
    category: CATEGORIES.media,
    description:
      "Free image to ASCII converter — turn any PNG, JPG or WebP photo into ASCII art instantly. One-tap styles, braille dot art, color ASCII, dithering. Copy, share, download TXT or PNG. No upload, no signup, 100% in your browser.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/image-to-ascii/og-image.png",
    subtitle: "PNG, JPG & SVG to ASCII Art Online Free",
    tags: [TAGS.ascii, TAGS.image, TAGS.tool],
    url: "https://jasperbernaers.com/image-to-ascii/",
  },
  {
    title: "Image Tools Pro",
    category: CATEGORIES.media,
    description:
      "Transform your photos with ease using imagetoolspro.com. Edit, crop, resize, and customize your images effortlessly with our advanced editing features.",
    favicon: "https://imagetoolspro.com/picture.webp",
    ogImage: "https://imagetoolspro.com/img/logo.svg",
    subtitle: "Online Image Tools — Edit & Enhance Photos with imagetoolspro",
    tags: [TAGS.image],
    url: "https://imagetoolspro.com/",
  },
  {
    title: "Image Watermark Tool",
    author: "Jasper Bernaers",
    category: CATEGORIES.media,
    description:
      "Free online image watermark tool. Add a text or logo watermark to your photos with custom position, opacity, rotation, tiling and fonts. Export as PNG or JPEG. 100% client-side — your images never leave your browser, no uploads, no sign-up.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/image-watermark/og-image.png",
    subtitle: "Add Text & Image Watermarks Online",
    tags: [TAGS.image],
    url: "https://jasperbernaers.com/image-watermark/",
  },
  {
    title: "LinkedIn Text Formatter",
    author: "Jasper Bernaers",
    category: CATEGORIES.media,
    description:
      "Make text bold or italic on LinkedIn in seconds: type, style, copy, paste. Free LinkedIn post formatter with Unicode bold, italic, bullets ▸ and checkmarks ✓ — no login, no ads, character counter included.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/LinkedIn-Post-Formatter/og-image.png",
    subtitle: "Free Bold & Italic Text Generator for LinkedIn Posts",
    tags: [TAGS.social],
    url: "https://jasperbernaers.com/LinkedIn-Post-Formatter/",
  },
  {
    title: "llline",
    author: "fffuel",
    category: CATEGORIES.media,
    description:
      "SVG generator that makes it easy to create lines & strokes that look and feel organic. Tweak the colors, add dashes and make it your own, then export the SVG.",
    favicon: "https://fffuel.co/images/favicon/favicon.svg",
    ogImage: "https://fffuel.co/images/covers/llline.png",
    subtitle: "Smooth SVG Line/Stroke Generator",
    tags: [TAGS.svg],
    url: "https://fffuel.co/llline/",
  },
  {
    title: "Logos",
    category: CATEGORIES.media,
    description:
      "15,015 free SVG logos for apps, dev tools and tech brands. Search, filter by category, download or copy in one click.",
    tags: [TAGS.logo],
    url: "https://logos.lndev.me/",
  },
  {
    title: "Magnific",
    category: CATEGORIES.media,
    description:
      "The complete platform of creative AI tools for image, video, and audio generation. Create anything from campaigns, product shots to filmmaking. Be Magnific.",
    favicon: "https://media.magnific.com/magnific-favicons/favicon-dark.svg",
    ogImage: "https://media.magnific.com/meta-tags-social/mg-home-og.jpg",
    subtitle: "The AI Creative Platform",
    tags: [TAGS.audio, TAGS.image, TAGS.video],
    url: "https://www.magnific.com/",
  },
  {
    title: "Making SVG Loading Spinners",
    author: "fffuel",
    category: CATEGORIES.media,
    description:
      "Learn to create a cool SVG loading spinner with this step-by-step guide. We'll use attributes like stroke-dasharray and stroke-dashoffset to make it easy.",
    favicon: "https://fffuel.co/images/favicon/favicon.svg",
    ogImage: "https://fffuel.co/images/covers/svg-spinner.jpg",
    subtitle: "An Interactive Guide",
    tags: [TAGS.svg],
    url: "https://fffuel.co/svg-spinner/",
  },
  {
    title: "Media Cheat Sheet",
    category: CATEGORIES.media,
    description:
      "Easily access the most accurate image and video specs for social media and digital advertising. Stay updated with the latest sizes, dimensions, and specifications.",
    favicon: "https://mediacheatsheet.com/favicon.png",
    ogImage: "https://mediacheatsheet.com/og-image.jpg",
    subtitle: "Social Media & Ad Specs Cheat Sheet",
    url: "https://mediacheatsheet.com/",
  },
  {
    title: "mmmotif",
    author: "fffuel",
    category: CATEGORIES.media,
    description:
      "Easily generate SVG shape patterns with a 3D feel, thanks to isometric design. Export the SVG code and use the 3D patterns in your designs right away.",
    favicon: "https://fffuel.co/images/favicon/favicon.svg",
    ogImage: "https://fffuel.co/images/covers/mmmotif.png",
    subtitle: "SVG generator for 3D-like isomorphic patterns",
    tags: [TAGS.svg],
    url: "https://fffuel.co/mmmotif/",
  },
  {
    title: "Need3D",
    category: CATEGORIES.media,
    description:
      "Library of free 3D objects for your projects, stock 3D illustrations, abstract 3D graphics",
    ogImage: "https://static.tildacdn.com/tild3635-6261-4232-b337-343261643835/Frame_137.jpg",
    subtitle: "library 3D illustrations",
    tags: [TAGS["3D"]],
    url: "https://need3d.ru/en",
  },
  {
    title: "Newt",
    author: "Pablo Stanley",
    category: CATEGORIES.media,
    description:
      "A code-native pixel art tool. Paint like a normal raster editor; underneath, every pixel is a color token in clean, editable code. Export SVG, CSS, React, PNG, and GIF.",
    favicon: "https://newt.sh/icon.svg",
    ogImage: "https://newt.sh/opengraph-image.png",
    subtitle: "pixel art, code underneath",
    tags: [TAGS.image],
    url: "https://newt.sh/",
  },
  {
    title: "OGimage.gallery",
    category: CATEGORIES.media,
    description: "Gallery with the best and most carefully collected OG images.",
    ogImage:
      "https://cdn.prod.website-files.com/6040b8a8176ad35fd8dbf709/606597ba2d86c0c02d518010_og.jpg",
    subtitle: "The finest hand-picked OG Images ✨",
    tags: [TAGS.image],
    url: "https://www.ogimage.gallery/",
  },
  {
    title: "OmniVoice Studio",
    author: "Palash Debnath",
    category: CATEGORIES.media,
    description:
      "A cinematic audio dubbing, cloning and voice generation studio. Enterprise-grade processing with AI-powered voice synthesis, 600+ language support, and self-hosted deployment.",
    subtitle: "Cinematic audio dubbing, cloning & voice generation | palash.dev",
    tags: [TAGS.audio],
    url: "https://palash.dev/omnivoice/",
  },
  {
    title: "On Fire illustrations",
    category: CATEGORIES.media,
    description:
      "Free illustrations that will wake up any project with its unique mood. Say «YES» to mind-blowing design.",
    favicon: "https://onfire.craftwork.design/images/favicon.png",
    ogImage: "https://onfire.craftwork.design/images/Open-Graph.png",
    tags: [TAGS.illustration],
    url: "https://onfire.craftwork.design/",
  },
  {
    title: "Online converter",
    category: CATEGORIES.media,
    description:
      "Convert files like images, video, documents, audio and more to other formats with this free and fast online converter.",
    favicon: "https://www.online-convert.com/assets/favicon/apple-touch-icon.png",
    ogImage:
      "https://www.online-convert.com/assets/social-share-image/en/www-online-convert-com.png",
    subtitle: "Convert video, images, audio and documents for free",
    tags: [TAGS.tool],
    url: "https://www.online-convert.com/",
  },
  {
    title: "Pablo Stanley",
    author: "Pablo Stanley",
    category: CATEGORIES.media,
    description:
      "Hi, I'm Pabs. I make pixel characters, doodle packs, illustration brushes, apps, and sometimes a course. Most are free. Take what you need.",
    favicon: "https://public-files.gumroad.com/l8v9qevsaqbjn54phbdvxfe12ccz",
    ogImage: "https://public-files.gumroad.com/w7gn8wgeepf3ju0xtqdoslypjb7f",
    url: "https://pablostanley.gumroad.com/",
  },
  {
    title: "Pastefy",
    category: CATEGORIES.media,
    description: "Pastefy is an Open Source self-hosted Pastebin/GithubGist alternative.",
    favicon: "https://pastefy.app/icons/apple-touch-icon.png",
    ogImage: "https://pastefy.app/thumbnail.png",
    subtitle: "Share your code snippets",
    url: "https://pastefy.app",
  },
  {
    title: "Pattern Monster",
    category: CATEGORIES.media,
    description:
      "A simple online pattern generator to create repeatable SVG patterns. Perfect for website backgrounds, apparel, branding, packaging design and more.",
    tags: [TAGS.image],
    url: "https://pattern.monster/",
  },
  {
    title: "Peeps Avatar Builder by UI8.net",
    category: CATEGORIES.media,
    description: "Look what I just made with the Peeps Avatar Builder @UI8",
    favicon: "https://peeps.ui8.net/apple-touch-icon.png",
    ogImage: "https://peeps-ui8-net-master.s3.amazonaws.com/meta-image.png",
    tags: [TAGS.illustration],
    url: "https://peeps.ui8.net/",
  },
  {
    title: "Pexels",
    category: CATEGORIES.media,
    description:
      "Free stock photos & videos you can use everywhere. Browse millions of high-quality royalty free stock images & copyright free pictures. No attribution required.",
    favicon: "https://static.pexels.com/1/images/meta/safari-pinned-tab.svg",
    ogImage: "https://static.pexels.com/1/images/meta/pexels-stock-photos.jpg",
    subtitle: "Free Stock Photos, Royalty Free Stock Images & Copyright Free Pictures",
    url: "https://www.pexels.com/",
  },
  {
    title: "Photo Collage Maker",
    author: "Jasper Bernaers",
    category: CATEGORIES.media,
    description:
      "Free browser-based photo collage maker. Pick a layout (grids, mosaics, filmstrip, pixel heart), drop in photos, zoom & pan, apply filters, add captions and export PNG or JPEG. 100% client-side — no upload, no account, no watermark.",
    favicon: "https://jasperbernaers.com/favicon.svg",
    ogImage: "https://jasperbernaers.com/photo-collage/og-image.png",
    subtitle: "Free Online Grid & Freeform Collages",
    tags: [TAGS.image],
    url: "https://jasperbernaers.com/photo-collage/",
  },
  {
    title: "Pixel Surplus",
    category: CATEGORIES.media,
    description:
      "Free stock photos & videos you can use everywhere. Browse millions of high-quality royalty free stock images & copyright free pictures. No attribution required.",
    favicon: "https://pixelsurplus.com/cdn/shop/files/PS-Brand-Draft.png",
    ogImage: "https://pixelsurplus.com/cdn/shop/files/All-Access-Header_1200x630.png",
    subtitle: "Resources for Creators",
    url: "https://pixelsurplus.com/",
  },
  {
    title: "Placeholder Image Generator",
    author: "Kristjan Retter",
    category: CATEGORIES.media,
    description:
      "Create free placeholder images using our generator. Select your brand colors and image size, and copy the image URL",
    favicon: "https://placeholderimage.io/logo.svg",
    ogImage: "https://placeholderimage.io/thumbnail.png",
    subtitle: "With Brand Colors",
    tags: [TAGS.image],
    url: "https://placeholderimage.io/",
  },
  {
    title: "Pngfile",
    category: CATEGORIES.media,
    description:
      "Download 100% free PNG images with transparent backgrounds! Browse thousands of high-resolution PNGs for designers, marketers & content creators. No attribution required!.",
    tags: [TAGS.design, TAGS.image],
    url: "https://pngfile.net/",
  },
  {
    title: "Rebrand",
    category: CATEGORIES.media,
    description:
      "Explore the best new design systems, identity launches, and rebrand reveal videos.",
    favicon: "https://www.rebrand.gallery/apple-icon.png",
    subtitle: "A curated gallery of rebrands and visual identities",
    tags: [TAGS.image, TAGS.video],
    url: "https://www.rebrand.gallery/",
  },
  {
    title: "remove.bg",
    author: "Icons8",
    category: CATEGORIES.media,
    description:
      "Remove image backgrounds automatically in 5 seconds with just one click. Don't spend hours manually picking pixels. Upload your photo now & see the magic.",
    subtitle: "Remove Background from Image for Free",
    url: "https://icons8.com/bgremover",
  },
  {
    title: "Same Energy",
    category: CATEGORIES.media,
    description: "Find beautiful images.",
    ogImage: "https://same.energy/blacklogo-bg.png",
    subtitle: "Visual Search Engine",
    tags: [TAGS.image],
    url: "https://same.energy/",
  },
  {
    title: "Sine wave SVG generator",
    category: CATEGORIES.media,
    description:
      "Generate perfect sine waves and export them as SVG for your designs and backgrounds.",
    favicon: "https://www.sinwaver.com/favicon.svg",
    ogImage: "https://i.ibb.co/r4rqt4s/OG-image.png",
    tags: [TAGS.svg],
    url: "https://www.sinwaver.com/",
  },
  {
    title: "SketchValley",
    category: CATEGORIES.media,
    description:
      "1,000+ free illustrations for websites, apps and presentations — SVG and PNG, no attribution required. Flat, 3D, hand-drawn and minimal styles. No signup, instant download.",
    favicon: "https://sketchvalley.com/uploads/logo.svg",
    subtitle: "Free SVG & PNG Illustrations for Commercial Use — No Attribution",
    tags: [TAGS.illustration],
    url: "https://sketchvalley.com/",
  },
  {
    title: "slides.supply",
    author: "Vlad Muslakov",
    category: CATEGORIES.media,
    description:
      "A curated library of presentation slide inspiration — the individual slides people actually need when building presentations, pitching ideas, and telling stories.",
    favicon: "https://slides.supply/favicon.ico",
    ogImage: "https://slides.supply/opengraph-image",
    subtitle: "Curated presentation slides",
    tags: [TAGS.typography],
    url: "https://slides.supply/",
  },
  {
    title: "Squoosh",
    category: CATEGORIES.media,
    description:
      "Squoosh is the ultimate image optimizer that allows you to compress and compare images with different codecs in your browser.",
    tags: [TAGS.image],
    url: "https://squoosh.app/",
  },
  {
    title: "ssshape",
    author: "fffuel",
    category: CATEGORIES.media,
    description:
      "Free SVG blob shape generator that allows you to control the final shapes. Copy/export as SVG and use the blob-like shapes in your designs right away.",
    favicon: "https://fffuel.co/images/favicon/favicon.svg",
    ogImage: "https://fffuel.co/images/covers/ssshape.png",
    subtitle: "SVG Blob/Organic Shape Generator with Extra Controls",
    tags: [TAGS.shapes, TAGS.svg],
    url: "https://fffuel.co/ssshape/",
  },
  {
    title: "sssplatter",
    author: "fffuel",
    category: CATEGORIES.media,
    description:
      "A simple SVG shape generator for random shapes that are blob-like, but with more of a splattered/splash feel.",
    favicon: "https://fffuel.co/images/favicon/favicon.svg",
    ogImage: "https://fffuel.co/images/covers/sssplatter.png",
    subtitle: "generate SVG shapes that look splattered",
    tags: [TAGS.svg],
    url: "https://www.fffuel.co/sssplatter/",
  },
  {
    title: "SSSVG",
    author: "fffuel",
    category: CATEGORIES.media,
    description:
      "A visual & interactive SVG reference. Quickly look up how to define SVG shapes, transforms, masks, patterns, gradients, text and more.",
    favicon: "https://fffuel.co/images/favicon/favicon.svg",
    ogImage: "https://fffuel.co/images/covers/sssvg.png",
    subtitle: "An Interactive SVG Reference",
    tags: [TAGS.svg],
    url: "https://fffuel.co/sssvg/",
  },
  {
    title: "Storytale",
    category: CATEGORIES.media,
    description:
      "High-class web assets under simple subscription. Huge library of stylish assets that grows every week. You can get them all by yearly subscription and download any assets you want for commercial and personal projects.",
    ogImage: "https://storytale-public.b-cdn.net/static/assets/storytale-app/img/Open-Graph.png",
    tags: [TAGS.graphics],
    url: "https://storytale.io/browse/?isFree=true",
  },
  {
    title: "Streamline",
    category: CATEGORIES.media,
    description:
      "Download free, exclusive art and illustrations in multiple formats including vectors, SVG, and PNG. High-quality digital assets for your creative projects.",
    favicon: "https://www.streamlinehq.com/favicons/favicon.svg",
    ogImage: "https://framerusercontent.com/images/s57uVk1eoeFfyNafmGmCGbi5q4I.png",
    subtitle: "Exclusive Stock Illustrations",
    tags: [TAGS.illustration],
    url: "https://www.streamlinehq.com/illustrations",
  },
  {
    title: "Text to ASCII Art Generator (TAAG)",
    author: "patorjk",
    category: CATEGORIES.media,
    description:
      "An online text conversion tool for changing text into ASCII art pictures. The output can be used to decorate emails, online profiles, IMs, and more!",
    favicon: "https://patorjk.com/software/taag/candy.png",
    tags: [TAGS.ascii],
    url: "https://patorjk.com/software/taag/",
  },
  {
    title: "theSVG",
    category: CATEGORIES.media,
    description:
      "Search, copy, and ship 6,149+ brand SVG icons. Open-source library with npm, React, Vue, Svelte, CLI, CDN, and MCP server support.",
    subtitle: "6,149+ Free Brand SVG Icons for Developers and Designers",
    tags: [TAGS.image],
    url: "https://thesvg.org/",
  },
  {
    title: "Thiings",
    category: CATEGORIES.media,
    description:
      "Browse the Thiings collection: 10,000+ free 3D icons generated with AI. Download individual icons free for personal use, or get a lifetime commercial license for the whole collection.",
    ogImage: "https://www.thiings.co/meta-new.png",
    subtitle: "10,000+ Free AI-Generated 3D Icons",
    tags: [TAGS.illustration, TAGS["3D"]],
    url: "https://www.thiings.co/things",
  },
  {
    title: "TinEye",
    category: CATEGORIES.media,
    description:
      "Search billions of images with TinEye reverse image search and find where images appear online.",
    favicon: "https://tineye.com/assets/touch_icons/touch-icon-192x192.webp",
    subtitle: "Reverse Image Search",
    tags: [TAGS.image],
    url: "https://tineye.com/",
  },
  {
    title: "TopPNG",
    category: CATEGORIES.media,
    description:
      "TopPng Contain Millions of high quality free png images, icons, vectors and background images, enjoy with free download for all design needs.",
    subtitle: "Download Free PNG images, icons and backgrounds",
    tags: [TAGS.design, TAGS.image],
    url: "https://toppng.com/",
  },
  {
    title: "Transhumans",
    author: "Pablo Stanley",
    category: CATEGORIES.media,
    description:
      "Transhumans, a collection of black and white illustrations inspired by punk rock, transhumanism, and minimalist Japanese art. Created by Pablo Stanley, these open-source pieces are free to download and remix. Dive into the bold and imperfect brush strokes of this unique collection",
    favicon:
      "https://cdn.prod.website-files.com/64c73d04a946980a44765330/64c9625c3e90504925bc759b_favicon-1.png",
    ogImage:
      "https://cdn.prod.website-files.com/64c73d04a946980a44765330/64d9999d28972bb41c26f3ff_og-image.png",
    subtitle: "Open Source Punk Sci-Fi Art Collection",
    tags: [TAGS.illustration],
    url: "https://www.transhumans.xyz/",
  },
  {
    title: "uilogos",
    author: "Vijay Verma",
    category: CATEGORIES.media,
    description:
      "More than 25+ professionally designed logos and plugin to add dummy logos to your design and mockups.",
    favicon: "https://uilogos.co/favicon.ico",
    ogImage: "https://uilogos.co/preview.jpg",
    subtitle: "lorem ipsum for logos | free logo placeholder",
    tags: [TAGS.logo],
    url: "https://uilogos.co/",
  },
  {
    title: "unDraw",
    category: CATEGORIES.media,
    description:
      "Open-source illustrations for any idea you can imagine and create. Build beautiful websites, products and applications with your color, for free.",
    tags: [TAGS.image],
    url: "https://undraw.co/",
  },
  {
    title: "Unsplash",
    category: CATEGORIES.media,
    description:
      "Beautiful, free images and photos that you can download and use for any project. Better than any royalty free or stock photos.",
    subtitle: "Beautiful Free Images & Pictures",
    url: "https://unsplash.com/",
  },
  {
    title: "Varun Kumar",
    category: CATEGORIES.media,
    description:
      "Fueled by a love for design tutorials and a desire to share valuable resources with the creative community. Turning inspiration into education, one pixel at a time.",
    favicon: "https://public-files.gumroad.com/26c552b223afht07gewt06u9juav",
    ogImage: "https://public-files.gumroad.com/26c552b223afht07gewt06u9juav",
    url: "https://vroon.gumroad.com/",
  },
  {
    title: "Vecteezy",
    category: CATEGORIES.media,
    description:
      "Explore millions of royalty free vectors, images, stock photos and videos! Get the perfect background, graphic, clipart, picture or drawing for your design.",
    subtitle: "Download Free Vectors, Images, Photos & Videos",
    tags: [TAGS.design, TAGS.image],
    url: "https://www.vecteezy.com/",
  },
  {
    title: "vid2ascii",
    category: CATEGORIES.media,
    description: "Convert videos to ASCII.",
    tags: [TAGS.ascii, TAGS.video],
    url: "https://www.vid2ascii.com/",
  },
  {
    title: "Vidsplay",
    category: CATEGORIES.media,
    description: "Royalty Free Stock Video Footage Clips",
    favicon:
      "https://www.vidsplay.com/wp-content/uploads/2019/10/vidsplay-logo-without-text-300x300.png",
    ogImage:
      "https://www.vidsplay.com/wp-content/themes/vidsplay-v1.0/assets/images/vidsplay-logo.svg",
    tags: [TAGS.video],
    url: "https://www.vidsplay.com/",
  },
  {
    title: "Voicebox",
    category: CATEGORIES.media,
    description:
      "Near-perfect voice cloning with multiple TTS engines. Desktop app for Mac, Windows, and Linux. Multi-sample support, smart caching, local or remote inference.",
    subtitle: "Open Source Voice Cloning Desktop App",
    tags: [TAGS.audio],
    url: "https://voicebox.sh/",
  },
  {
    title: "wannathis.one",
    category: CATEGORIES.media,
    description:
      "High-quality mockups and 3d illustrations for digital products. Free and premium assets to help creators work faster and make projects standout.",
    subtitle: "High Quality Mockups and 3D Illustrations for Design Projects",
    tags: [TAGS.mockup],
    url: "https://wannathis.one/",
  },
  {
    title: "Webcam Text Overlay App",
    category: CATEGORIES.media,
    description:
      "This interactive web app transforms your webcam feed by overlaying customizable text on bright areas, encouraging creativity and mindfulness in real-time.",
    url: "https://text-over-video.figma.site/",
  },
  {
    title: "yoinks",
    author: "Pablo Stanley",
    category: CATEGORIES.media,
    description: "yoink any video from your terminal. no shady ads.",
    favicon: "./github.svg",
    ogImage: "https://raw.githubusercontent.com/pablostanley/yoinks/main/assets/home.png",
    tags: [TAGS.video],
    url: "https://github.com/pablostanley/yoinks",
  },
  {
    title: "yt-dlp/yt-dlp",
    category: CATEGORIES.media,
    description: "A feature-rich command-line audio/video downloader.",
    tags: [TAGS.audio, TAGS.video],
    url: "https://github.com/yt-dlp/yt-dlp",
  },
  {
    title: "YUZU",
    category: CATEGORIES.media,
    description: "i'm independent digital creator — welcome to my mockup store 🪴",
    favicon: "https://public-files.gumroad.com/nxonwfel0h0yqlm2yti3jexzx8yk",
    ogImage: "https://public-files.gumroad.com/nxonwfel0h0yqlm2yti3jexzx8yk",
    url: "https://yuzudigital.gumroad.com/",
  },
];
