export const TAGS = {
  agents: "agents",
  ai: "ai",
  animation: "animation",
  ascii: "ASCII",
  backend: "backend",
  builder: "builder",
  color: "color",
  crawler: "crawler",
  data: "data",
  "data-viz": "data-viz",
  design: "design",
  development: "development",
  education: "education",
  icon: "icon",
  image: "image",
  inspiration: "inspiration",
  job: "job",
  llm: "llm",
  "low-code": "low-code",
  map: "map",
  "open-source": "open-source",
  platform: "platform",
  rag: "rag",
  react: "react",
  scraper: "scraper",
  "self-hosted": "self-hosted",
  tool: "tool",
  typography: "typography",
  ui: "ui",
  "ui-component": "ui-component",
} as const;

export type TagType = keyof typeof TAGS;
