import { Resource } from "@/types";

import { CATEGORIES } from "./categories";
import { TAGS } from "./tags";

export const uiLinks: Resource[] = [
  {
    title: "9ui",
    author: "Bora Baloglu",
    category: CATEGORIES.ui,
    description: "Beautiful, customizable components built with Base UI and Tailwind CSS.",
    favicon: "https://www.9ui.dev/apple-touch-icon.png",
    ogImage: "https://www.9ui.dev/og.jpg",
    tags: [TAGS["ui-component"]],
    url: "https://www.9ui.dev/",
  },
  {
    title: "21st Dev",
    category: CATEGORIES.ui,
    description:
      "Explore, copy, and remix thousands of high-quality React components published to the 21st.dev Community by designers and developers.",
    tags: [TAGS.react],
    url: "https://21st.dev/",
  },
  {
    title: "Aceternity UI",
    category: CATEGORIES.ui,
    description:
      "Copy-paste beautiful UI components built with React, Next.js, Tailwind CSS, and Framer Motion. 200+ free components, blocks, and templates.",
    tags: [TAGS["ui-component"]],
    url: "https://ui.aceternity.com/",
  },
  {
    title: "AI Elements",
    category: CATEGORIES.ui,
    description:
      "A component library and custom registry built on top of shadcn/ui to help you build AI-native applications faster.",
    favicon: "https://elements.ai-sdk.dev/favicon.ico",
    ogImage:
      "https://raw.githubusercontent.com/vercel/ai-elements/main/apps/docs/app/opengraph-image.png",
    tags: [TAGS["ui-component"]],
    url: "https://elements.ai-sdk.dev/",
  },
  {
    title: "All ShadCN",
    category: CATEGORIES.ui,
    description:
      "Explore All Shadcn, your go-to hub for premium & free Shadcn Themes, Components, Blocks, and Tools.",
    ogImage:
      "https://cdn.allshadcn.com/as-assets/og-images/static-pages/all-shadcn---300+-shadcn-templates,-components,-blocks-&-tools.png",
    subtitle: "300+ Shadcn Templates, Components, Blocks & Tools",
    tags: [TAGS["ui-component"]],
    url: "https://allshadcn.com/",
  },
  {
    title: "Animate UI",
    category: CATEGORIES.ui,
    description:
      "Fully animated, open-source component distribution built with React, TypeScript, Tailwind CSS, Motion and Shadcn CLI. Browse a list of components you can install, modify, and use in your projects.",
    subtitle: "Animated React Components",
    tags: [TAGS["ui-component"]],
    url: "https://animate-ui.com/",
  },
  {
    title: "Ark UI",
    category: CATEGORIES.ui,
    description:
      "A headless UI library with over 45+ components designed to build reusable, scalable Design Systems that works for a wide range of JS frameworks.",
    favicon: "https://ark-ui.com/icon.svg?3e91f991fe6d39a3",
    tags: [TAGS["ui-component"]],
    url: "https://ark-ui.com/",
  },
  {
    title: "BagUI",
    author: "Anelka Bagalane",
    category: CATEGORIES.ui,
    description:
      "BagUI is an open-source shadcn/ui registry with production-ready components, blocks, templates, and animations for React, Next.js, and Tailwind CSS. Copy, customize, and build faster.",
    favicon: "https://www.bagui.pro/faviconblack.png",
    ogImage: "https://www.bagui.pro/og-image.png",
    subtitle: "Open Source shadcn/ui Components & Blocks",
    tags: [TAGS["ui-component"]],
    url: "https://www.bagui.pro/",
  },
  {
    title: "beUI",
    category: CATEGORIES.ui,
    description:
      "The motion toolkit for React and Next.js. Free, open-source, shadcn-compatible components built on Framer Motion and Tailwind CSS. Copy-paste the source or install with the shadcn CLI.",
    subtitle: "The motion toolkit for React & Next.js",
    tags: [TAGS.animation, TAGS.react, TAGS["ui-component"]],
    url: "https://beui.dev/",
  },
  {
    title: "Bklit UI",
    category: CATEGORIES.ui,
    description:
      "Bklit UI is a component library built on top of shadcn/ui to help you build charts and data visualizations more easily.",
    subtitle: "Charts & Data Visualization Components",
    tags: [TAGS["ui-component"]],
    url: "https://bklit.com/",
  },
  {
    title: "Blocks",
    author: "Ali Imam",
    category: CATEGORIES.ui,
    favicon: "https://www.aliimam.in/apple-touch-icon.png",
    ogImage: "https://www.aliimam.in/opengraph-image.jpg",
    tags: [TAGS.ui],
    url: "https://old.aliimam.in/blocks",
  },
  {
    title: "Blossom Carousel",
    category: CATEGORIES.ui,
    description: "Enhance native scrolling with dragging instead of replacing it.",
    tags: [TAGS["ui-component"]],
    url: "https://www.blossom-carousel.com/",
  },
  {
    title: "boneyard",
    category: CATEGORIES.ui,
    description:
      "Pixel-perfect skeleton loading screens auto-extracted from your real DOM. Zero configuration, zero layout shift.",
    subtitle: "skeleton screens for your UI",
    tags: [TAGS["ui-component"]],
    url: "https://boneyard.vercel.app/",
  },
  {
    title: "Brand UI",
    category: CATEGORIES.ui,
    description:
      "Documentation for Primer Brand - GitHub's design system for brand-led marketing experiences",
    favicon: "https://primer.style/icon.svg",
    ogImage: "https://primer.style/brand/og-image.png",
    subtitle: "Primer",
    tags: [TAGS["ui-component"]],
    url: "https://primer.style/brand/",
  },
  {
    title: "Bundui",
    category: CATEGORIES.ui,
    description:
      "Tailwind is a carefully curated collection of 200+ handcrafted UI components built with CSS, React, and shadcn/ui.",
    favicon: "https://bundui.io/logo.svg",
    ogImage: "https://bundui.io/og-image.png",
    subtitle: "Tailwind CSS & shadcn/ui components, UI blocks, examples and more.",
    tags: [TAGS["ui-component"]],
    url: "https://bundui.io/",
  },
  {
    title: "BuouUI",
    author: "buou",
    category: CATEGORIES.ui,
    description:
      "This is a beautiful UI library with components, sections, landing page, and templates using Tailwind CSS.",
    favicon: "https://buouui.com/apple-touch-icon.png",
    ogImage: "https://buouui.com/og.jpg",
    tags: [TAGS["ui-component"]],
    url: "https://buouui.com/",
  },
  {
    title: "Canvas UI",
    author: "David Haz",
    category: CATEGORIES.ui,
    description:
      "An open source component library of creative html-in-canvas and WebGL effects for React, Solid, Preact, Vue, Svelte, and vanilla JS. Creative effects running over live HTML.",
    favicon: "https://canvasui.dev/favicon.svg",
    ogImage: "https://canvasui.dev/og.png",
    subtitle: "Creative Canvas and WebGL Component Library",
    tags: [TAGS.webgl, TAGS["ui-component"]],
    url: "https://canvasui.dev/",
  },
  {
    title: "Clonify",
    category: CATEGORIES.ui,
    description:
      "Speed up your site builds with 1K+ ready-made Framer and Figma assets — sections, wireframes, templates, and UI kits all in one place.",
    subtitle: "Your All-in-One Framer & Figma UI Library",
    tags: [TAGS["ui-component"]],
    url: "https://clonify.io/",
  },
  {
    title: "CodeFronts",
    author: "CodeFronts",
    category: CATEGORIES.ui,
    description:
      "Browse hundreds of free CSS components, interactive generators, animations, layouts and frontend tools. Copy-paste ready with live demos. No sign-up, no paywall.",
    favicon: "https://codefronts.com/favicon.svg",
    ogImage: "https://codefronts.com/og-default.png",
    subtitle: "Free CSS Components, Generators & Frontend Tools",
    tags: [TAGS["ui-component"]],
    url: "https://codefronts.com/",
  },
  {
    title: "comimi",
    category: CATEGORIES.ui,
    description:
      "comimi is a TypeScript/JavaScript library that allows you to embed a manga viewer into websites.",
    tags: [TAGS.javascript, TAGS.typescript],
    url: "https://yui540.com/comimi",
  },
  {
    title: "Componentry",
    author: "Harsh Jadhav",
    category: CATEGORIES.ui,
    className: "bg-foreground border-paper",
    description:
      "Beautiful, animated React UI components with styling and motion already handled. Built with Tailwind CSS, TypeScript, and Framer Motion.",
    favicon: "https://componentry.dev/icon.svg",
    ogImage: "https://componentry.dev/opengraph-image.png",
    subtitle: "Beautiful Animated UI Components for React",
    tags: [TAGS["ui-component"]],
    url: "https://componentry.dev/",
  },
  {
    title: "Components – Chánh Đại",
    author: "Chánh Đại",
    category: CATEGORIES.ui,
    description: "Pixel-perfect, uniquely crafted.",
    tags: [TAGS.animation, TAGS["ui-component"]],
    url: "https://chanhdai.com/components",
  },
  {
    title: "Components",
    author: "Ali Imam",
    category: CATEGORIES.ui,
    favicon: "https://www.aliimam.in/apple-touch-icon.png",
    ogImage: "https://www.aliimam.in/opengraph-image.jpg",
    tags: [TAGS["ui-component"]],
    url: "https://old.aliimam.in/docs/components",
  },
  {
    title: "coss ui",
    category: CATEGORIES.ui,
    description: "Built for developers and AI.",
    favicon: "https://coss.com/ui/favicon.ico",
    ogImage: "https://coss.com/ui/opengraph-image.png",
    subtitle: "A new, modern UI component library built on top of Base UI",
    tags: [TAGS["ui-component"]],
    url: "https://coss.com/ui",
  },
  {
    title: "Cover Flow",
    category: CATEGORIES.ui,
    description: "iOS-like Cover Flow for React.",
    tags: [TAGS["ui-component"]],
    url: "https://coverflow.ashishgogula.in/",
  },
  {
    title: "CSS Button Library",
    author: "Csaba Kissi",
    category: CATEGORIES.ui,
    description:
      "A library of 99 buttons with pure-CSS hover effects — no JavaScript, no dependencies. Click any button to view and copy its CSS.",
    favicon: "https://animatedbuttons.colorion.co/favicon.svg",
    ogImage: "https://animatedbuttons.colorion.co/og.png",
    subtitle: "99 pure-CSS hover effects, free to copy",
    tags: [TAGS.animation, TAGS.css, TAGS["ui-component"]],
    url: "https://animatedbuttons.colorion.co/",
  },
  {
    title: "CSS Buttons",
    category: CATEGORIES.ui,
    description:
      "Explore Cssbuttons.io for a diverse collection of over 100 unique button styles. Get the code you need to enhance your web projects with stylish, functional buttons. Elevate your design with ease and creativity!",
    favicon: "https://cssbuttons.io/favicon-96x96.png",
    ogImage:
      "https://imagedelivery.net/KMb5EadhEKC1gAE0LkjL1g/cb814b9d-45f8-46f5-3108-91e511990200/public",
    tags: [TAGS["ui-component"]],
    url: "https://cssbuttons.io/",
  },
  {
    title: "CSS Loader Library",
    author: "Csaba Kissi",
    category: CATEGORIES.ui,
    description:
      "A library of 99 loading spinners built with pure CSS. Click any loader to copy its CSS — no JavaScript, no dependencies, MIT licensed.",
    favicon: "https://cssloaders.colorion.co/favicon.svg",
    ogImage: "https://cssloaders.colorion.co/og-image.png",
    subtitle: "99 pure-CSS loaders, free to copy",
    tags: [TAGS.animation, TAGS.css, TAGS["ui-component"]],
    url: "https://css-loaders.colorion.co/",
  },
  {
    title: "CSS Text Effects",
    author: "Csaba Kissi",
    category: CATEGORIES.ui,
    description:
      "A library of 75 animated text effects built with pure CSS — gradient, glitch, typewriter, neon, liquid fill and more. Click any effect to copy its CSS. No JavaScript, no dependencies, MIT licensed.",
    favicon: "https://text-effects.colorion.co/favicon.svg",
    ogImage: "https://text-effects.colorion.co/og-image.png",
    subtitle: "75 pure-CSS text animations, free to copy",
    tags: [TAGS.animation, TAGS.css, TAGS["ui-component"]],
    url: "https://text-effects.colorion.co/",
  },
  {
    title: "CSS Toggle Library",
    author: "Csaba Kissi",
    category: CATEGORIES.ui,
    description:
      "A library of pure-CSS toggles, switches, checkboxes and radios — no JavaScript, no dependencies. Click any toggle to view and copy its self-contained CSS.",
    favicon: "https://toggles.colorion.co/favicon.svg",
    ogImage: "https://toggles.colorion.co/og-image.png",
    subtitle: "Pure-CSS Switches & Checkboxes",
    tags: [TAGS.animation, TAGS.css, TAGS["ui-component"]],
    url: "https://toggles.colorion.co/",
  },
  {
    title: "CSS Tooltip Library",
    author: "Csaba Kissi",
    category: CATEGORIES.ui,
    description:
      "A library of pure-CSS tooltips in 8 directions with fade and slide reveals — no JavaScript, no dependencies. Click any tooltip to view and copy its CSS.",
    subtitle: "Pure-CSS ::after tooltips, free to copy",
    tags: [TAGS.animation, TAGS.css, TAGS["ui-component"]],
    url: "https://tooltips.colorion.co/",
  },
  {
    title: "CuiCui",
    author: "Damien Schneider",
    category: CATEGORIES.ui,
    description: "A collection of UI components for advanced applications.",
    tags: [TAGS["ui-component"]],
    url: "https://cuicui.day/",
  },
  {
    title: "Cult UI",
    category: CATEGORIES.ui,
    description:
      "Open-source Shadcn UI components, animated blocks, and full templates you can copy-paste into any TypeScript/Next.js project.",
    tags: [TAGS["ui-component"]],
    url: "https://www.cult-ui.com/",
  },
  {
    title: "daisyUI",
    category: CATEGORIES.ui,
    description:
      "Tailwind CSS component library by daisyUI. Build faster with semantic components, built-in themes, and reusable UI blocks.",
    favicon: "https://img.daisyui.com/images/daisyui/mark.svg",
    ogImage: "https://img.daisyui.com/images/default.webp",
    subtitle: "Tailwind CSS Component Library",
    tags: [TAGS["ui-component"]],
    url: "https://daisyui.com/",
  },
  {
    title: "devl.dev",
    category: CATEGORIES.ui,
    description:
      "Two years of UI experiments. 159+ components built on coss-ui, all on the shadcn registry. Press 'c' on any design to copy the source.",
    subtitle: "UI experiments built on coss-ui",
    tags: [TAGS["ui-component"]],
    url: "https://www.devl.dev/",
  },
  {
    title: "Dot Matrix",
    category: CATEGORIES.ui,
    description:
      "React component library of dot matrix loaders—expressive loading primitives you install via the shadcn registry and own as local code.",
    tags: [TAGS["ui-component"]],
    url: "https://dotmatrix.zzzzshawn.cloud/",
  },
  {
    title: "Efferd",
    category: CATEGORIES.ui,
    description:
      "Save hours of design time with clean, ready-to-use shadcn blocks that just work — modern, responsive, and built for speed.",
    subtitle: "Beautiful Shadcn blocks for Busy & Smart devs.",
    tags: [TAGS["ui-component"]],
    url: "https://efferd.com/",
  },
  {
    title: "ElevenLabs UI",
    author: "ElevenLabs",
    category: CATEGORIES.ui,
    description:
      "A collection of Open Source agent and audio components that you can customize and extend.",
    favicon: "https://ui.elevenlabs.io/apple-touch-icon.png",
    ogImage: "https://ui.elevenlabs.io/opengraph-image.png",
    tags: [TAGS.audio, TAGS["ui-component"]],
    url: "https://ui.elevenlabs.io/",
  },
  {
    title: "Fancy Components",
    author: "Daniel Petho",
    category: CATEGORIES.ui,
    description:
      "Ready to use, fancy React components to make the web fun again. Free & Open Source.",
    ogImage: "https://fancycomponents.dev/og.jpg",
    tags: [TAGS["ui-component"]],
    url: "https://www.fancycomponents.dev/",
  },
  {
    title: "Fluid Functionalism.",
    category: CATEGORIES.ui,
    description: "Open Source UI components created by @micka_design",
    tags: [TAGS["ui-component"]],
    url: "https://www.fluidfunctionalism.com/",
  },
  {
    title: "Footer",
    category: CATEGORIES.ui,
    description:
      "Footer is a curated gallery of the top website footer inspiration on earth. Find the footers you need and sort by type and style.",
    subtitle: "The only footer gallery on earth.",
    tags: [TAGS["ui-component"]],
    url: "https://www.footer.design/",
  },
  {
    title: "ForgeUI",
    category: CATEGORIES.ui,
    description:
      "Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.",
    tags: [TAGS["ui-component"]],
    url: "https://forgeui.in/",
  },
  {
    title: "FormSCN",
    category: CATEGORIES.ui,
    description:
      "Visual form builder for shadcn/ui and React. Build production-ready forms with React Hook Form or TanStack Form, add Better Auth in one click, and export clean TypeScript code for Next.js, Remix, or Vite.",
    subtitle: "shadcn/ui Form Builder with Better Auth Integration",
    tags: [TAGS["ui-component"]],
    url: "https://www.formscn.space/",
  },
  {
    title: "framecn",
    category: CATEGORIES.ui,
    description:
      "A collection of beautifully designed, and customizable video components. Built on Editframe. Works with shadcn/ui.",
    subtitle: "Beautiful videos, made simple",
    tags: [TAGS["ui-component"]],
    url: "https://www.framecn.dev/",
  },
  {
    title: "Frimousse",
    category: CATEGORIES.ui,
    description:
      "Open-source, lightweight, unstyled, and composable emoji picker for React—originally created for Liveblocks Comments. Styles can be applied with CSS, Tailwind CSS, CSS-in-JS, and more.",
    tags: [TAGS["ui-component"]],
    url: "https://frimousse.liveblocks.io/",
  },
  {
    title: "Gamification UI Kit by Trophy",
    category: CATEGORIES.ui,
    description:
      "Trophy's Gamification UI Kit is an open-source library of gamification UI components built on shadcn/ui and Tailwind CSS. Drop-in React components for streaks, achievements, leaderboards, points, and more — ready to copy and customize.",
    tags: [TAGS["ui-component"]],
    url: "https://ui.trophy.so/",
  },
  {
    title: "gooey-toast",
    category: CATEGORIES.ui,
    description:
      "Morphing toast notifications for React. Organic blob animations, promise tracking, and full customization out of the box.",
    favicon: "https://goey-toast.vercel.app/apple-touch-icon.png",
    ogImage: "https://goey-toast.vercel.app/og-image.png",
    subtitle: "Morphing toast notifications for React",
    tags: [TAGS["ui-component"]],
    url: "https://goey-toast.vercel.app/",
  },
  {
    title: "Gravity UI",
    category: CATEGORIES.ui,
    description: "Build modern interfaces with the Gravity design system and libraries",
    ogImage: "https://gravity-ui.com/index-social.png",
    tags: [TAGS["ui-component"]],
    url: "https://gravity-ui.com/",
  },
  {
    title: "HTMLrev",
    category: CATEGORIES.ui,
    description:
      "Free HTML CSS templates and themes for websites, landing pages, blogs, portfolios, ecommerce and admin dashboards.",
    tags: [TAGS["ui-component"]],
    url: "https://htmlrev.com/",
  },
  {
    title: "HyperUI",
    category: CATEGORIES.ui,
    description:
      "Free, open-source Tailwind CSS components for modern web development. Copy-paste ready components to build beautiful, responsive websites faster.",
    favicon: "https://www.hyperui.dev/favicon.ico",
    ogImage: "https://hyperui.dev/og.jpg",
    subtitle: "Free Tailwind CSS Components",
    tags: [TAGS["ui-component"]],
    url: "https://hyperui.dev/",
  },
  {
    title: "Indie UI",
    category: CATEGORIES.ui,
    description:
      "Make your website stand out with minimal effort. Built with Reactjs, shadcn and Framer Motion for animation.",
    favicon: "https://ui.indie-starter.dev/favicon.ico",
    ogImage: "https://ui.indie-starter.dev/opengraph-image.jpg?2c560e418071e952",
    tags: [TAGS["ui-component"]],
    url: "https://ui.indie-starter.dev/",
  },
  {
    title: "Intent UI",
    category: CATEGORIES.ui,
    description:
      "Copy and paste accessible React components built on React Aria and Tailwind CSS. 87+ production-ready components for Next.js and Laravel.",
    tags: [TAGS["ui-component"]],
    url: "https://intentui.com/",
  },
  {
    title: "Joly UI",
    author: "johuniq",
    category: CATEGORIES.ui,
    description:
      "50+ free, open-source React components built on shadcn/ui & Radix. Copy-paste ready for Next.js, TypeScript & Tailwind CSS.",
    favicon: "https://jolyui.dev/icon.png",
    ogImage: "https://jolyui.dev/opengraph-image.png",
    subtitle: "50+ Free shadcn/ui Components for React & Next.js",
    tags: [TAGS["ui-component"]],
    url: "https://www.jolyui.dev/",
  },
  {
    title: "junwen-k/ui-x",
    author: "junwen-k",
    category: CATEGORIES.ui,
    className: "bg-foreground border-paper",
    description:
      "Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.",
    favicon: "https://ui-x.junwen-k.dev/favicon.svg",
    ogImage: "https://ui-x.junwen-k.dev/og.jpg",
    tags: [TAGS["ui-component"]],
    url: "https://ui-x.junwen-k.dev/",
  },
  {
    title: "JustGage",
    author: "JustGage Team",
    category: CATEGORIES.ui,
    description:
      "Modern SVG gauge library with zero dependencies. Create beautiful, animated dashboard gauges with ease.",
    favicon: "https://raw.githubusercontent.com/toorshia/justgage/master/docs/public/logo.png",
    subtitle: "Modern SVG Gauges",
    tags: [TAGS["ui-component"]],
    url: "https://toorshia.github.io/justgage/",
  },
  {
    title: "Kibo UI",
    category: CATEGORIES.ui,
    description:
      "Kibo UI is a custom registry of composable, accessible and open source components designed for use with shadcn/ui.",
    favicon: "https://www.kibo-ui.com/apple-icon.png?apple-icon.78308315.png",
    ogImage: "https://www.kibo-ui.com/opengraph-image.jpg?opengraph-image.408bd8df.jpg",
    tags: [TAGS["ui-component"]],
    url: "https://www.kibo-ui.com/",
  },
  {
    title: "Kokonut UI",
    category: CATEGORIES.ui,
    description:
      "Collection of 100+ stunning UI components free and open source built with Next.js, React, Tailwind CSS, and Motion.",
    subtitle: "Open Source Components",
    tags: [TAGS["ui-component"]],
    url: "https://kokonutui.com/",
  },
  {
    title: "Lightswind UI",
    category: CATEGORIES.ui,
    description:
      "Accelerate your workflow with Lightswind UI. A library of 151+ high-performance,  accessible, and beautifully animated React components and UI kits crafted for Modern Developers.",
    subtitle: "Beautifully Animated React Components & Modern UI Kits",
    url: "https://lightswind.com/",
  },
  {
    title: "Loading UI",
    category: CATEGORIES.ui,
    description:
      "Free and open source CSS and React loaders, spinners, and animations to create polished, accessible loading states for modern web apps.",
    subtitle: "Spinners, loaders, and loading animations for the web",
    tags: [TAGS["ui-component"]],
    url: "https://loading-ui.com/",
  },
  {
    title: "Lukacho UI",
    category: CATEGORIES.ui,
    description: "Animated UI component Collection made with Next.js | TailwindCSS | Framer Motion",
    tags: [TAGS["ui-component"]],
    url: "https://ui.lukacho.com/",
  },
  {
    title: "Mage UI",
    category: CATEGORIES.ui,
    description:
      "Hand-crafted animated components that you can copy and paste into your apps. Free & Open Source.",
    tags: [TAGS["ui-component"]],
    url: "https://www.mageui.in/",
  },
  {
    title: "Magic UI",
    category: CATEGORIES.ui,
    description: "Beautiful UI components and templates to make your landing page look stunning.",
    tags: [TAGS["ui-component"]],
    url: "https://magicui.design/",
  },
  {
    title: "Monoco",
    author: "Monokai",
    category: CATEGORIES.ui,
    description:
      "Monoco is a tiny JavaScript library that adds squircles (smooth corners) and other corner types to html elements.",
    favicon: "https://somonoco.com/favicon.png",
    ogImage: "https://somonoco.com/featured-image.jpg",
    subtitle: "smooth squircle corners for HTML elements",
    tags: [TAGS["ui-component"]],
    url: "https://somonoco.com/",
  },
  {
    title: "Morphin",
    author: "Morphin",
    category: CATEGORIES.ui,
    className: "bg-foreground border-paper",
    description:
      "Build premium React interfaces with production-ready animated components, micro-interactions and motion UI patterns. Ship polished UI 10x faster.",
    favicon: "https://morphin.dev/logo.svg",
    ogImage: "https://morphin.dev/twitter-image?eaa549bb27ece1c0",
    subtitle: "Premium Animated React Components & Motion UI Library",
    tags: [TAGS["ui-component"]],
    url: "https://morphin.dev/",
  },
  {
    title: "Motion-Primitives",
    category: CATEGORIES.ui,
    description:
      "Motion-Primitives is an open-source UI kit to make beautiful, animated interfaces, faster. Built for React, Next.js, and Tailwind CSS.",
    subtitle: "UI kit to make beautiful, animated interfaces, faster.",
    tags: [TAGS.animation, TAGS["ui-component"]],
    url: "https://motion-primitives.com/",
  },
  {
    title: "MynaUI",
    author: "Praveen Juge",
    category: CATEGORIES.ui,
    description:
      "MynaUI is a comprehensive design system and UI kit that lets you customize and extend designs.",
    favicon: "https://mynaui.com/icon.svg",
    ogImage: "https://mosaic.praveenjuge.com/use?url=https://mynaui.com/",
    subtitle: "Made with TailwindCSS, shadcn/ui, Radix UI and Figma.",
    tags: [TAGS.designSystem, TAGS.icons, TAGS["ui-component"]],
    url: "https://mynaui.com/",
  },
  {
    title: "Neobrutalism components",
    category: CATEGORIES.ui,
    description: "A collection of neobrutalism-styled components based on shadcn/ui.",
    subtitle: "Start making neobrutalism layouts today",
    tags: [TAGS["ui-component"]],
    url: "https://www.neobrutalism.dev/",
  },
  {
    title: "Nova UI",
    category: CATEGORIES.ui,
    description:
      "Nova UI is a complete solution for Framer & Figma, offering all the resources needed from concept to launch. Packed with a UI kit, templates, design systems, components, and custom code, it's the ultimate toolkit for creating and monetizing your websites.",
    subtitle: "Framer UI Kit & Design System",
    tags: [TAGS["ui-component"]],
    url: "https://novaui.design/",
  },
  {
    title: "Originkit",
    category: CATEGORIES.ui,
    description:
      "The largest free animated component library for building modern websites. Copy code, use in Framer, or connect through MCP.",
    subtitle: "Free Animated component library for modern websites",
    tags: [TAGS["ui-component"]],
    url: "https://www.originkit.dev/",
  },
  {
    title: "Pages",
    author: "Ali Imam",
    category: CATEGORIES.ui,
    favicon: "https://www.aliimam.in/apple-touch-icon.png",
    ogImage: "https://www.aliimam.in/opengraph-image.jpg",
    tags: [TAGS.ui],
    url: "https://old.aliimam.in/pages",
  },
  {
    title: "Park UI",
    category: CATEGORIES.ui,
    description:
      "Beautifully designed components built with Ark UI and Panda CSS that work with a variety of JS frameworks.",
    tags: [TAGS["ui-component"]],
    url: "https://park-ui.com/",
  },
  {
    title: "phantom-ui",
    category: CATEGORIES.ui,
    description: "Structure-aware skeleton loader. One Web Component. Every framework.",
    favicon: "https://aejkatappaja.github.io/phantom-ui/favicon.svg",
    tags: [TAGS["ui-component"]],
    url: "https://aejkatappaja.github.io/phantom-ui/",
  },
  {
    title: "Plate rich-text editor",
    category: CATEGORIES.ui,
    description:
      "A set of beautifully-designed, customizable plugins and components to help you build your rich-text editor. Open Source.",
    tags: [TAGS["ui-component"]],
    url: "https://platejs.org/",
  },
  {
    title: "Prime UI",
    author: "Pixel Point",
    category: CATEGORIES.ui,
    className: "bg-foreground border-paper",
    description:
      "Prime UI is the missing foundation for AI-generated websites. Go from sitemaps and wireframes to production-ready Next.js and Tailwind CSS code in minutes.",
    favicon: "https://primeui.com/logomark-dark.svg",
    ogImage: "https://primeui.com/social-previews/index.jpg",
    subtitle: "Build sites fast. Fear no code.",
    tags: [TAGS["ui-component"]],
    url: "https://primeui.com/",
  },
  {
    title: "Product UI",
    category: CATEGORIES.ui,
    description:
      "Primer product UI is a set of guidelines, principles, and patterns for designing and building UI at GitHub.",
    favicon: "https://primer.style/icon.svg",
    subtitle: "Primer",
    tags: [TAGS["ui-component"]],
    url: "https://primer.style/product/",
  },
  {
    title: "React Aria",
    category: CATEGORIES.ui,
    description: "Craft world-class accessible components with custom styles.",
    favicon: "https://react-aria.adobe.com/server/react-aria-favicon.0d52b4c6.svg",
    ogImage: "https://react-aria.adobe.com/server/ReactAriaOpenGraph.c58014f0.webp",
    tags: [TAGS["ui-component"]],
    url: "https://react-aria.adobe.com/",
  },
  {
    title: "React Bits",
    category: CATEGORIES.ui,
    description:
      "An open source collection of high quality, animated, interactive & fully customizable React components for building stunning, memorable user interfaces.",
    tags: [TAGS["ui-component"]],
    url: "https://www.reactbits.dev/",
  },
  {
    title: "ReUI",
    author: "ReUI",
    category: CATEGORIES.ui,
    description:
      "Free Shadcn UI components and pro blocks for React and Tailwind CSS. Hand-crafted icons, templates, and a hosted MCP server so coding agents build with the shadcn CLI.",
    favicon: "https://reui.io/favicon.ico",
    ogImage:
      "https://reui.io/og?title=Free%20Shadcn%20UI%20Components%2C%20Blocks%2C%20Icons%2C%20Templates%20%26%20MCP&description=Free%20Shadcn%20UI%20components%20and%20pro%20blocks%20for%20React%20and%20Tailwind%20CSS.%20Hand-crafted%20icons%2C%20templates%2C%20and%20a%20hosted%20MCP%20server%20so%20coding%20agents%20build%20with%20the%20shadcn%20CLI.&v=dpl_7SoDQLxB1vnarVpa5BSr3NUxi4T8",
    subtitle: "Free Shadcn UI Components, Blocks, Icons, Templates & MCP",
    tags: [TAGS["ui-component"]],
    url: "https://reui.io/",
  },
  {
    title: "SATIS UI",
    category: CATEGORIES.ui,
    description:
      "An evolving collection of production-ready components built for the shadcn/ui ecosystem. Supercharge your projects with fluid animations and modern best practices.",
    subtitle: "Beautifully Engineered Components for shadcn/ui",
    tags: [TAGS["ui-component"]],
    url: "https://satisui.xyz/",
  },
  {
    title: "Scrollbar",
    category: CATEGORIES.ui,
    description: "Simple CSS scrollbar editor.",
    favicon: "https://scrollbar.app/apple-touch-icon.png",
    ogImage: "https://www.scrollbar.app/scrollbar_cover.png",
    tags: [TAGS["ui-component"]],
    url: "https://scrollbar.app/",
  },
  {
    title: "Shadcn Blocks",
    author: "Ephraim Duncan",
    category: CATEGORIES.ui,
    description:
      "Customize theme for shadcn/ui with tweakcn's interactive editor. Supports Tailwind CSS v4, Shadcn UI, and custom styles. Modify properties, preview changes, and get the code in real time.",
    ogImage: "https://blocks.so/opengraph-image.png",
    subtitle: "60+ Free shadcn/ui Components for React | blocks.so - shadcn/ui blocks",
    tags: [TAGS["ui-component"]],
    url: "https://blocks.so/",
  },
  {
    title: "Shadcnblocks",
    category: CATEGORIES.ui,
    description:
      "Discover hundreds of extra shadcn/ui blocks and Shadcn UI components. Shadcnblocks is a premium component library built with Shadcn UI, React & Tailwind.",
    favicon: "https://www.shadcnblocks.com/favicon/apple-touch-icon.png",
    ogImage: "https://cdn.shadcnblocks.com/shadcnblocks/images/og/og-default.png",
    subtitle: "shadcn/ui blocks & components",
    tags: [TAGS["ui-component"]],
    url: "https://www.shadcnblocks.com/",
  },
  {
    title: "Shadcnexamples",
    category: CATEGORIES.ui,
    description:
      "Shadcn UI examples, components, and blocks. Built with Tailwind CSS, Shadcn/ui, Next.js, React, Vue.js. Typescript compatible.",
    favicon: "https://shadcnexamples.com/logo.png",
    ogImage: "https://shadcnexamples.com/preview.png",
    subtitle: "Shadcn UI Components and Blocks",
    tags: [TAGS["ui-component"]],
    url: "https://shadcnexamples.com/",
  },
  {
    title: "ShadcnStore",
    author: "ShadcnStore",
    category: CATEGORIES.ui,
    description:
      "Build faster with production-ready Shadcn UI blocks and components. Copy-paste React components built with Tailwind CSS. Perfect for Next.js, Vite, and modern web applications. Start building beautiful interfaces today.",
    favicon: "https://shadcnstore.com/docs/logo.svg",
    ogImage: "https://assets.shadcnstore.com/shadcnstore.com/brand/og-image.2400w.19d03d.png",
    subtitle: "Premium Shadcn UI Blocks & Components for Modern Web Apps",
    tags: [TAGS["ui-component"]],
    url: "https://shadcnstore.com",
  },
  {
    title: "Shadcn UI Blocks",
    category: CATEGORIES.ui,
    description:
      "Explore a curated collection of customized Shadcn UI blocks and components. Preview, customize, and copy ready-to-use code snippets to streamline your web development workflow. Perfect for creating responsive, high-quality Shadcn UI designs with ease.",
    favicon: "https://www.shadcnui-blocks.com/images/android-chrome-192x192.png",
    ogImage: "https://www.shadcnui-blocks.com/images/og-image.png",
    subtitle: "Customized Shadcn UI Blocks & Components | Preview & Copy",
    tags: [TAGS["ui-component"]],
    url: "https://www.shadcnui-blocks.com/",
  },
  {
    title: "Shoogle",
    category: CATEGORIES.ui,
    description: "Search shadcn components.",
    tags: [TAGS["ui-component"]],
    url: "https://shoogle.dev/",
  },
  {
    title: "Sileo",
    category: CATEGORIES.ui,
    description:
      "A tiny, beautiful, physics-based toast component for React. SVG morphing and spring animations.",
    tags: [TAGS["ui-component"]],
    url: "https://sileo.aaryan.design/",
  },
  {
    title: "Skiper UI",
    author: "Gxuri",
    category: CATEGORIES.ui,
    description:
      "Brand new uncommon components for your Next.js project. Use with ease through shadcn CLI 3.0, featuring fast-growing components and collections that are easy to edit and use.",
    favicon: "https://skiper-ui.com/logos/logo.svg",
    ogImage: "https://skiper-ui.com/og-main.png",
    subtitle: "Un-common Components for shadcn/ui",
    tags: [TAGS["ui-component"]],
    url: "https://skiper-ui.com/",
  },
  {
    title: "SmolCSS",
    author: "Stephanie Eckles",
    category: CATEGORIES.ui,
    description:
      "Minimal snippets for modern CSS layouts and components, created by Stephanie Eckles of ModernCSS.dev",
    tags: [TAGS["ui-component"]],
    url: "https://smolcss.dev/",
  },
  {
    title: "SmoothUI",
    category: CATEGORIES.ui,
    description:
      "Animated React components with smooth Motion animations. Drop-in shadcn/ui compatible, fully customizable with Tailwind CSS.",
    favicon: "https://smoothui.dev/logomark-smoothui.svg",
    ogImage: "https://smoothui.dev/og-optimized.webp",
    subtitle: "Animated React Components for shadcn/ui | Motion & Tailwind",
    tags: [TAGS["ui-component"]],
    url: "https://smoothui.dev/",
  },
  {
    title: "Spectrum UI",
    category: CATEGORIES.ui,
    description:
      "Copy-paste beautiful UI components built with React, Next.js, Tailwind CSS, and shadcn/ui. 250+ production-ready components, blocks, and templates. Free and open source.",
    tags: [TAGS["ui-component"]],
    url: "https://ui.spectrumhq.in/",
  },
  {
    title: "spoilerjs",
    category: CATEGORIES.ui,
    className: "bg-foreground border-paper",
    description:
      "A framework-agnostic web component for creating beautiful spoiler effects with Telegram-inspired particle animations. Easily integrates into React, Vue, Svelte, or vanilla JS.",
    favicon: "https://spoilerjs.sh4jid.me/apple-touch-icon.png",
    ogImage: "https://spoilerjs.sh4jid.me/og_image.png",
    subtitle: "Beautiful Spoiler Effects",
    tags: [TAGS["ui-component"]],
    url: "https://spoilerjs.sh4jid.me/",
  },
  {
    title: "Supabase UI Library",
    author: "Supabase",
    category: CATEGORIES.ui,
    description: "Provides a library of components for your project",
    favicon: "https://supabase.com/favicon/favicon.svg",
    ogImage: "https://supabase.com/ui/img/supabase-og-image.png",
    tags: [TAGS["ui-component"]],
    url: "https://supabase.com/ui",
  },
  {
    title: "SyntaxUI",
    category: CATEGORIES.ui,
    description:
      "Get free-to-use Prebuilt React components powered by Tailwind CSS & Framer Motion. Modern, Minimal and customizable. Just copy, paste and you're ready to go!",
    subtitle: "Free React, Tailwind CSS & Framer UI Components",
    tags: [TAGS["ui-component"]],
    url: "https://syntaxui.com/",
  },
  {
    title: "TableCraft",
    category: CATEGORIES.ui,
    description:
      "A production-ready, type-safe, fully customizable table component for modern React applications.",
    favicon: "https://react-table-craft.vercel.app/brand/logo-light.svg",
    ogImage: "https://react-table-craft.vercel.app/brand/thumnail.png",
    subtitle: "The Ultimate React Table Engine",
    tags: [TAGS["ui-component"]],
    url: "https://react-table-craft.vercel.app/",
  },
  {
    title: "Tailark",
    category: CATEGORIES.ui,
    description:
      "Speed up your workflow with responsive, pre-built UI blocks designed for marketing websites.",
    favicon: "https://tailark.com/icon.svg",
    ogImage: "https://tailark.com/opengraph-image.png",
    subtitle: "Shadcn Marketing Blocks",
    tags: [TAGS["ui-component"]],
    url: "https://tailark.com/",
  },
  {
    title: "Tegaki",
    author: "Gokhan Kurt",
    category: CATEGORIES.ui,
    description: "Animated handwriting from any font.",
    favicon: "https://gkurt.com/tegaki/favicon.svg",
    ogImage: "https://gkurt.com/tegaki/tegaki-card.png",
    tags: [TAGS.animation, TAGS.typography, TAGS["ui-component"]],
    url: "https://gkurt.com/tegaki/",
  },
  {
    title: "termcn",
    category: CATEGORIES.ui,
    description:
      "A collection of beautifully designed, accessible, and customizable terminal UI components. Built on Ink and OpenTUI. Works with shadcn/ui.",
    subtitle: "Beautiful terminal UIs, made simple",
    tags: [TAGS.development, TAGS.ui],
    url: "https://www.termcn.dev/",
  },
  {
    title: "TermUI Registry",
    category: CATEGORIES.ui,
    description: "shadcn-style terminal UI components for React + Ink",
    ogImage: "https://raw.githubusercontent.com/Arindam200/termui/main/.github/assets/demo.png",
    tags: [TAGS.terminal, TAGS["ui-component"]],
    url: "https://arindam200.github.io/termui/",
  },
  {
    title: "Thinking orbs",
    author: "Jakub Antalik",
    category: CATEGORIES.ui,
    description:
      "Dotted thought-orb loading indicators for AI and agent UIs. Nine hand-tuned states, two sizes, auto dark/light theme.",
    favicon: "https://orbs.jakubantalik.com/header.png",
    ogImage:
      "https://opengraph.githubassets.com/162bca73d172be0872926f469374c11037f77602f8739960332e0d90a4471f0c/Jakubantalik/thinking-orbs",
    subtitle: "Animated thinking orb component",
    tags: [TAGS["ui-component"]],
    url: "https://orbs.jakubantalik.com/",
  },
  {
    title: "toc-cn",
    category: CATEGORIES.ui,
    description: "A shadcn component registry for documentation-style table of contents.",
    tags: [TAGS["ui-component"]],
    url: "https://tocn.vercel.app/",
  },
  {
    title: "Trees, from Pierre",
    category: CATEGORIES.ui,
    description:
      "@pierre/trees is an open source file tree rendering library. It's built for performance and flexibility, is super customizable, and comes packed with features.",
    tags: [TAGS["ui-component"]],
    url: "https://trees.software/",
  },
  {
    title: "Uilora",
    category: CATEGORIES.ui,
    description:
      "Build stunning interfaces with 700+ premium animated components for Next.js & React Native. Copy-paste ready, production-grade UI library.",
    subtitle: "Premium UI Components for Next.js & React Native",
    tags: [TAGS["ui-component"]],
    url: "https://www.uilora.com/",
  },
  {
    title: "Uiverse",
    category: CATEGORIES.ui,
    description:
      "Community-made library of free and customizable UI elements made with CSS or Tailwind. It's all free to copy and use in your projects. Uiverse can save you many hours spent on building & customizing UI components for your next project.",
    tags: [TAGS["ui-component"]],
    url: "https://uiverse.io/",
  },
  {
    title: "unlumen UI",
    category: CATEGORIES.ui,
    description:
      "A curated registry of beautifully designed React components built with TypeScript, Tailwind CSS and Motion. Install with the shadcn CLI, customize freely, and ship production-ready interfaces faster.",
    subtitle: "Beautifully Designed React Components",
    tags: [TAGS.animation, TAGS["ui-component"]],
    url: "https://ui.unlumen.com/",
  },
  {
    title: "VCI Components",
    category: CATEGORIES.ui,
    description:
      "200+ copy-paste UI component prompts for AI-powered vibe coding. Elevate your Lovable, Cursor, and Bolt projects with premium components. Ship faster, stand out.",
    subtitle: "Premium UI Prompts for Vibe Coding | React Components",
    tags: [TAGS["ui-component"]],
    url: "https://vibecodecomponents.com/",
  },
  {
    title: "Vengeance UI",
    category: CATEGORIES.ui,
    description:
      "Animated React components and next-generation UI interactions for modern landing pages.",
    subtitle: "Animated React Components",
    tags: [TAGS["ui-component"]],
    url: "https://www.vengenceui.com/",
  },
  {
    title: "VibeUI",
    category: CATEGORIES.ui,
    description:
      "92 ready-to-copy layout prompts for vibe coding and AI UI generation. Auth, pricing, hero, bento, dashboards & more — paste into any AI tool.",
    subtitle: "92 Free UI Prompts for Vibe Coders (Auth, Pricing, Hero, Bento)",
    tags: [TAGS["ui-component"]],
    url: "https://vibeui.online/",
  },
  {
    title: "Watermelon UI",
    category: CATEGORIES.ui,
    description:
      "A collection of high-quality React components, dashboards, and UI blocks. Copy and paste production-ready UI with ease.",
    subtitle: "Premium React Components, Dashboards & Blocks",
    tags: [TAGS.animation, TAGS["ui-component"]],
    url: "https://ui.watermelon.sh/",
  },
  {
    title: "WigggleUI",
    category: CATEGORIES.ui,
    description: "A beautiful collection of 80+ copy-and-paste widgets for your next project.",
    favicon: "https://wigggle-ui.vercel.app/icon.svg",
    ogImage: "https://wigggle-ui.vercel.app/opengraph-image.png",
    subtitle: "Open Source Widgets for the Web.",
    tags: [TAGS["ui-component"]],
    url: "https://wigggle-ui.vercel.app/",
  },
];
