export type TailwindEntry = {
  className: string;
  css: string;
  category: string;
};

export const CATEGORIES = [
  "All",
  "Spacing",
  "Typography",
  "Sizing",
  "Flexbox",
  "Grid",
  "Layout",
  "Borders",
  "Effects",
  "Transitions",
] as const;

export const TAILWIND_CLASSES: TailwindEntry[] = [
  // Spacing
  { className: "p-0", css: "padding: 0px", category: "Spacing" },
  { className: "p-1", css: "padding: 0.25rem /* 4px */", category: "Spacing" },
  { className: "p-2", css: "padding: 0.5rem /* 8px */", category: "Spacing" },
  { className: "p-3", css: "padding: 0.75rem /* 12px */", category: "Spacing" },
  { className: "p-4", css: "padding: 1rem /* 16px */", category: "Spacing" },
  { className: "p-5", css: "padding: 1.25rem /* 20px */", category: "Spacing" },
  { className: "p-6", css: "padding: 1.5rem /* 24px */", category: "Spacing" },
  { className: "p-8", css: "padding: 2rem /* 32px */", category: "Spacing" },
  { className: "p-10", css: "padding: 2.5rem /* 40px */", category: "Spacing" },
  { className: "p-12", css: "padding: 3rem /* 48px */", category: "Spacing" },
  { className: "p-16", css: "padding: 4rem /* 64px */", category: "Spacing" },
  { className: "px-4", css: "padding-inline: 1rem /* 16px */", category: "Spacing" },
  { className: "py-4", css: "padding-block: 1rem /* 16px */", category: "Spacing" },
  { className: "pt-4", css: "padding-top: 1rem /* 16px */", category: "Spacing" },
  { className: "pr-4", css: "padding-right: 1rem /* 16px */", category: "Spacing" },
  { className: "pb-4", css: "padding-bottom: 1rem /* 16px */", category: "Spacing" },
  { className: "pl-4", css: "padding-left: 1rem /* 16px */", category: "Spacing" },
  { className: "m-0", css: "margin: 0px", category: "Spacing" },
  { className: "m-1", css: "margin: 0.25rem /* 4px */", category: "Spacing" },
  { className: "m-2", css: "margin: 0.5rem /* 8px */", category: "Spacing" },
  { className: "m-4", css: "margin: 1rem /* 16px */", category: "Spacing" },
  { className: "m-8", css: "margin: 2rem /* 32px */", category: "Spacing" },
  { className: "m-auto", css: "margin: auto", category: "Spacing" },
  { className: "mx-auto", css: "margin-inline: auto", category: "Spacing" },
  { className: "mx-4", css: "margin-inline: 1rem /* 16px */", category: "Spacing" },
  { className: "my-4", css: "margin-block: 1rem /* 16px */", category: "Spacing" },
  { className: "mt-4", css: "margin-top: 1rem /* 16px */", category: "Spacing" },
  { className: "mr-4", css: "margin-right: 1rem /* 16px */", category: "Spacing" },
  { className: "mb-4", css: "margin-bottom: 1rem /* 16px */", category: "Spacing" },
  { className: "ml-4", css: "margin-left: 1rem /* 16px */", category: "Spacing" },
  { className: "-m-4", css: "margin: -1rem /* -16px */", category: "Spacing" },
  { className: "gap-1", css: "gap: 0.25rem /* 4px */", category: "Spacing" },
  { className: "gap-2", css: "gap: 0.5rem /* 8px */", category: "Spacing" },
  { className: "gap-4", css: "gap: 1rem /* 16px */", category: "Spacing" },
  { className: "gap-6", css: "gap: 1.5rem /* 24px */", category: "Spacing" },
  { className: "gap-8", css: "gap: 2rem /* 32px */", category: "Spacing" },
  { className: "gap-x-4", css: "column-gap: 1rem /* 16px */", category: "Spacing" },
  { className: "gap-y-4", css: "row-gap: 1rem /* 16px */", category: "Spacing" },
  { className: "space-x-2", css: "& > * + * { margin-left: 0.5rem }", category: "Spacing" },
  { className: "space-y-2", css: "& > * + * { margin-top: 0.5rem }", category: "Spacing" },
  { className: "space-x-4", css: "& > * + * { margin-left: 1rem }", category: "Spacing" },
  { className: "space-y-4", css: "& > * + * { margin-top: 1rem }", category: "Spacing" },

  // Typography
  {
    className: "text-xs",
    css: "font-size: 0.75rem /* 12px */; line-height: 1rem",
    category: "Typography",
  },
  {
    className: "text-sm",
    css: "font-size: 0.875rem /* 14px */; line-height: 1.25rem",
    category: "Typography",
  },
  {
    className: "text-base",
    css: "font-size: 1rem /* 16px */; line-height: 1.5rem",
    category: "Typography",
  },
  {
    className: "text-lg",
    css: "font-size: 1.125rem /* 18px */; line-height: 1.75rem",
    category: "Typography",
  },
  {
    className: "text-xl",
    css: "font-size: 1.25rem /* 20px */; line-height: 1.75rem",
    category: "Typography",
  },
  {
    className: "text-2xl",
    css: "font-size: 1.5rem /* 24px */; line-height: 2rem",
    category: "Typography",
  },
  {
    className: "text-3xl",
    css: "font-size: 1.875rem /* 30px */; line-height: 2.25rem",
    category: "Typography",
  },
  {
    className: "text-4xl",
    css: "font-size: 2.25rem /* 36px */; line-height: 2.5rem",
    category: "Typography",
  },
  {
    className: "text-5xl",
    css: "font-size: 3rem /* 48px */; line-height: 1",
    category: "Typography",
  },
  {
    className: "text-6xl",
    css: "font-size: 3.75rem /* 60px */; line-height: 1",
    category: "Typography",
  },
  { className: "font-thin", css: "font-weight: 100", category: "Typography" },
  { className: "font-light", css: "font-weight: 300", category: "Typography" },
  { className: "font-normal", css: "font-weight: 400", category: "Typography" },
  { className: "font-medium", css: "font-weight: 500", category: "Typography" },
  { className: "font-semibold", css: "font-weight: 600", category: "Typography" },
  { className: "font-bold", css: "font-weight: 700", category: "Typography" },
  { className: "font-extrabold", css: "font-weight: 800", category: "Typography" },
  { className: "font-black", css: "font-weight: 900", category: "Typography" },
  {
    className: "font-mono",
    css: "font-family: ui-monospace, SFMono-Regular, …",
    category: "Typography",
  },
  {
    className: "font-sans",
    css: "font-family: ui-sans-serif, system-ui, …",
    category: "Typography",
  },
  { className: "font-serif", css: "font-family: ui-serif, Georgia, …", category: "Typography" },
  { className: "tracking-tighter", css: "letter-spacing: -0.05em", category: "Typography" },
  { className: "tracking-tight", css: "letter-spacing: -0.025em", category: "Typography" },
  { className: "tracking-normal", css: "letter-spacing: 0em", category: "Typography" },
  { className: "tracking-wide", css: "letter-spacing: 0.025em", category: "Typography" },
  { className: "tracking-wider", css: "letter-spacing: 0.05em", category: "Typography" },
  { className: "tracking-widest", css: "letter-spacing: 0.1em", category: "Typography" },
  { className: "leading-none", css: "line-height: 1", category: "Typography" },
  { className: "leading-tight", css: "line-height: 1.25", category: "Typography" },
  { className: "leading-snug", css: "line-height: 1.375", category: "Typography" },
  { className: "leading-normal", css: "line-height: 1.5", category: "Typography" },
  { className: "leading-relaxed", css: "line-height: 1.625", category: "Typography" },
  { className: "leading-loose", css: "line-height: 2", category: "Typography" },
  { className: "text-left", css: "text-align: left", category: "Typography" },
  { className: "text-center", css: "text-align: center", category: "Typography" },
  { className: "text-right", css: "text-align: right", category: "Typography" },
  { className: "text-justify", css: "text-align: justify", category: "Typography" },
  { className: "uppercase", css: "text-transform: uppercase", category: "Typography" },
  { className: "lowercase", css: "text-transform: lowercase", category: "Typography" },
  { className: "capitalize", css: "text-transform: capitalize", category: "Typography" },
  { className: "normal-case", css: "text-transform: none", category: "Typography" },
  { className: "italic", css: "font-style: italic", category: "Typography" },
  { className: "not-italic", css: "font-style: normal", category: "Typography" },
  { className: "underline", css: "text-decoration-line: underline", category: "Typography" },
  { className: "line-through", css: "text-decoration-line: line-through", category: "Typography" },
  { className: "no-underline", css: "text-decoration-line: none", category: "Typography" },
  {
    className: "truncate",
    css: "overflow: hidden; text-overflow: ellipsis; white-space: nowrap",
    category: "Typography",
  },
  { className: "text-ellipsis", css: "text-overflow: ellipsis", category: "Typography" },
  { className: "whitespace-nowrap", css: "white-space: nowrap", category: "Typography" },
  { className: "whitespace-pre", css: "white-space: pre", category: "Typography" },
  { className: "break-words", css: "overflow-wrap: break-word", category: "Typography" },
  { className: "break-all", css: "word-break: break-all", category: "Typography" },
  {
    className: "line-clamp-1",
    css: "display: -webkit-box; -webkit-line-clamp: 1; overflow: hidden",
    category: "Typography",
  },
  {
    className: "line-clamp-2",
    css: "display: -webkit-box; -webkit-line-clamp: 2; overflow: hidden",
    category: "Typography",
  },
  {
    className: "line-clamp-3",
    css: "display: -webkit-box; -webkit-line-clamp: 3; overflow: hidden",
    category: "Typography",
  },

  // Sizing
  { className: "w-0", css: "width: 0px", category: "Sizing" },
  { className: "w-1", css: "width: 0.25rem /* 4px */", category: "Sizing" },
  { className: "w-4", css: "width: 1rem /* 16px */", category: "Sizing" },
  { className: "w-8", css: "width: 2rem /* 32px */", category: "Sizing" },
  { className: "w-16", css: "width: 4rem /* 64px */", category: "Sizing" },
  { className: "w-32", css: "width: 8rem /* 128px */", category: "Sizing" },
  { className: "w-64", css: "width: 16rem /* 256px */", category: "Sizing" },
  { className: "w-1/2", css: "width: 50%", category: "Sizing" },
  { className: "w-1/3", css: "width: 33.333%", category: "Sizing" },
  { className: "w-2/3", css: "width: 66.666%", category: "Sizing" },
  { className: "w-1/4", css: "width: 25%", category: "Sizing" },
  { className: "w-3/4", css: "width: 75%", category: "Sizing" },
  { className: "w-full", css: "width: 100%", category: "Sizing" },
  { className: "w-screen", css: "width: 100vw", category: "Sizing" },
  { className: "w-auto", css: "width: auto", category: "Sizing" },
  { className: "w-fit", css: "width: fit-content", category: "Sizing" },
  { className: "w-min", css: "width: min-content", category: "Sizing" },
  { className: "w-max", css: "width: max-content", category: "Sizing" },
  { className: "h-0", css: "height: 0px", category: "Sizing" },
  { className: "h-4", css: "height: 1rem /* 16px */", category: "Sizing" },
  { className: "h-8", css: "height: 2rem /* 32px */", category: "Sizing" },
  { className: "h-16", css: "height: 4rem /* 64px */", category: "Sizing" },
  { className: "h-full", css: "height: 100%", category: "Sizing" },
  { className: "h-screen", css: "height: 100vh", category: "Sizing" },
  { className: "h-auto", css: "height: auto", category: "Sizing" },
  { className: "h-fit", css: "height: fit-content", category: "Sizing" },
  { className: "min-w-0", css: "min-width: 0px", category: "Sizing" },
  { className: "min-w-full", css: "min-width: 100%", category: "Sizing" },
  { className: "min-h-screen", css: "min-height: 100vh", category: "Sizing" },
  { className: "min-h-0", css: "min-height: 0px", category: "Sizing" },
  { className: "max-w-xs", css: "max-width: 20rem /* 320px */", category: "Sizing" },
  { className: "max-w-sm", css: "max-width: 24rem /* 384px */", category: "Sizing" },
  { className: "max-w-md", css: "max-width: 28rem /* 448px */", category: "Sizing" },
  { className: "max-w-lg", css: "max-width: 32rem /* 512px */", category: "Sizing" },
  { className: "max-w-xl", css: "max-width: 36rem /* 576px */", category: "Sizing" },
  { className: "max-w-2xl", css: "max-width: 42rem /* 672px */", category: "Sizing" },
  { className: "max-w-4xl", css: "max-width: 56rem /* 896px */", category: "Sizing" },
  { className: "max-w-6xl", css: "max-width: 72rem /* 1152px */", category: "Sizing" },
  { className: "max-w-7xl", css: "max-width: 80rem /* 1280px */", category: "Sizing" },
  { className: "max-w-full", css: "max-width: 100%", category: "Sizing" },
  { className: "max-w-none", css: "max-width: none", category: "Sizing" },
  { className: "size-4", css: "width: 1rem /* 16px */; height: 1rem", category: "Sizing" },
  { className: "size-8", css: "width: 2rem /* 32px */; height: 2rem", category: "Sizing" },
  { className: "size-full", css: "width: 100%; height: 100%", category: "Sizing" },

  // Flexbox
  { className: "flex", css: "display: flex", category: "Flexbox" },
  { className: "inline-flex", css: "display: inline-flex", category: "Flexbox" },
  { className: "flex-row", css: "flex-direction: row", category: "Flexbox" },
  { className: "flex-col", css: "flex-direction: column", category: "Flexbox" },
  { className: "flex-row-reverse", css: "flex-direction: row-reverse", category: "Flexbox" },
  { className: "flex-col-reverse", css: "flex-direction: column-reverse", category: "Flexbox" },
  { className: "flex-wrap", css: "flex-wrap: wrap", category: "Flexbox" },
  { className: "flex-nowrap", css: "flex-wrap: nowrap", category: "Flexbox" },
  { className: "flex-1", css: "flex: 1 1 0%", category: "Flexbox" },
  { className: "flex-auto", css: "flex: 1 1 auto", category: "Flexbox" },
  { className: "flex-none", css: "flex: none", category: "Flexbox" },
  { className: "grow", css: "flex-grow: 1", category: "Flexbox" },
  { className: "grow-0", css: "flex-grow: 0", category: "Flexbox" },
  { className: "shrink", css: "flex-shrink: 1", category: "Flexbox" },
  { className: "shrink-0", css: "flex-shrink: 0", category: "Flexbox" },
  { className: "items-start", css: "align-items: flex-start", category: "Flexbox" },
  { className: "items-center", css: "align-items: center", category: "Flexbox" },
  { className: "items-end", css: "align-items: flex-end", category: "Flexbox" },
  { className: "items-baseline", css: "align-items: baseline", category: "Flexbox" },
  { className: "items-stretch", css: "align-items: stretch", category: "Flexbox" },
  { className: "justify-start", css: "justify-content: flex-start", category: "Flexbox" },
  { className: "justify-center", css: "justify-content: center", category: "Flexbox" },
  { className: "justify-end", css: "justify-content: flex-end", category: "Flexbox" },
  { className: "justify-between", css: "justify-content: space-between", category: "Flexbox" },
  { className: "justify-around", css: "justify-content: space-around", category: "Flexbox" },
  { className: "justify-evenly", css: "justify-content: space-evenly", category: "Flexbox" },
  { className: "self-auto", css: "align-self: auto", category: "Flexbox" },
  { className: "self-start", css: "align-self: flex-start", category: "Flexbox" },
  { className: "self-center", css: "align-self: center", category: "Flexbox" },
  { className: "self-end", css: "align-self: flex-end", category: "Flexbox" },
  { className: "self-stretch", css: "align-self: stretch", category: "Flexbox" },
  { className: "order-first", css: "order: -9999", category: "Flexbox" },
  { className: "order-last", css: "order: 9999", category: "Flexbox" },
  { className: "order-none", css: "order: 0", category: "Flexbox" },

  // Grid
  { className: "grid", css: "display: grid", category: "Grid" },
  { className: "inline-grid", css: "display: inline-grid", category: "Grid" },
  {
    className: "grid-cols-1",
    css: "grid-template-columns: repeat(1, minmax(0, 1fr))",
    category: "Grid",
  },
  {
    className: "grid-cols-2",
    css: "grid-template-columns: repeat(2, minmax(0, 1fr))",
    category: "Grid",
  },
  {
    className: "grid-cols-3",
    css: "grid-template-columns: repeat(3, minmax(0, 1fr))",
    category: "Grid",
  },
  {
    className: "grid-cols-4",
    css: "grid-template-columns: repeat(4, minmax(0, 1fr))",
    category: "Grid",
  },
  {
    className: "grid-cols-6",
    css: "grid-template-columns: repeat(6, minmax(0, 1fr))",
    category: "Grid",
  },
  {
    className: "grid-cols-12",
    css: "grid-template-columns: repeat(12, minmax(0, 1fr))",
    category: "Grid",
  },
  { className: "grid-cols-none", css: "grid-template-columns: none", category: "Grid" },
  { className: "col-span-1", css: "grid-column: span 1 / span 1", category: "Grid" },
  { className: "col-span-2", css: "grid-column: span 2 / span 2", category: "Grid" },
  { className: "col-span-3", css: "grid-column: span 3 / span 3", category: "Grid" },
  { className: "col-span-full", css: "grid-column: 1 / -1", category: "Grid" },
  { className: "col-start-1", css: "grid-column-start: 1", category: "Grid" },
  { className: "col-end-3", css: "grid-column-end: 3", category: "Grid" },
  {
    className: "grid-rows-1",
    css: "grid-template-rows: repeat(1, minmax(0, 1fr))",
    category: "Grid",
  },
  {
    className: "grid-rows-2",
    css: "grid-template-rows: repeat(2, minmax(0, 1fr))",
    category: "Grid",
  },
  { className: "row-span-2", css: "grid-row: span 2 / span 2", category: "Grid" },
  { className: "row-span-full", css: "grid-row: 1 / -1", category: "Grid" },
  { className: "grid-flow-row", css: "grid-auto-flow: row", category: "Grid" },
  { className: "grid-flow-col", css: "grid-auto-flow: column", category: "Grid" },
  { className: "grid-flow-dense", css: "grid-auto-flow: dense", category: "Grid" },
  { className: "auto-cols-auto", css: "grid-auto-columns: auto", category: "Grid" },
  { className: "auto-cols-fr", css: "grid-auto-columns: minmax(0, 1fr)", category: "Grid" },
  { className: "auto-rows-auto", css: "grid-auto-rows: auto", category: "Grid" },
  { className: "auto-rows-fr", css: "grid-auto-rows: minmax(0, 1fr)", category: "Grid" },

  // Layout
  { className: "block", css: "display: block", category: "Layout" },
  { className: "inline-block", css: "display: inline-block", category: "Layout" },
  { className: "inline", css: "display: inline", category: "Layout" },
  { className: "hidden", css: "display: none", category: "Layout" },
  { className: "contents", css: "display: contents", category: "Layout" },
  { className: "relative", css: "position: relative", category: "Layout" },
  { className: "absolute", css: "position: absolute", category: "Layout" },
  { className: "fixed", css: "position: fixed", category: "Layout" },
  { className: "sticky", css: "position: sticky", category: "Layout" },
  { className: "static", css: "position: static", category: "Layout" },
  { className: "inset-0", css: "inset: 0px", category: "Layout" },
  { className: "inset-x-0", css: "left: 0; right: 0", category: "Layout" },
  { className: "inset-y-0", css: "top: 0; bottom: 0", category: "Layout" },
  { className: "top-0", css: "top: 0px", category: "Layout" },
  { className: "right-0", css: "right: 0px", category: "Layout" },
  { className: "bottom-0", css: "bottom: 0px", category: "Layout" },
  { className: "left-0", css: "left: 0px", category: "Layout" },
  { className: "top-full", css: "top: 100%", category: "Layout" },
  { className: "z-0", css: "z-index: 0", category: "Layout" },
  { className: "z-10", css: "z-index: 10", category: "Layout" },
  { className: "z-20", css: "z-index: 20", category: "Layout" },
  { className: "z-30", css: "z-index: 30", category: "Layout" },
  { className: "z-40", css: "z-index: 40", category: "Layout" },
  { className: "z-50", css: "z-index: 50", category: "Layout" },
  { className: "z-auto", css: "z-index: auto", category: "Layout" },
  { className: "overflow-hidden", css: "overflow: hidden", category: "Layout" },
  { className: "overflow-auto", css: "overflow: auto", category: "Layout" },
  { className: "overflow-scroll", css: "overflow: scroll", category: "Layout" },
  { className: "overflow-visible", css: "overflow: visible", category: "Layout" },
  { className: "overflow-x-hidden", css: "overflow-x: hidden", category: "Layout" },
  { className: "overflow-y-auto", css: "overflow-y: auto", category: "Layout" },
  {
    className: "container",
    css: "width: 100%; max-width varies by breakpoint",
    category: "Layout",
  },
  {
    className: "sr-only",
    css: "position: absolute; width: 1px; height: 1px; …",
    category: "Layout",
  },
  {
    className: "not-sr-only",
    css: "position: static; width: auto; height: auto; …",
    category: "Layout",
  },
  { className: "visible", css: "visibility: visible", category: "Layout" },
  { className: "invisible", css: "visibility: hidden", category: "Layout" },
  { className: "cursor-pointer", css: "cursor: pointer", category: "Layout" },
  { className: "cursor-default", css: "cursor: default", category: "Layout" },
  { className: "cursor-not-allowed", css: "cursor: not-allowed", category: "Layout" },
  { className: "cursor-grab", css: "cursor: grab", category: "Layout" },
  { className: "pointer-events-none", css: "pointer-events: none", category: "Layout" },
  { className: "select-none", css: "user-select: none", category: "Layout" },
  { className: "select-text", css: "user-select: text", category: "Layout" },
  { className: "select-all", css: "user-select: all", category: "Layout" },

  // Borders
  { className: "border", css: "border-width: 1px", category: "Borders" },
  { className: "border-0", css: "border-width: 0px", category: "Borders" },
  { className: "border-2", css: "border-width: 2px", category: "Borders" },
  { className: "border-4", css: "border-width: 4px", category: "Borders" },
  { className: "border-8", css: "border-width: 8px", category: "Borders" },
  { className: "border-t", css: "border-top-width: 1px", category: "Borders" },
  { className: "border-r", css: "border-right-width: 1px", category: "Borders" },
  { className: "border-b", css: "border-bottom-width: 1px", category: "Borders" },
  { className: "border-l", css: "border-left-width: 1px", category: "Borders" },
  { className: "border-solid", css: "border-style: solid", category: "Borders" },
  { className: "border-dashed", css: "border-style: dashed", category: "Borders" },
  { className: "border-dotted", css: "border-style: dotted", category: "Borders" },
  { className: "border-none", css: "border-style: none", category: "Borders" },
  { className: "divide-x", css: "& > * + * { border-left-width: 1px }", category: "Borders" },
  { className: "divide-y", css: "& > * + * { border-top-width: 1px }", category: "Borders" },
  { className: "rounded-none", css: "border-radius: 0px", category: "Borders" },
  { className: "rounded-sm", css: "border-radius: 0.125rem /* 2px */", category: "Borders" },
  { className: "rounded", css: "border-radius: 0.25rem /* 4px */", category: "Borders" },
  { className: "rounded-md", css: "border-radius: 0.375rem /* 6px */", category: "Borders" },
  { className: "rounded-lg", css: "border-radius: 0.5rem /* 8px */", category: "Borders" },
  { className: "rounded-xl", css: "border-radius: 0.75rem /* 12px */", category: "Borders" },
  { className: "rounded-2xl", css: "border-radius: 1rem /* 16px */", category: "Borders" },
  { className: "rounded-3xl", css: "border-radius: 1.5rem /* 24px */", category: "Borders" },
  { className: "rounded-full", css: "border-radius: 9999px", category: "Borders" },
  {
    className: "rounded-t-lg",
    css: "border-top-left-radius: 0.5rem; border-top-right-radius: 0.5rem",
    category: "Borders",
  },
  { className: "ring-1", css: "box-shadow: 0 0 0 1px rgb(0 0 0 / 0.05)", category: "Borders" },
  { className: "ring-2", css: "box-shadow: 0 0 0 2px rgb(0 0 0 / 0.05)", category: "Borders" },
  { className: "ring-4", css: "box-shadow: 0 0 0 4px rgb(0 0 0 / 0.05)", category: "Borders" },
  {
    className: "outline-none",
    css: "outline: 2px solid transparent; outline-offset: 2px",
    category: "Borders",
  },
  { className: "outline", css: "outline-style: solid", category: "Borders" },

  // Effects
  { className: "shadow-sm", css: "box-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.05)", category: "Effects" },
  {
    className: "shadow",
    css: "box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
    category: "Effects",
  },
  {
    className: "shadow-md",
    css: "box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
    category: "Effects",
  },
  {
    className: "shadow-lg",
    css: "box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
    category: "Effects",
  },
  {
    className: "shadow-xl",
    css: "box-shadow: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
    category: "Effects",
  },
  {
    className: "shadow-2xl",
    css: "box-shadow: 0 25px 50px -12px rgb(0 0 0 / 0.25)",
    category: "Effects",
  },
  { className: "shadow-none", css: "box-shadow: 0 0 #0000", category: "Effects" },
  { className: "opacity-0", css: "opacity: 0", category: "Effects" },
  { className: "opacity-25", css: "opacity: 0.25", category: "Effects" },
  { className: "opacity-50", css: "opacity: 0.5", category: "Effects" },
  { className: "opacity-75", css: "opacity: 0.75", category: "Effects" },
  { className: "opacity-100", css: "opacity: 1", category: "Effects" },
  { className: "blur-sm", css: "filter: blur(4px)", category: "Effects" },
  { className: "blur", css: "filter: blur(8px)", category: "Effects" },
  { className: "blur-md", css: "filter: blur(12px)", category: "Effects" },
  { className: "blur-lg", css: "filter: blur(16px)", category: "Effects" },
  { className: "blur-xl", css: "filter: blur(24px)", category: "Effects" },
  { className: "blur-none", css: "filter: blur(0)", category: "Effects" },
  { className: "backdrop-blur-sm", css: "backdrop-filter: blur(4px)", category: "Effects" },
  { className: "backdrop-blur", css: "backdrop-filter: blur(8px)", category: "Effects" },
  { className: "backdrop-blur-md", css: "backdrop-filter: blur(12px)", category: "Effects" },
  { className: "grayscale", css: "filter: grayscale(100%)", category: "Effects" },
  { className: "grayscale-0", css: "filter: grayscale(0)", category: "Effects" },
  { className: "brightness-50", css: "filter: brightness(0.5)", category: "Effects" },
  { className: "brightness-75", css: "filter: brightness(0.75)", category: "Effects" },
  { className: "brightness-100", css: "filter: brightness(1)", category: "Effects" },
  { className: "brightness-125", css: "filter: brightness(1.25)", category: "Effects" },
  { className: "mix-blend-multiply", css: "mix-blend-mode: multiply", category: "Effects" },
  { className: "mix-blend-screen", css: "mix-blend-mode: screen", category: "Effects" },

  // Transitions
  {
    className: "transition",
    css: "transition-property: color, background-color, border-color, …; duration: 150ms; timing: cubic-bezier(0.4, 0, 0.2, 1)",
    category: "Transitions",
  },
  {
    className: "transition-all",
    css: "transition-property: all; duration: 150ms; timing: cubic-bezier(0.4, 0, 0.2, 1)",
    category: "Transitions",
  },
  {
    className: "transition-colors",
    css: "transition-property: color, background-color, border-color, …; duration: 150ms",
    category: "Transitions",
  },
  {
    className: "transition-opacity",
    css: "transition-property: opacity; duration: 150ms",
    category: "Transitions",
  },
  {
    className: "transition-shadow",
    css: "transition-property: box-shadow; duration: 150ms",
    category: "Transitions",
  },
  {
    className: "transition-transform",
    css: "transition-property: transform; duration: 150ms",
    category: "Transitions",
  },
  { className: "transition-none", css: "transition-property: none", category: "Transitions" },
  { className: "duration-75", css: "transition-duration: 75ms", category: "Transitions" },
  { className: "duration-100", css: "transition-duration: 100ms", category: "Transitions" },
  { className: "duration-150", css: "transition-duration: 150ms", category: "Transitions" },
  { className: "duration-200", css: "transition-duration: 200ms", category: "Transitions" },
  { className: "duration-300", css: "transition-duration: 300ms", category: "Transitions" },
  { className: "duration-500", css: "transition-duration: 500ms", category: "Transitions" },
  { className: "duration-700", css: "transition-duration: 700ms", category: "Transitions" },
  { className: "duration-1000", css: "transition-duration: 1000ms", category: "Transitions" },
  { className: "ease-linear", css: "transition-timing-function: linear", category: "Transitions" },
  {
    className: "ease-in",
    css: "transition-timing-function: cubic-bezier(0.4, 0, 1, 1)",
    category: "Transitions",
  },
  {
    className: "ease-out",
    css: "transition-timing-function: cubic-bezier(0, 0, 0.2, 1)",
    category: "Transitions",
  },
  {
    className: "ease-in-out",
    css: "transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1)",
    category: "Transitions",
  },
  { className: "delay-75", css: "transition-delay: 75ms", category: "Transitions" },
  { className: "delay-100", css: "transition-delay: 100ms", category: "Transitions" },
  { className: "delay-150", css: "transition-delay: 150ms", category: "Transitions" },
  { className: "delay-300", css: "transition-delay: 300ms", category: "Transitions" },
  { className: "delay-500", css: "transition-delay: 500ms", category: "Transitions" },
  { className: "animate-none", css: "animation: none", category: "Transitions" },
  { className: "animate-spin", css: "animation: spin 1s linear infinite", category: "Transitions" },
  {
    className: "animate-ping",
    css: "animation: ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
    category: "Transitions",
  },
  {
    className: "animate-pulse",
    css: "animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
    category: "Transitions",
  },
  { className: "animate-bounce", css: "animation: bounce 1s infinite", category: "Transitions" },
  { className: "scale-50", css: "transform: scale(0.5)", category: "Transitions" },
  { className: "scale-75", css: "transform: scale(0.75)", category: "Transitions" },
  { className: "scale-90", css: "transform: scale(0.9)", category: "Transitions" },
  { className: "scale-100", css: "transform: scale(1)", category: "Transitions" },
  { className: "scale-110", css: "transform: scale(1.1)", category: "Transitions" },
  { className: "scale-125", css: "transform: scale(1.25)", category: "Transitions" },
  { className: "rotate-45", css: "transform: rotate(45deg)", category: "Transitions" },
  { className: "rotate-90", css: "transform: rotate(90deg)", category: "Transitions" },
  { className: "rotate-180", css: "transform: rotate(180deg)", category: "Transitions" },
  { className: "translate-x-1", css: "transform: translateX(0.25rem)", category: "Transitions" },
  { className: "translate-y-1", css: "transform: translateY(0.25rem)", category: "Transitions" },
  { className: "-translate-y-1", css: "transform: translateY(-0.25rem)", category: "Transitions" },
  { className: "translate-x-full", css: "transform: translateX(100%)", category: "Transitions" },
  { className: "-translate-x-full", css: "transform: translateX(-100%)", category: "Transitions" },
];
