export type StatusCategory = "1xx" | "2xx" | "3xx" | "4xx" | "5xx";

export type HttpStatus = {
  code: number;
  name: string;
  description: string;
  category: StatusCategory;
  useCase: string;
};

export const STATUS_CATEGORIES: ("All" | StatusCategory)[] = [
  "All",
  "1xx",
  "2xx",
  "3xx",
  "4xx",
  "5xx",
];

export const STATUS_CATEGORY_LABELS: Record<StatusCategory, string> = {
  "1xx": "1xx Informational",
  "2xx": "2xx Success",
  "3xx": "3xx Redirect",
  "4xx": "4xx Client Error",
  "5xx": "5xx Server Error",
};

export const HTTP_STATUS_CODES: HttpStatus[] = [
  // ─── 1xx Informational ───────────────────────────────────────────────────────
  {
    code: 100,
    name: "Continue",
    description: "The server has received the request headers and the client should proceed to send the request body.",
    category: "1xx",
    useCase: "Used with Expect: 100-continue header before sending large payloads.",
  },
  {
    code: 101,
    name: "Switching Protocols",
    description: "The requester has asked the server to switch protocols and the server has agreed to do so.",
    category: "1xx",
    useCase: "WebSocket upgrade from HTTP to WS protocol.",
  },
  {
    code: 102,
    name: "Processing",
    description: "The server has received and is processing the request, but no response is available yet.",
    category: "1xx",
    useCase: "Long-running operations like file uploads or complex database migrations.",
  },
  {
    code: 103,
    name: "Early Hints",
    description: "Allows user agents to preload resources while the server prepares the final response.",
    category: "1xx",
    useCase: "Preloading critical CSS/JS resources to improve page load time.",
  },

  // ─── 2xx Success ─────────────────────────────────────────────────────────────
  {
    code: 200,
    name: "OK",
    description: "The request was successful and the server returned the requested resource.",
    category: "2xx",
    useCase: "Standard GET response, or successful POST/PUT that returns data.",
  },
  {
    code: 201,
    name: "Created",
    description: "The request was successful and a new resource was created as a result.",
    category: "2xx",
    useCase: "Response to POST requests that create a new database record.",
  },
  {
    code: 202,
    name: "Accepted",
    description: "The request has been accepted for processing, but the processing has not been completed.",
    category: "2xx",
    useCase: "Async jobs: the server queued the task but hasn't finished it yet.",
  },
  {
    code: 203,
    name: "Non-Authoritative Information",
    description: "The response is a transformed version from a third-party proxy.",
    category: "2xx",
    useCase: "Proxy returned modified metadata (e.g., a CDN adding headers).",
  },
  {
    code: 204,
    name: "No Content",
    description: "The server successfully processed the request and is not returning any content.",
    category: "2xx",
    useCase: "DELETE requests, or updates where no body needs to be returned.",
  },
  {
    code: 205,
    name: "Reset Content",
    description: "Tells the user agent to reset the document which sent the request.",
    category: "2xx",
    useCase: "Form submission — tell the browser to clear the form after success.",
  },
  {
    code: 206,
    name: "Partial Content",
    description: "The server is delivering only part of the resource due to a Range header.",
    category: "2xx",
    useCase: "Video streaming, resumable downloads, and range requests.",
  },
  {
    code: 207,
    name: "Multi-Status",
    description: "Conveys information about multiple resources in a single response.",
    category: "2xx",
    useCase: "WebDAV bulk operations; batch API responses with mixed results.",
  },
  {
    code: 208,
    name: "Already Reported",
    description: "Used in a DAV binding, to avoid repeatedly enumerating the internal members of multiple bindings.",
    category: "2xx",
    useCase: "WebDAV — prevents duplicate entries in multi-status responses.",
  },
  {
    code: 226,
    name: "IM Used",
    description: "The server has fulfilled a GET request and the response is a representation of the result of one or more instance-manipulations.",
    category: "2xx",
    useCase: "HTTP delta encoding (RFC 3229) — rarely used in practice.",
  },

  // ─── 3xx Redirect ────────────────────────────────────────────────────────────
  {
    code: 300,
    name: "Multiple Choices",
    description: "The request has more than one possible response. The user-agent should choose one.",
    category: "3xx",
    useCase: "Content negotiation — multiple formats or languages available.",
  },
  {
    code: 301,
    name: "Moved Permanently",
    description: "The URL of the requested resource has been changed permanently.",
    category: "3xx",
    useCase: "Permanent URL redirects, SEO-friendly migrations from old URLs.",
  },
  {
    code: 302,
    name: "Found",
    description: "The URI of requested resource has been changed temporarily.",
    category: "3xx",
    useCase: "Temporary redirects, post-login redirects, feature flags.",
  },
  {
    code: 303,
    name: "See Other",
    description: "The server directs the client to get the requested resource at another URI with a GET request.",
    category: "3xx",
    useCase: "POST/Redirect/GET pattern to prevent form resubmission.",
  },
  {
    code: 304,
    name: "Not Modified",
    description: "The resource has not been modified since the version specified in If-Modified-Since.",
    category: "3xx",
    useCase: "Browser caching — tells the client to use its cached version.",
  },
  {
    code: 307,
    name: "Temporary Redirect",
    description: "The request should be repeated with another URI, but future requests should still use the original URI.",
    category: "3xx",
    useCase: "Temporary redirects that preserve the HTTP method (unlike 302).",
  },
  {
    code: 308,
    name: "Permanent Redirect",
    description: "The request and all future requests should be repeated using another URI.",
    category: "3xx",
    useCase: "Like 301, but explicitly preserves the HTTP method and body.",
  },

  // ─── 4xx Client Error ────────────────────────────────────────────────────────
  {
    code: 400,
    name: "Bad Request",
    description: "The server cannot process the request due to a client error such as malformed syntax.",
    category: "4xx",
    useCase: "Invalid JSON body, missing required fields, or malformed query params.",
  },
  {
    code: 401,
    name: "Unauthorized",
    description: "Authentication is required and has failed or has not yet been provided.",
    category: "4xx",
    useCase: "Missing or invalid authentication token (e.g., expired JWT).",
  },
  {
    code: 402,
    name: "Payment Required",
    description: "Reserved for future use; some APIs use it for subscription or quota issues.",
    category: "4xx",
    useCase: "Paywall — user's free tier is exhausted or subscription is unpaid.",
  },
  {
    code: 403,
    name: "Forbidden",
    description: "The server understood the request but refuses to authorize it.",
    category: "4xx",
    useCase: "Authenticated but lacks permission (RBAC — wrong role or scope).",
  },
  {
    code: 404,
    name: "Not Found",
    description: "The server cannot find the requested resource.",
    category: "4xx",
    useCase: "Resource does not exist, or is intentionally hidden for security.",
  },
  {
    code: 405,
    name: "Method Not Allowed",
    description: "The request method is known by the server but is not supported by the target resource.",
    category: "4xx",
    useCase: "Sending POST to a read-only endpoint, or DELETE to a create-only endpoint.",
  },
  {
    code: 406,
    name: "Not Acceptable",
    description: "The server cannot produce a response matching the Accept headers in the request.",
    category: "4xx",
    useCase: "Client requests XML but the API only returns JSON.",
  },
  {
    code: 407,
    name: "Proxy Authentication Required",
    description: "Authentication is required to use the proxy.",
    category: "4xx",
    useCase: "Corporate proxy requiring authentication before forwarding requests.",
  },
  {
    code: 408,
    name: "Request Timeout",
    description: "The server timed out waiting for the request.",
    category: "4xx",
    useCase: "Client took too long to send the full request body.",
  },
  {
    code: 409,
    name: "Conflict",
    description: "The request conflicts with the current state of the server.",
    category: "4xx",
    useCase: "Duplicate resource creation, version conflicts in optimistic locking.",
  },
  {
    code: 410,
    name: "Gone",
    description: "The resource requested is no longer available and will not be available again.",
    category: "4xx",
    useCase: "Permanently deleted resources — a stronger signal than 404.",
  },
  {
    code: 411,
    name: "Length Required",
    description: "The request did not specify the length of its content.",
    category: "4xx",
    useCase: "Server requires Content-Length header for POST/PUT requests.",
  },
  {
    code: 412,
    name: "Precondition Failed",
    description: "The server does not meet one of the preconditions the requester put on the request.",
    category: "4xx",
    useCase: "Conditional updates (If-Match) failing due to stale ETag.",
  },
  {
    code: 413,
    name: "Content Too Large",
    description: "The request entity is larger than limits defined by the server.",
    category: "4xx",
    useCase: "File upload exceeds the server's maximum allowed size.",
  },
  {
    code: 414,
    name: "URI Too Long",
    description: "The URI requested by the client is longer than the server is willing to interpret.",
    category: "4xx",
    useCase: "Extremely long query strings or base64-encoded data in URLs.",
  },
  {
    code: 415,
    name: "Unsupported Media Type",
    description: "The media format of the requested data is not supported by the server.",
    category: "4xx",
    useCase: "Sending text/plain to an endpoint that only accepts application/json.",
  },
  {
    code: 416,
    name: "Range Not Satisfiable",
    description: "The range specified in the Range header cannot be fulfilled.",
    category: "4xx",
    useCase: "Client requested a byte range beyond the end of the file.",
  },
  {
    code: 417,
    name: "Expectation Failed",
    description: "The server cannot meet the requirements of the Expect request-header field.",
    category: "4xx",
    useCase: "Server doesn't support the Expect: 100-continue handshake.",
  },
  {
    code: 418,
    name: "I'm a Teapot",
    description: "The server refuses to brew coffee because it is, permanently, a teapot.",
    category: "4xx",
    useCase: "April Fools' RFC 2324. Used humorously in developer APIs.",
  },
  {
    code: 422,
    name: "Unprocessable Entity",
    description: "The server understands the content type but was unable to process the contained instructions.",
    category: "4xx",
    useCase: "Validation errors — request is well-formed but semantically incorrect.",
  },
  {
    code: 423,
    name: "Locked",
    description: "The resource that is being accessed is locked.",
    category: "4xx",
    useCase: "WebDAV — resource is checked out or has an exclusive lock.",
  },
  {
    code: 424,
    name: "Failed Dependency",
    description: "The request failed because it depended on another request that failed.",
    category: "4xx",
    useCase: "WebDAV batch operations where a preceding operation failed.",
  },
  {
    code: 425,
    name: "Too Early",
    description: "Indicates that the server is unwilling to risk processing a request that might be replayed.",
    category: "4xx",
    useCase: "TLS 1.3 early data (0-RTT) is not safe to act upon for this request.",
  },
  {
    code: 426,
    name: "Upgrade Required",
    description: "The client should switch to a different protocol such as TLS/1.3.",
    category: "4xx",
    useCase: "Server requires the client to upgrade to a newer protocol version.",
  },
  {
    code: 428,
    name: "Precondition Required",
    description: "The origin server requires the request to be conditional.",
    category: "4xx",
    useCase: "Prevents the 'lost update problem' — ETag or Last-Modified must be provided.",
  },
  {
    code: 429,
    name: "Too Many Requests",
    description: "The user has sent too many requests in a given amount of time (rate limiting).",
    category: "4xx",
    useCase: "API rate limiting — include Retry-After header with the response.",
  },
  {
    code: 431,
    name: "Request Header Fields Too Large",
    description: "The server is unwilling to process the request because its header fields are too large.",
    category: "4xx",
    useCase: "Oversized cookies or authorization headers exceeding server limits.",
  },
  {
    code: 451,
    name: "Unavailable For Legal Reasons",
    description: "The user requested a resource that cannot legally be provided.",
    category: "4xx",
    useCase: "GDPR data removal, DMCA takedowns, government censorship.",
  },

  // ─── 5xx Server Error ────────────────────────────────────────────────────────
  {
    code: 500,
    name: "Internal Server Error",
    description: "The server encountered an unexpected condition that prevented it from fulfilling the request.",
    category: "5xx",
    useCase: "Unhandled exceptions, database errors, or misconfigured servers.",
  },
  {
    code: 501,
    name: "Not Implemented",
    description: "The server does not support the functionality required to fulfill the request.",
    category: "5xx",
    useCase: "HTTP method not implemented (e.g., server doesn't support PATCH).",
  },
  {
    code: 502,
    name: "Bad Gateway",
    description: "The server, while acting as a gateway, received an invalid response from an upstream server.",
    category: "5xx",
    useCase: "Reverse proxy (Nginx/ALB) can't reach the upstream app server.",
  },
  {
    code: 503,
    name: "Service Unavailable",
    description: "The server is not ready to handle the request — overloaded or down for maintenance.",
    category: "5xx",
    useCase: "Planned maintenance windows or traffic spikes overwhelming the server.",
  },
  {
    code: 504,
    name: "Gateway Timeout",
    description: "The server, acting as a gateway, did not receive a timely response from upstream.",
    category: "5xx",
    useCase: "Upstream service too slow — database query timeout, slow microservice.",
  },
  {
    code: 505,
    name: "HTTP Version Not Supported",
    description: "The server does not support the HTTP version used in the request.",
    category: "5xx",
    useCase: "Client sends HTTP/2 to a server that only handles HTTP/1.1.",
  },
  {
    code: 506,
    name: "Variant Also Negotiates",
    description: "Indicates an internal server configuration error in content negotiation.",
    category: "5xx",
    useCase: "Misconfigured transparent content negotiation (RFC 2295).",
  },
  {
    code: 507,
    name: "Insufficient Storage",
    description: "The method could not be performed on the resource because the server is unable to store the representation.",
    category: "5xx",
    useCase: "WebDAV — disk full; can't save the uploaded file.",
  },
  {
    code: 508,
    name: "Loop Detected",
    description: "The server detected an infinite loop while processing the request.",
    category: "5xx",
    useCase: "WebDAV PROPFIND or COPY with infinite-depth detecting circular references.",
  },
  {
    code: 510,
    name: "Not Extended",
    description: "Further extensions to the request are required for the server to fulfill it.",
    category: "5xx",
    useCase: "HTTP Extension Framework (RFC 2774) — rare in practice.",
  },
  {
    code: 511,
    name: "Network Authentication Required",
    description: "The client needs to authenticate to gain network access.",
    category: "5xx",
    useCase: "Captive portals — hotel Wi-Fi requiring login before internet access.",
  },
];
